### ISSUE TITLE
Blackrock Depths Blacksmithing Plans always empty loot 

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#10384]
Original Post: https://github.com/chromiecraft/chromiecraft/issues/2877

### What client do you play on?

esES

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

Good morning, the problem I want to report is that I spent three weeks farming the dungeon Blackrock Depths looting the item ( https://wowgaming.altervista.org/aowow/?object=173234 ) but the loot is always empty when it should give two loot options. I've tried looting it at least a hundred times a day and it always drops empty loot.

![image](https://user-images.githubusercontent.com/69435150/151241258-59c0710c-228d-48b7-85b6-ba806bb2783e.png)

### Expected Blizzlike Behaviour

Check what is happening with the loot of this item ( https://wowgaming.altervista.org/aowow/?search=Dise%C3%B1os+de+herrer%C3%ADa )

### Steps to reproduce the problem

Go in Blackrock Depths beside Golem Lord in a room insode the manufactory.
Loot the item ( https://wowgaming.altervista.org/aowow/?object=173234 ) on the table.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Server

ChromieCraft

**Comment by febaut** [comment]
Did you try multiple times? The Plans: Dark Iron Shoulders (11615) seems to has 18.3% chance only.

**Comment by jspinedas** [comment]
Yeah i hope 10 min for respawn and always empty loot. Like 50 times at day.

**Comment by Porchigone16** [comment]
Yeah i hope 10 min for respawn and always empty loot. Like 50 times at day.

**Comment by acidmanifesto** [comment]
Second opinion and only a opinion at this point which this does need to be discussed.
**No Records** for that gameobject having loot in the UDB for loot.

**That will indicate one of 2 things being the reason:**
A sniff was never recorded dealing with looting of that object Blacksmithing Plans.
It is linked to a condition of having a quest (Which none is recorded or found in any exsisting database)

**Background when it comes to loot when it comes to the udb at the time where 335 and earlier were the current retail:**
When sniffing instances were usually run due to the time constraints of the sniffer at the time with the meathod that was used. With most instances at the time, only placement of gameobjects and npcs, rotations, spells, and key loot from Mobs and Bosses were prioritized.

At this point this will fall under the common sense discussion since sniffs are not available on the game object itself so a alternative meathod of filling it with loot will need to be debated and discussed.
