### ISSUE TITLE
misplaced road signs

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#1039]
misplaced road signs
https://i5.imageban.ru/out/2018/09/28/11d3f5d50ddf0ab74b975bd342a1ee08.jpg
https://i4.imageban.ru/out/2018/09/28/ad0e2aa4c8ab2bf5c116fdb87fda4bfd.jpg
https://i4.imageban.ru/out/2018/09/28/a7285d1d6693abce76f48df7feb3043a.jpg

**Comment by BarbzYHOOL** [comment]
This issue requires 0 programming knowledge, maybe you could help us and fix it?

Fix it with GM commands, then export the SQL result and post it here

**Comment by BarbzYHOOL** [comment]
No, we must not delete them, they are just misplaced. They are from Vanilla zones.

Can you try to put them in the right place instead? they just need to be moved a little to fit each sign.

**Comment by d3tr0l** [comment]
The fix is here:

REPLACE INTO `gameobject` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES (33326, 1692, 0, 1, 1, 342.72, 1249.11, 80.8974, 2.86, -0, -0, -0.982452, -0.186518, 7200, 100, 1, 0);

REPLACE INTO `gameobject` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES (13764, 381, 0, 1, 1, -3597, -2714.84, 19.94, -3.14152, 0.69436, 0.117214, 0.700446, -0.116196, 7200, 100, 1, 0);

REPLACE INTO `gameobject` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES (16889, 19847, 1, 1, 1, -4970.3, -1712.6, -62.5, -0.802852, -0.314157, 0.070458, -0.38768, 0.863739, 180, 100, 1, 0);


The first 2 fixes are 100% blizzlike, but the third one is "just fixed"...the gobject rotation makes it impossible to rotate that gobject to align the roadsign pillar in proper angle! Because of this, i am posting another issue. But the fix above can be used and issue can be closed, until someone finds the solution not pretty. #1043

**Comment by BarbzYHOOL** [comment]
Query executed OK, 2 rows affected.

this only changes 2 rows, not 3

**Comment by BarbzYHOOL** [comment]
Also to make the object in the right position, you might need to tweak it in the DB (i did it once for a NPC) but it's very tedious and annoying :(

**Comment by d3tr0l** [comment]
It should affect 3 rows, weird. I had that in notepad i hope there is no typo in that. Should affect 6 rows in total. Weird idk why 6, should do 3 only. It is in the right position. Just put it in db and restart server. Can you confirm?

**Comment by d3tr0l** [comment]
The third query is as i wrote "not very nice" fix...but it fixes the positioning. The rotation cannot be fixed atm until that  feature gets fixed in the core.

**Comment by BarbzYHOOL** [comment]
Yes this is an useful fix anyway, thank you!!

And yes, I don't understand why it says 6 rows instead of 3.

**Comment by Mitradis** [comment]
thx for fixes.

**Comment by BarbzYHOOL** [comment]
Note: the one for grim batol is weird I admit (because no road to follow), but it doesn't hurt to have it
