### ISSUE TITLE
First aid trainer Byancie dialogue text

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#10459]
https://github.com/chromiecraft/chromiecraft/issues/2895

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The first aid trainer in Dolanaar, Byancie, gives the dialogue text about further training no matter what your skill is in first aid.
`The esteemed Doctor Gustaf VanHowzen can train you further. He can be found in Theramore treating the wounded at the barracks.`
https://wowgaming.altervista.org/aowow/?npc=6094

### Expected Blizzlike Behaviour

Byancie's dialogue text should change depending on your level in first aid, like other profession trainers.

### Steps to reproduce the problem

1. Create a new night elf character
2. Walk to Dolanaar and talk to Byancie

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by acidmanifesto** [comment]
I seen Projects only had this recreated based on requirements of the other npcs that is shown to players with items and quests that is available.

```INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(14, 5855, 7028, 0, 1, 7, 129 0, 0, 0, 0, 0, 0, '', 'Gossip Text 5855 - Show Text 7028 if no First Aid Skill),
(14, 5855, 7027, 0, 1, 7, 129 125, 0, 0, 0, 0, 0, '', 'Gossip Text 5855 - Show Text 7029 if First Aid Skill is 125),
(14, 5855, 7026, 0, 1, 7, 129 255, 0, 0, 0, 0, 0, '', 'Gossip Text 5855 - Show Text 7029 if First Aid Skill is 255);
```
![image](https://user-images.githubusercontent.com/16887899/152218819-f3ddd3d5-3da6-4aa2-bb40-3bbad16b0250.png)

So Gossip Text 5855 - Show Text 7028 if no First Aid Skill condition will show only if there is no First aid skill essentially 0 to 124.
Gossip Text 5855 - Show Text 7029 if First Aid Skill is 125 condition will only show if the player is level 125 to 224 because Deneb Walker offers a book that teaches you Expert First aid which requires First Aid skill 125 and higher,
Gossip Text 5855 - Show Text 7029 if First Aid Skill is 255 condition will only show if player is 225 or higher due to Doctor Gustaf VanHowzen offering a quest that will allow training of Artisan First Aid (Up to 300).

So far I have only seen those specification on a Re-Cretae Bases and no public sniffs has been presented to confirm those conditions. If there are any sniffs, in which i am sure there is, they are being held privately among individuals or other projects. No idea if theses are correct or not with the conditions. Please discuss this since there are no sniffs available to verify.
