### ISSUE TITLE
/src/CFBG.cpp:338:9: fatal error: no member named 'GetTeamStartLoc' in 'Battleground'

### ISSUE THREAD

**Issue by 5266869** [azerothcore/azerothcore-wotlk#10977]
### Current Behaviour

i used the newest azerothcore version,
and also the modulds also newest
when i build it , fatal error.
/src/CFBG.cpp:338:9: fatal error: no member named 'GetTeamStartLoc' in 'Battleground'

### Expected Blizzlike Behaviour

it must can be build

### Steps to reproduce the problem

update and rebuild

### AC rev. hash/commit

/src/CFBG.cpp:338:9: fatal error: no member named 'GetTeamStartLoc' in 'Battleground'

### Operating system

ubuntu 21

**Comment by Nyeriah** [comment]
We're running the latest build and the latest module revision and we have no issues compiling.

**Your module is outdated and needs updating.**

Please don't spam issues.
Please update your module.

Furthermore, the status of the CFBG module can be checked here: https://github.com/azerothcore/mod-cfbg and as can be seen there is no such issues.

The issue you're experiencing is caused because your module is outdated.
