### ISSUE TITLE
Hunter - Strange Pet Size

### ISSUE THREAD

**Issue by virgo77** [azerothcore/azerothcore-wotlk#11006]
### Current Behaviour

after taming a beast, some are really tall, others a bit small

Examples:
small pet: [image 1](https://mega.nz/file/8ChEBKTB#E4JL5Clae8734lsPZEnnukvpraCLnNHqhjVst9b9lVw) / [image 2](https://mega.nz/file/lbxwGQLL#9GPXCRWCWWHfPm3Bnb4KYEvU49xplw-13w2aFc9XENI)
tall pet: [image 1](https://mega.nz/file/FW5iwYjD#bWPQGwgeb6BBc30pHTK_vNNIhufB2HAxvAGVoHFVPKU) / [image 2](https://mega.nz/file/pDgmUYRQ#_drQXSWVF541vMvgOK4JLywku7tVGrTd6rbgqMmMXsY)

### Expected Blizzlike Behaviour

a correct pet size, according to the race

### Steps to reproduce the problem

just be level 10+ and tame some beasts

### Extra Notes

I searched on about 5 pages of actual issues, and by keyword, but I didn't find if someone opened an issue before me

### AC rev. hash/commit

AzerothCore rev. 75439773d0dd+ 2022-03-12 04:57:26 -0300 (master branch) (Win64, Release, Static)

### Operating system

core: Windows Server 2022 / db: MariaDB 10.5.12, debian 11

### Custom changes or Modules

none

**Comment by Sulan2** [comment]
Ive heard people say it was like this in WOTLK, the pets size scales with its level so the higher level it is the bigger it is
My acore is like this and all versions of Acore ive had has also been like this

**Comment by virgo77** [comment]
Hi Sulan, thanks for your answer. Damn, I didn't remember this fact! Oo
I thought it was a bug! So, I expect that with Tauren Hunters, the pet will be oversized! XD 

So, I'm 50% sorry for my issue: 50% for my 'blackout' / 50% for remembering me with this issue :)
It was useful, thanks again and play well ;)

I close this issue. Sorry again

**Comment by Sulan2** [comment]
Hey Virgo Ive finaly managed to figure out how to fix this if u want to.

There is a dbc file called Creaturefamily.dbc

In it if u set all values like this 
![image](https://user-images.githubusercontent.com/86251944/190881333-e10a5602-7da1-46e8-bf57-ff45dc864a20.png)

Then pets will not scale anything. 
This however means that no beasts in the game even in the open world will not scale either.

You have to patch this into a MPQ in order to see the changes in the game
