### ISSUE TITLE
PDUMP command not working properly with deleted/unlinked characters

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#1111]
SMALL DESCRIPTION:
If you have the "unlinked" option on for character deletes, then create a new character with the same name, the pdump command will not export the new character. It will fail with "can't dump deleted characters, aborted."

EXPECTED BLIZZLIKE BEHAVIOUR:
The command should prioritize and dump active accounts regardless if there are unlinked deletions in the database.

STEPS TO REPRODUCE THE PROBLEM:
Create a character
Log into the game
Log out and delete the character
Create a new character with the same name
Try to .pdump write the character

BRANCH(ES):
master

AC HASH/COMMIT:
d55c44c

OPERATING SYSTEM:
Windows 7/10

MODULES:
None

OTHER CUSTOMIZATIONS:
None

**Comment by Viste** [comment]
its core guild cache problem.
when you delete character core should update the cached guids, what loads in memory, but some times core don't do it.
i have i something like hack for recalculate guids when create characters, because i don't found another way how solve this type of cases
`
diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index 779695310443b144eb24a36a239e187275457577..cfbf68ecb19dc4f082a4f58fe6a23b72f5a86b7a 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -996,6 +996,24 @@ bool Player::Create(uint32 guidlow, CharacterCreateInfo* createInfo)
     // should check that skin, face, hair* are valid via DBC per race/class
     // also do it in Player::BuildEnumData, Player::LoadFromDB
 
+    //select and update guid count from DB
+    bool incHighest = true;
+    if (guidlow != 0 && guidlow <= sObjectMgr->_hiCharGuid)
+    {
+        PreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHECK_GUID);
+        stmt->setUInt32(0, guidlow);
+        PreparedQueryResult result2 = CharacterDatabase.Query(stmt);
+
+        if (result2)
+            guidlow = sObjectMgr->_hiCharGuid;                     // use first free if exists
+        else incHighest = false;
+    }
+    else
+        guidlow = sObjectMgr->_hiCharGuid;
+        
+    if (incHighest)
+        ++sObjectMgr->_hiCharGuid;
+    
     Object::_Create(guidlow, 0, HIGHGUID_PLAYER);
 
     m_name = createInfo->Name;
diff --git a/src/server/game/Globals/ObjectMgr.h b/src/server/game/Globals/ObjectMgr.h
index 4878c8a7aef1a3c2ca62fb7c059b06175ab00ce5..47877768cb8ac7bc02879eed6c4ba2365e4a941a 100644
--- a/src/server/game/Globals/ObjectMgr.h
+++ b/src/server/game/Globals/ObjectMgr.h
@@ -681,6 +681,7 @@ class PlayerDumpReader;
 
 class ObjectMgr
 {
+    friend class Player;
     friend class PlayerDumpReader;
     friend class ACE_Singleton<ObjectMgr, ACE_Null_Mutex>;
`

**Comment by StygianTheBest** [comment]
Thanks. I'll add this to my core and check it out.

**Comment by Pondaveia** [comment]
@StygianTheBest and @Viste any news on this?

**Comment by Viste** [comment]
@Pondaveia what you want?  what news ? i don't have this bug

**Comment by peti446** [comment]
Not happening anymore. Tested on fine https://github.com/azerothcore/azerothcore-wotlk/commit/003fa8773144dede989e67448bd2ffdee5222d36
