### ISSUE TITLE
[Uldaman][NPC: Revelosh] The Shaft of Tsol has incorrect drop chance.

### ISSUE THREAD

**Issue by Gultask** [azerothcore/azerothcore-wotlk#11376]
### Current Behaviour

The Shaft of Tsol (ID: 7741) has a 41% drop chance from Revelosh (ID: 6910)

### Expected Blizzlike Behaviour

WotLK drop rates on item 7741 are supposed to be 100%

### Source

The drop chance is 100% [in](https://wotlkdb.com/?item=7741) [6](https://wowgaming.altervista.org/aowow/?item=7741) [different](https://wotlk.evowow.com/?item=7741) [WotLK](https://wotlk-twinhead.twinstar.cz/?item=7741) [databases](http://wotlk.cavernoftime.com/item=7741) I [found](https://legacy-wotlk.com/?item=7741).

Although the WotLK snapshot of the Wowhead page for the item is inacessible for me, [the snapshot from January 2012 isn't](https://web.archive.org/web/20120121141909/http://www.wowhead.com:80/item=7741/the-shaft-of-tsol). and the stated drop chance there is 53%, meaning that at some point it was higher than the vanilla 41%.
Note: The item was removed during Cataclysm.

### Steps to reproduce the problem

1. teleport to Uldaman/Revelosh (ID: 6910)
2. loot him and do not get a guaranteed drop for The Shaft of Tsol (ID: 7741)

### Extra Notes

Originally reported in: https://github.com/chromiecraft/chromiecraft/issues/3336
Also reported earlier in: https://github.com/chromiecraft/chromiecraft/issues/685 and https://github.com/azerothcore/azerothcore-wotlk/issues/5909 however it was closed due to lack of sources.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Windows 10.

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by Arthus** [comment]
Also as a quick comment on #5909 which was closed because the droprate on wowhead is 41%:

The corresponding item that is combined with the Shaft of Tsol (Gni'kiv Medallion: https://classic.wowhead.com/item=7740/gnikiv-medallion#contained-in-object) has a drop rate of 100%.
It makes no sense that this has a 100% drop rate and the shaft doesn't. In this case the Medallion should be used as reference: It is the only item contained in the chest. So there are only two cases: 1) The chest hasn't been looted. Someone using the Wowhead Client can look into the chest and will see the item with 100% chance. 2) The chest has been looted. The Medallion is gone and the chest can't be interacted with anymore. So no "false loot attempts" can be made.

Also from my personal experience playing on Classic servers in the last weeks and running Uldaman a few times, the Shaft is a guaranteed drop. (If someone wants additional testing, I can solo Revelosh 10 times and drop the uncertainty to 0.01%)

I think the Wowhead data is wrong here: A player without the Wowhead Client can loot Revelosh, remove the Shaft and another player with the tracking tool will then have a look at the body and won't see the guaranteed drop. This skews the reported drop rate.
It's basically the same problem as for https://classic.wowhead.com/item=20383/head-of-the-broodlord-lashlayer and a lot of other items when a guaranteed quest item has a lower droprate on Wowhead because not every recorded kill/loot attempt was done by someone with the quest.

**Comment by Kitzunu** [comment]
Never trust wowhead
