### ISSUE TITLE
 DB restructuring - characters - character_arena_stats

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#1167]
This is part of: https://github.com/azerothcore/azerothcore-wotlk/issues/1118

**General note**: not all structure differences can or should be imported. Every change must be first verified. If a structure change is not suitable, we just close the issue.

---

Not sure about `maxMMR`, the other fields can be probably adapted.

```diff
--- Dumping structure for table acore_characters.character_arena_stats
+-- Dumping structure for table tc_characters.character_arena_stats
 DROP TABLE IF EXISTS `character_arena_stats`;
 CREATE TABLE IF NOT EXISTS `character_arena_stats` (
-  `guid` int(10) NOT NULL,
-  `slot` tinyint(3) NOT NULL,
-  `matchMakerRating` smallint(5) NOT NULL,
-  `maxMMR` smallint(5) NOT NULL,
+  `guid` int(10) unsigned NOT NULL DEFAULT '0',
+  `slot` tinyint(3) unsigned NOT NULL DEFAULT '0',
+  `matchMakerRating` smallint(5) unsigned NOT NULL DEFAULT '0',
   PRIMARY KEY (`guid`,`slot`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by Pondaveia** [comment]
So, I've been reading a bit and It seems Sunwell core people added the flag MaxMMR to avoid people losing too much mmr when they lost points. However I don't quite understand the why since in both Trinity and Azerothcore, this field is only to validate if they get below 0 MMR. In both cases they can't go lower than 0 so I think this check needs to probably be removed if we want to include this change:

Trinity core [here](https://github.com/TrinityCore/TrinityCore/blob/master/src/server/game/Battlegrounds/ArenaTeam.cpp#L446)

Azerothcore [here](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Battlegrounds/ArenaTeam.cpp#L470)

This field is probably used somewhere else but I say we create a Pull request and test if the changes heavily impact the MMR when someone loses. Otherwise it should be ok to change I think 🤔

**Comment by FrancescoBorzi** [comment]
I wouldn't risk to break game functionalities just for the sake of aligning the DB structure to TC. So we can do modification only if we are sure about what we're doing.

For example, we can probably convert `guid`  `slot` and  `matchMakerRating` to be also `UNSIGNED` if we are sure to not have any negative value there.

**Comment by Pondaveia** [comment]
True, By the way just found out that we have this configuration CONFIG_MAX_ALLOWED_MMR_DROP. So this means that servers can be configured to balance the arena stats. I say we don't merge the removal of MaxMMR since it actually helps balance out the PvP scenario on servers.

**Comment by Pondaveia** [comment]
``` c++
// pussywizard: prevent lowering MMR too much from max achieved MMR
        int32 maxAllowedDrop = (int32)sWorld->getIntConfig(CONFIG_MAX_ALLOWED_MMR_DROP);
        mod = std::min<int32>(std::max<int32>(-((int32)MatchMakerRating - (int32)MaxMMR + maxAllowedDrop), mod), 0);
...
else
        MatchMakerRating += mod;
```

So there's a limit of MMR that you can lose compared to Trinity core. This limit is calculated with the configuration i mentioned above in mind.

**Comment by Pondaveia** [comment]
Also according to TC documentation:

> guid
> The GUID of the character. See characters.guid
> 
> slot
> Arena slot index:
> 0 - 2v2
> 1 - 3v3
> 2 - 5v5
> 
> matchmakerRating
> Player's matchmaker rating

These values can never be negative, GUID for sure, Slot is never less than 0 and matchmakerRating has a check that never allows this to Drop to negative, if your MMR gets negative, it is set to 0 so we can change to unsigned.

**Comment by FrancescoBorzi** [comment]
@Pondaveia feel free to submit PR about it :)
