### ISSUE TITLE
[Talent] [Rogue] Dirty Deeds

### ISSUE THREAD

**Issue by Delrake** [azerothcore/azerothcore-wotlk#1204]
SMALL DESCRIPTION: Talent Dirty Deeds simply doesn't work

EXPECTED BLIZZLIKE BEHAVIOUR: Reduce 20 energy cost from cheap shot and garrote and increase damage of certain skills on 35% or less HP enemy.

CURRENT BEHAVIOUR: Doesn't work at all.

STEPS TO REPRODUCE THE PROBLEM:

1. Get a rogue
2. Get Dirty Deeds
3. Cheap shot/garrote stuff and get a dummy or w/e on 35% or less HP and test skills.

BRANCH(ES):
master

AC HASH/COMMIT:
008f16fac2fb 2018-12-28

OPERATING SYSTEM:
Ubuntu 18.04

MODULES:
No

OTHER CUSTOMIZATIONS:
No

**Comment by sucofog** [comment]
Code related:

https://github.com/TrinityCore/TrinityCore/commit/cf9ce100edb2a1c514d5a509870fedf1191b7da3

**Comment by FrancescoBorzi** [comment]
@sucofog can you please open a PR with that?

**Comment by Nefertumm** [comment]
Already on the core https://github.com/azerothcore/azerothcore-wotlk/blob/0e16853157cff17dcd59aac490fbd5db3da0b727/src/server/game/Entities/Unit/Unit.cpp#L10498 & https://github.com/azerothcore/azerothcore-wotlk/blob/0e16853157cff17dcd59aac490fbd5db3da0b727/src/server/game/Entities/Unit/Unit.cpp#L12033

**Comment by pklloveyou** [comment]
Energy expenditure did not decrease by 20

**Comment by wetbrownsauce** [comment]
Tested on bcddad97da7b052f6ec46cc0aa619277bbb86e23

Cannot reproduce.  

Dirty Deeds 0/2 | Dirty Deeds 2/2
------------ | -------------
Cheap Shot Cost: 60 energy | Cheap Shot Cost: 40 energy
Garrote Cost: 50 energy | Garrote Cost: 30 energy


#### Sinister Strike Damage (without stat increases from armor/weapons)
Dirty Deeds 0/2 | Dirty Deeds 2/2
------------ | -------------
<35% HP: 231 dmg | <35% HP: 279 dmg

#### Eviscerate Damage (without stat increases from armor/weapons)
Dirty Deeds 0/2 | Dirty Deeds 2/2
------------ | -------------
<35% HP: ~2300 dmg | <35% HP: ~2591 dmg

######note: values may not reflect exactly 20% damage increase due to damage dealt being a range.  


In sum: Energy reductions are applied correctly and damage of abilities increases when target is below 35% hp.
