### ISSUE TITLE
Midsummer pole dance effects missing 

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#12145]
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/3647 

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Ribbon attaches to the bottom of the pole
All the effects depending on the amount of dancing people are missing

### Expected Blizzlike Behaviour

Ribbon attaches at the top
1 person dancing adds a blue ring of fire
2 add fireworks
3 add ground flowers
6 makes it spew lava
7 people make big dancing flames spawn (npc entry 26267)

### Source

https://www.wowhead.com/object=181605/ribbon-pole#comments:id=312207
https://www.wowhead.com/npc=26267/big-dancing-flames
https://youtu.be/f4PwcnOjTCg

### Steps to reproduce the problem

1. Have 7 people use the pole
2. Notice no effects, and ribbon is on the base of the pole

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/82cfd1b8d4147f09564e692f13effc4142178d72

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by sudlud** [comment]
I've tried to look into the issue of the beam beeing connected to the bottom instead of the top
- ribbon pole beam (spell 29712) by condition always targets NPC 17066 "Ribbon Pole Debug Target"
- all Ribbon Poles (181605) already have NPC 17066 placed on top for this purpose
- ribbon pole 181605 has linked TRAP 181604
- 181604 "TEST Ribbon Pole TRAP" triggers spell 29708, which spawns an additional NPC 17066 at the ribbon pole bottom everytime (!) the ribbon pole is beeing clicked / activated
- (these additional NPCs also do NOT despawn on Event end)
- the closest NPC 17066 to the player is then usually always at the bottom pole and becomes target of ribbon pole beam spell (29712)

- the closed PR above unlinks the trap so that no additional NPCs get spawned
-> the beam then always connects to the NPC at the ribbon pole top
-> but as @Nyeriah pointed out this is not a solution.

---

My next idea was to get all close NPCs 17066 and find the one with the highest Z coordinate. Then directly cast the beam spell 29712 targetting this NPC.
But as it seems the implicit-target-condition overwrites this target (?) so the beam still connects to the bottom NPCs.

---

Also my only guess right now regarding the spawned NPCs would be to use them to count the players currently dancing at the pole somehow (?) but this would require despawning them at some point

**Comment by sudlud** [comment]
@Nyeriah 
- thanks for the hint that spell 29712 is AOE spell so it chooses its target just by the implicit-target-condition

- would despawning unwanted NPCs right before casting the beam spell be an acceptable solution for now?

because if the (additional) NPCs sit / spawn at the bottom of the pole when the beam spell gets casted it will never connect to the npc at the top of the pole, so we either have to:
- keep them from spawning in the first place (not acceptable solution?)
- despawn them
- use a different NPC at the top of the pole

or what am I missing here?

**Comment by sudlud** [comment]
here are screenshots from 2010 that show some of the effects
https://wow.zamimg.com/uploads/screenshots/normal/171943-ribbon-pole.jpg
https://wow.zamimg.com/uploads/screenshots/normal/171263-ribbon-pole-if-you-get-enough-people-to-click-on-it-the-pole-get.jpg
- 3-4 dancing flames
- 2-4 trails of lava spewing
- randomly colored beams
