### ISSUE TITLE
Death Knights are not created with a hearthstone.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#12160]
### Current Behaviour

Death Knights upon creation are given the ten [mushrooms](https://www.wowhead.com/wotlk/item=41751/black-mushroom), but nothing else.

### Expected Blizzlike Behaviour

Death Knights are supposed to have a hearthstone as well as the ten [mushies](https://www.wowhead.com/wotlk/item=41751/black-mushroom).

### Source

[World of Warcraft©: Wrath© of the Lich King©: Classic© PTR©](https://mms.businesswire.com/media/20220418005551/en/1423923/23/Wrath_of_the_Lich_King_Classic_Logo_transparent_background.jpg)

Video seen here at ~5:40: https://www.youtube.com/watch?v=rwsr_HWOOSg

### Steps to reproduce the problem

1. Create a Death Knight of any race.
2. Observe no hearthstone.

### Extra Notes

Will figure out where the hearthstone is bound to once my account is fixed.

### AC rev. hash/commit

37c1ce5e36c9749bc9a063f0621bb1f02e47a6f1

### Operating system

Windows 10 x64

### Custom changes or Modules

mod-worgoblin
mod-npc-talent-template
mod-transmog

**Comment by Kitzunu** [comment]
So here comes the decision AC has to make.

Are we going to go Blizzlike WotLK which the core and all systems are built upon.
Or are we going to rewrite the core to go in a Classic Wotlk route? This also means that thr entire authentication and client needs to be changed.

Why I say this is that iirc is Wrath DKs did not start with a hearthstone. So that is something new to classic.

**Comment by benjymansy123** [comment]
Okay I will hunt down some wrath retail footage to confirm, but my opinion is that AC should stick with wrath retail, and keep any changes made from classic to modules/custom SQL or what have you, but I'm obviously not in a position to decide that sort of thing.

**Comment by Nyeriah** [comment]
Yes, they are not created with hearthstones, you get that once you zone out of the starting area. For Archerus you always have the dark portal thing.

I'm torn whether we should go with classic wrath or keep things strict original wrath. Part of me says we should just switch over simply because classic wrath is verifyiable and wrath isn't, but I understand those who oppose the idea. That's for sources only, for client support (packs and stuff), that's an entirely different story.

**Comment by acidmanifesto** [comment]
In 3.0.4a and only on test realms we had the scourage stone for the dk. It returned the user to the ebon hold if the battle at light hopes wasnt completed.

In original 3.2.0 Unlike other classes, Death knights start without a Hearthstone.

You only get a hearthstone by fully completing the DK starting questline, including talking to your faction leader. After that you need to go to an inn and bind yourself to that inn. At that point, if you don't have a hearthstone, one will be created for you.

However with wotlk classic, i am uncertain what the changes are brought to the dk.

**Comment by benjymansy123** [comment]
![image](https://user-images.githubusercontent.com/38561765/175789479-263b7935-6275-402b-96af-9828142ec404.png)
Taken from PTR.

**Comment by acidmanifesto** [comment]
> ![image](https://user-images.githubusercontent.com/38561765/175789479-263b7935-6275-402b-96af-9828142ec404.png)
> Taken from PTR.

Interesting. So its the scourage stone from the original test realms and not the hearthstone.

**Comment by Nyeriah** [comment]
We should wait until the oficial release to addres this one then, to see what actually goes live

**Comment by benjymansy123** [comment]
My opinion remains that anything we can *prove* from original retail wrath should stay that way in AC, such as this hearthstone issue.

**Comment by acidmanifesto** [comment]
> My opinion remains that anything we can *prove* from original retail wrath should stay that way in AC, such as this hearthstone issue.

Its suprising retail are going this far with progressive. We will find out if the scourage stone is a valid item once moves forward in revision from test to live retail.

**Comment by DavuKnight** [comment]
So its Live And yse they gave them Hearthstones
![image](https://user-images.githubusercontent.com/112143769/188255393-17ae3521-bdb8-4253-aed2-7de982b94f46.png)

I think if we say we are syncing with Retail instead of OG its going to open us to DBC changes. As long as we are locked in on NO DBC changes then we have to do our best to emulate the game the DBC's came from. Sure if there is no proof use retail but if theres proof from back in the day use that. $.02

**Comment by heyitsbench** [comment]
> I think if we say we are syncing with Retail instead of OG its going to open us to DBC changes.

This issue has basically nothing to do with DBCs.

**Comment by DavuKnight** [comment]
Not sure how you'd get around it. Bug Comes in that item xyz is diferent on retail in some way... requires a dbc change or some funky c++ code to deal with it. Bug comes in that spell xyz is different on retail. The list would get eternal.

**Comment by heyitsbench** [comment]
Yes, I suppose if we were aligning the whole of AC to Wrath Classic, then DBC changes would be warranted. However, with *this particular issue*, it doesn't require a DBC change, even if the plan were to add this stone back in.

**Comment by DavuKnight** [comment]
Oh yaeh. Its the over arching conversation I was speaking to. The Answer in this case would be No Hearthstone. Match OG.
