### ISSUE TITLE
You need to log out to return the quest

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#12215]
### Current Behaviour

Many quests need to be logged out before they can be returned. They cannot be repeated before. It is accidental Find a way to reproduce today

https://youtu.be/TBJkX6gfqFg

It can be seen from the video that the task can be completed when I accept it, but I fly away on the mount provided by NPC and then fly back You can't return the task You need to log in again to return the task

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

1. .go xyz 504.003845 2008.118896 113.079597 530
2. .q a 10382
3. talk `Gryphoneer Leafbeard` fly to `Shatter Point`
4. talk `Gryphoneer Windbellow` Fly back
5. talk `Field Marshal Brock` 

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/38889324b2bd4a77b47bf4774753198e280723ec

### Operating system

Ubuntu20.04

**Comment by ZhengPeiRu21** [comment]
I can confirm this issue. I have seen is occur frequently in local testing. Recently it occurred while doing first quest in The Missing Diplomat chain (quest 1274).

**Comment by mpfans** [comment]
> 

I always thought it was random, but you can reproduce it by watching my video and following my steps

**Comment by tkn963** [comment]
I believe it has something to do with quests not updating when NPCs spawn in for the player. I see this a lot and it is quite random. Something to do with going to areas that are 'unloaded' for you. You can accept a quest, walk far away and complete the quest, when you return it has a chance of forcing a relog to talk to the NPC or if the NPC has npcflags set to allow you to talk to it no matter if there are quests or not. When you turn in the quest (or accept one) it'll force an update and start working again. It has been like this for, honestly, a long time now.

**Comment by temperrr** [comment]
Hmm so that would be like packets related then?

**Comment by tkn963** [comment]
> Hmm so that would be like packets related then?

Well, I don't know for sure - what I wrote is my guess. It doesn't happen to every player, even when a group of people arrive at a location some might not have **!** or **?** showing but some will but like I said talking to the NPCs if they have gossip options available will show quests and accepting or turning quests in causes the **!** and **?** to update. I'm not sure what in the core is causing this, only what I have experienced myself - so I can't speak for what the actual cause is.

**Comment by acidmanifesto** [comment]
I encounter this only on cc but never my local.

**Comment by tkn963** [comment]
Sometimes it doesn't happen to me for at least a full day, sometimes even longer, and then suddenly it can happen 3 or more times in a day. That is why I'm saying it's random.

One thing I notice is always happening to me is when taking the quest ```Where in the World is Hemet Nesingwary?``` from Archmage Pentarus in Dalaran and asking him to fly me to Sholazar Basin. When I go to turn the quest in the **?** is not always there. I should say that I'm usually leveling with at least 10 characters which is why I'm noticing it so frequently - and the Hemet Nesingwary issue usually happens to anywhere between 3 and 10 characters.
