### ISSUE TITLE
CTM  have some issues

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#12252]
### Current Behaviour

It's seems that some flag cause few issues in specfic condition. The recent example is with Ragnaros. Rooted caused a major where players in melee (0-3y), got any threat. 

@Si1ker had use setunitflag in the core instead of ctm
https://github.com/azerothcore/azerothcore-wotlk/pull/12245

~~It's seems also that Ghaz'ranka got  a better pathway in water without CTM than with (need confirmation).~~
https://github.com/azerothcore/azerothcore-wotlk/pull/12182

### Expected Blizzlike Behaviour

CTM shouldn't break others mechanic.

### Steps to reproduce the problem

1. Use root flag on ragnaros (and remove the flag in the core)
2. Engage in melee ranaros with 2/3  chars and look the behavior
3. Revert this and compare

### AC rev. hash/commit

[0ef7f99](https://github.com/azerothcore/azerothcore-wotlk/commit/0ef7f999db7284c2a7776b70c9ecf008d8551f16)

### Operating system

Windows 11

**Comment by acidmanifesto** [comment]
It isnt really a creature template movement (ctm) or creature movement override (cmo). The CTM and CMO are just listing what movement generators to use as defaults via ctm (creature entry specific) and cmo (creature guid specific).
Only modification dealing with ctm is the bandaid that i had to reapply to the ctm handling [#11475](https://github.com/azerothcore/azerothcore-wotlk/pull/11475/files) due to water evade issues that were happening due to the vast difference of water handling and swim\isswim\canswim between azerothcore and trinitycore.

**Comment by UltraNix** [comment]
Why this one is still opened?

**Comment by Gultask** [comment]
One of the problems was about Ragnaros not being able to be dealt with CTM, and having to be rooted in script instead. If done through CTM, he'd not recognize targets within melee range.

The other one was a mmaps issue about to be fixed by an open PR

**Comment by UltraNix** [comment]
But both are fixed.

**Comment by Gultask** [comment]
Ragnaros being handled by script is a hack, no?

**Comment by Nyeriah** [comment]
CTM has the same issue the old inhabittype had (https://github.com/azerothcore/azerothcore-wotlk/pull/8464)

Creatures must have at least one of the valid inhabittypes (ground, air, water) in order for the root flag to work. The root flag alone does not work, as in that case the creature doesn't have any valid inhabittypes.

I used the root CTM flag for all of C'thun mobs and had no issues

**Comment by Kitzunu** [comment]
Can this be closed?
