### ISSUE TITLE
Anyone find there is security breach in porject?

### ISSUE THREAD

**Issue by ballmaK** [azerothcore/azerothcore-wotlk#12372]
I have been extorted by deleting my database after installing azerothcore-wotlk with docker installation.

The guys who did this asking for 0.0183 BTC to recover my data.

Is there anyone suffer this situation?

They leave message like below:
"以下数据库已被删除：acore_auth, acore_characters, acore_world。 我们有完整的备份。 要恢复它，您必须向我们的比特币地址bc1q0utj25ran79ykxs0h296er6hypvu5fm5dye79d支付0.0183比特币（BTC）。 如果您需要证明，请通过以下电子邮件与我们联系。 ~Redacted~ 。 任何与付款无关的邮件都将被忽略！"

I believe this is a huge damage to our community!!!

** AC STAFFER REMARK**
Email address Redacted.

**Comment by acidmanifesto** [comment]
follow up with a translation:
"The following databases have been removed: acore_auth, acore_characters, acore_world. We have a full backup. To restore it, you must pay 0.0183 Bitcoin (BTC) to our Bitcoin address bc1q0utj25ran79ykxs0h296er6hypvu5fm5dye79d. If you need proof, please email below Contact us. ~Redacted~ . Any mail not related to payment will be ignored!"

The only possible way someone will be able to gain control of your SQL database is if you opened your sql port to open in your firewall and used default creditials which should of been changes when hosting a public server, or you were using RDP (Remote Desktop Protocol) with the default port and used a recycled or dictionary login\password that was known to be leaked. Please check your email at [haveibeenpwned](https://haveibeenpwned.com/) to see if your email has been found on any massleak or combo list.

 If you are running rdp ensure default ports are not used, and username of of the user profile is not a common name and not using a recycled password. Ensure default administrator account has a strong password or disabled.
 
 If you did change the login for your SQL DB then you most likely had the credential auto saved with whatever sql editor program you are using.
 
 Common Sense Rules to follow:
1) Do not pay hackers anything, there is no gaurentee they honor their end of their self proposed offer due to their dishonorable act.

2) Ensure password complexity and maintence:

```
Passwords must be at least 15 characters long.

Passwords must contain a mix of upper case letters, lower case letters, numbers, and special characters.

When a password is changed, users must not be able to use personal information such as names, telephone numbers, account names, or dictionary words.

Passwords must expire after 60 days.

Users must not be able to reuse any of their previous 10 passwords.

Ensure that the application has the capability to require that new account passwords differ from the previous password by at least four characters when a password is changed.

Users must not be able to change passwords more than once a day, except in the case of an administrator or a privileged user. Privileged users may be required to reset a user’s forgotten passwords and the ability to change passwords more than once per day.
```

In the end it is unfortunate this situation happened but the situation could of been preventible. When in doubt and you want to ensure further security of your server, use the common sense practice in password and maintence and look towards alternative av and security software that offers RCA and RDP Brutefore protection such as Malwarebytes.
