### ISSUE TITLE
[Druid] `Thorns` bug

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#12621]
### Current Behaviour

When a druid with a spell strength of 3113 cast a thorn spell to another player with a spell strength of 266, the thorn spell wrongly inherited the damage of spell strength of 3113

https://youtu.be/UvBh_eF71tA

It can be seen from the video that the damage of Druid's thorns with spell strength of 0 is 26 points. When another Druid with 3113 spell strength cast thorns to him, the damage increased from 26 points to 217 points

### Expected Blizzlike Behaviour

When a druid with a spell strength of 3113 casts a thorn spell on another player with a spell strength of 266, the damage of the thorn spell should be calculated according to the spell strength of the player who obtains the spell

### Steps to reproduce the problem

1.  Create a new Druid
2. Equip a set of T10 graduation equipment
3. Cast thorns to a player with low level and no spell strength
4. Test the damage of thorns

### AC rev. hash/commit

639dcec71fa6a299f3e3306a568e6b0a59da9038

### Operating system

Ubuntu20.04

**Comment by mpfans** [comment]
@UltraNix  tyvm

**Comment by Santaria94** [comment]
Can you provide any proof? I personally found information that what you are suggesting was a bug and was fixed in patch 3.1. The current version works correctly.

https://wowwiki-archive.fandom.com/wiki/Thorns
[Patch 3.1.0](14-Apr-2009): This spell will now properly use the druid's spell power to determine its scaling instead of the target's spell power.

**Comment by UltraNix** [comment]
@mpfans ? @Santaria94 just proofed it is okay.

**Comment by mpfans** [comment]
If it's likeblizzard... It's too buggy
