### ISSUE TITLE
talent levitation disconnect

### ISSUE THREAD

**Issue by avatar789** [azerothcore/azerothcore-wotlk#1271]
When using the levitation spell, if you remove it, then the character is disconnect. Disconnect only happens on GM account
Spell https://ru.wowhead.com/spell=1706/%D0%BB%D0%B5%D0%B2%D0%B8%D1%82%D0%B0%D1%86%D0%B8%D1%8F

**Comment by gngn7** [comment]
I just tried with and without glyph to cast it (compos was light feather since I'm 70), while falling and without falling, work fine for me, maybe you should follow the template when you make a new issue

**Comment by avatar789** [comment]
@gngn7  https://youtu.be/xjygNwGtGhM 
Here is a video showing how it all works.

**Comment by JorgeSally** [comment]
Work fine for me

Try post your answer with all the field required, could help : 

##### SMALL DESCRIPTION:
 Add a one line description of the bug 



##### EXPECTED BLIZZLIKE BEHAVIOUR:
 Describe how it should be working without the bug. 



##### CURRENT BEHAVIOUR:
 Describe the bug in detail. Database to link spells, NPCs, quests etc https://wowgaming.altervista.org/aowow/ 



##### STEPS TO REPRODUCE THE PROBLEM:
 Describe precisely how to reproduce the bug so we can fix it or confirm its existence:
 - Which commands to use? Which NPC to teleport to?
 - Do we need to have debug flags on Cmake?
 - Do we need to look at the console while the bug happens?
 - Other steps


1. 
2. 
3. 

##### EXTRA NOTES:

Any information that can help the developers to identify and fix the issue should be put here.
Examples:
- was this bug always present in AzerothCore? if it was introduced after a change, please mention it
- the code line(s) that cause the issue
- does this feature work in other server appplications (e.g. CMaNGOS, TrinityCore, etc...) ?


##### BRANCH(ES):
 Specify the branch(es) affected by this issue: master, 0.x, 1.x, or another branch. 

master


##### AC HASH/COMMIT:
 IF YOU DO NOT FILL THIS OUT, WE WILL CLOSE YOUR ISSUE! NEVER WRITE "LATEST", ALWAYS PUT THE ACTUAL VALUE INSTEAD.
Find the commit hash (unique identifier) by running "git log" on your own clone of AzerothCore or by looking at here https://github.com/azerothcore/azerothcore-wotlk/commits/master 



##### OPERATING SYSTEM:
 Windows 7/10, Debian 8/9/10, Ubuntu 16/18 etc... 



##### MODULES:
 Are you using modules? If yes, list them (note them down in a .txt for opening future issues) 



##### OTHER CUSTOMIZATIONS:
 Are you using any extra script?
 - Did you apply any core patch/diff?
 - Did you modify your database?
 - Or do you have other customizations? If yes please specify them here.





 ------------------------- THE END ------------------------------
Thank you for your contribution.
If you use AzerothCore regularly, we really NEED your help to:
 - TEST our fixes ( https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-test-a-pull-request )
 - Report issues
 - Improve the documentation/wiki
With your help the project can evolve much quicker!



 NOTE: If you intend to contribute more than once, you should really join us on our discord channel! We set cosmetic ranks for our contributors and may give access to special resources/knowledge to them! The link is on our site http://azerothcore.org/

Without any information I would say it's your anti-cheat that make this bug, but since idk if you got one.. 🤷‍

**Comment by poszer** [comment]
Tested and i can't reproduce this issue. Trying with normal and gm account ( Using as talent, and also as .learning spell ) but without disconnect or something.
