### ISSUE TITLE
Snapjaw mobs evading while swimming

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13156]
original report https://github.com/chromiecraft/chromiecraft/issues/3954
### Current Behaviour

Snapjaw mobs that are in the river that runs North/South through Alterac Mountains (and Hillsbrad Foothills) have pathing issues. River starts East of Southshore 55.0 62.1 and goes North from there.

When you commence combat with them, it causes them to evade/retreat/reset after being in combat for a few seconds. Auto attacks will not work, but you can use spells to attack and kill them, until they evade/reset.

as far as i can tell, it only happens when the player is swimming
https://user-images.githubusercontent.com/11332559/192535575-7f18a5d3-63a2-45bc-8e74-532510f85bc5.mp4

### Expected Blizzlike Behaviour

Mobs should not evade unless they player is in a location they cant get to

### Source

Previous similar issues on server

### Steps to reproduce the problem

.tele southshore (alliance)
.tele TarrenMill (Horde)
use ranged attack against Snapjaw whilst in water deep enough to be swimming
keep casting ranged spells until they evade

### Extra Notes

most consistent locations are;
68.14 20.60
NE of Tarren Mill
89.75 47.04/90.23 46.67

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

**Comment by CosmicCleric** [comment]
Curious as to why a new report was created when [#3954](https://github.com/chromiecraft/chromiecraft/issues/3954) exists?

**Comment by virgo77** [comment]
Hi!
I think it's a water collision bug, and/or maybe because of pathfinding and/or maps extraction. Maybe?

So, I tried without the pathfinding enabled and it semt to be the same. I tried with the v15 maps pack downloadable via GitHub, and I tried with my own map extraction, within different clients versions (frFR, enGB, enUS (the size of MPQ files are not totally the same between each ones. Why? I don't know...)). And the bug is still the same.

With my hunter, sometimes my pet can't attack the mob I target. And sometimes, the pet is going to do a very large deviation before reaching and attacking the creature I send it to. And sometimes, when I go out of the water, my pet is vanishing. As if he was going across the decor, like clipping. So I have to call it again with my whistle. It's annoying, especially when I'm in combat huh huh :(

What you show in your video, I had the same when I was in Bloodmyst Isle, against the murlocs, for example.

Maybe a core issue? Map extraction bug? Client MPQ files? All these at the same time?

Hope this is correctable :)

Thanks a lot!

V.

**Comment by heyitsbench** [comment]
Yes, this is an issue with mmaps.

**Comment by virgo77** [comment]
Hey, thanks for your reply
ah mmaps? Hope it's not too hard to debug, because there's a lot of file! ^^
Just to know: do you think that a fix will be up soon? I know that there are lots of more important bugs to fix before this. The game is still playable for sure. It is just to have a potential deadline :)
Bye
V.

**Comment by UltraNix** [comment]
@BeefSteaker Give me coords from .gps

**Comment by BeefSteaker** [comment]
> @BeefSteaker Give me coords from .gps

the most consistent spot is 
.go xyz -37 -1114 36

**Comment by UltraNix** [comment]
@BeefSteaker Cannot reproduce it on that spot, attacking mob with spawnId 15555

**Comment by BeefSteaker** [comment]
> @BeefSteaker Cannot reproduce it on that spot, attacking mob with spawnId 15555

i found a second spot it works consistently
.go xyz -94.3 -1116.1 35.1

https://user-images.githubusercontent.com/11332559/197395339-e35252c6-1b0a-4c31-865e-6f2188aec136.mp4
