### ISSUE TITLE
Creature of the void (part 2 of 3) xp reward increases by level

### ISSUE THREAD

**Issue by BeefSteaker** [azerothcore/azerothcore-wotlk#13213]
Original issue https://github.com/chromiecraft/chromiecraft/issues/4152
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

The xp reward for Creature of the void (part 2 of 3) changes depending on level completed

6050 at level 47 (double xp weekend on live)
https://user-images.githubusercontent.com/11332559/193467308-24874097-491f-4720-af53-3ad0fb1b8f10.mp4

4350 at level 31
![image](https://user-images.githubusercontent.com/11332559/193467447-08a42ca9-024e-424f-9d25-4c8748d31e4f.png)

850 at level 10 (correct)
![image](https://user-images.githubusercontent.com/11332559/193467359-7e5862fc-d48f-484e-8ff4-68d94219a142.png)

### Expected Blizzlike Behaviour

xp reward should be fixed/scale down with level
around 850 as far as i can tell

### Source

![image](https://user-images.githubusercontent.com/11332559/193467571-2702cc52-69d4-4a27-9c53-fa35a4bef7dd.png)
https://www.wowhead.com/wotlk/quest=1501/creature-of-the-void
![image](https://user-images.githubusercontent.com/11332559/193467598-16886ece-1e4b-4d27-a435-750046410bbc.png)

https://wowpedia.fandom.com/wiki/Creature_of_the_Void_(Orgrimmar)
![image](https://user-images.githubusercontent.com/11332559/193467633-700f3677-04a0-4c82-8373-625e80e6aba6.png)

### Steps to reproduce the problem

.quest add 1501
.quest complete 1501
.go c 256

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by archfr** [comment]
I believe it is working as it is supposed to. Inferring from the previous quest in the chain, Gan'rul's Summons, I think that the XP scaling with level is correct, since that other quest is also supposed to scale.

The page for the quest "Creature of the Void" on WoWDB indicates that it scales with level. However, I am uncertain about the reliability of WoWDB as I am relatively new to the project. https://www.wowdb.com/quests/1501-creature-of-the-void

The preceding quest in the chain, [Gan'rul's Summons](https://www.wowhead.com/wotlk/quest=1506/ganruls-summons), also scales with level in AC. According to Wowhead, this quest should not scale with level.
![imagen](https://github.com/azerothcore/azerothcore-wotlk/assets/108412182/ec83fbdd-dbea-4811-92f3-4cb069a7b623)
But comments from 2008/2009 stated that the XP reward does indeed scale.
![imagen](https://github.com/azerothcore/azerothcore-wotlk/assets/108412182/09faec68-3a84-4e28-a55c-8e2a9b55bfdd)
![imagen](https://github.com/azerothcore/azerothcore-wotlk/assets/108412182/177a03f7-20f0-4cea-b463-03dd983fe90c)

The following images are from AC eaa09ed95e20324a3cc9c9e189ad4502412f30dd
XP reward at level 10.
![imagen](https://github.com/azerothcore/azerothcore-wotlk/assets/108412182/c6eceb3e-6afd-417f-84ee-2035a9561637)
XP reward at level 64. 
![imagen](https://github.com/azerothcore/azerothcore-wotlk/assets/108412182/10c36be3-5ea1-4f24-b639-6abc2b80cdbd)
XP reward at level 79.
![imagen](https://github.com/azerothcore/azerothcore-wotlk/assets/108412182/35ee7815-5601-4689-8859-fdb91891e241)

**Comment by Kitzunu** [comment]
Rule number one. Dont trust WoWHead

**Comment by Kitzunu** [comment]
However, from what I can tell from wowhead comments, wowpedia etc the quest should indeed scale
