### ISSUE TITLE
Command: .spy follow $name does not work.

### ISSUE THREAD

**Issue by Mutevazi** [azerothcore/azerothcore-wotlk#1355]
##### SMALL DESCRIPTION:

Just does not track messages.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .spy follow $name
2. Nothing happens
3. .spy status
4. the list is empty

##### BRANCH(ES):

master

##### OPERATING SYSTEM:

Win 10 x64

##### MODULES:

Clear

##### OTHER CUSTOMIZATIONS:

Clear

**Comment by Deku** [comment]
Related to #1344  and PR #1346

**Comment by BarbzYHOOL** [comment]
plz test https://github.com/azerothcore/azerothcore-wotlk/pull/1346 @Mutevazi  https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-test-a-pull-request

**Comment by FrancescoBorzi** [comment]
@Mutevazi can you please test the solution for this bug? https://github.com/azerothcore/azerothcore-wotlk/pull/1346

**Comment by Mutevazi** [comment]
@FrancescoBorzi After installing the changes in #1346 , I unsubscribed the problem that .spy was not working.

**Comment by Mutevazi** [comment]
@BarbzYHOOL Checked Problem still exists.

**Comment by Deku** [comment]
I could finally have the time and resources to test and debug this issue and will be opening a PR asap. The problem was really stupid from my part and I'm sorry for that. Will be doing some improvements that I left behind too.

Thanks for your report!

![wowscrnshot_013119_212742](https://user-images.githubusercontent.com/800655/52094845-6c638500-259f-11e9-8b27-9576fb9e83c7.jpg)

**Comment by Deku** [comment]
Closing since the command will be removed from the core, and will be optional through a module.
