### ISSUE TITLE
【The new version of the previous compilation failure is reproduced】Duration.h:55:27: fatal error: no type named 'days' in namespace 'std::chrono' using Days = std::chrono::days;

### ISSUE THREAD

**Issue by sw586** [azerothcore/azerothcore-wotlk#13689]
### Current Behaviour

Hello, I encountered the above error when compiling using the https://github.com/azerothcore/azerothcore-wotlk (2022.11.5) repository

BUG:
```
[ 12%] Building CXX object src/common/CMakeFiles/common.dir/Collision/Management/MMapMgr.cpp.o
In file included from /root/sw-azerothcore/src/common/Collision/DynamicTree.cpp:25:
In file included from /root/sw-azerothcore/src/common/Utilities/Timer.h:22:
/root/sw-azerothcore/src/common/Utilities/Duration.h:55:27: fatal error: no type named 'days' in namespace 'std::chrono'
using Days = std::chrono::days;
             ~~~~~~~~~~~~~^
1 error generated.
```

My command process:
```
git clone https://github.com/azerothcore/azerothcore-wotlk.git --branch master --single-branch azerothcore
cd azerothcore
mkdir build
cd build

cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++-11 -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static
make -j 4
```
![image](https://user-images.githubusercontent.com/24788222/200041218-6bc4147c-6081-42dc-8fb9-7e756a3e5969.png)

![image](https://user-images.githubusercontent.com/24788222/200042648-df95203f-d765-422a-9b13-9c2ac0a32a6e.png)
![image](https://user-images.githubusercontent.com/24788222/200042725-885a7413-9705-4874-a84b-7a3d46d6d29c.png)
![image](https://user-images.githubusercontent.com/24788222/200042902-719e4da2-fb5e-4299-b12b-e68904c925ea.png)

与别人曾经的故障相同：https://github.com/azerothcore/azerothcore-wotlk/pull/12731#issuecomment-1235761453

### Expected Blizzlike Behaviour

Linux Core Installation
https://www.azerothcore.org/wiki/linux-core-installation

### Steps to reproduce the problem

`git clone https://github.com/azerothcore/azerothcore-wotlk.git --branch master --single-branch azerothcore`
`cd azerothcore`
`mkdir build`
`cd build`
`cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/ -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++-11 -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static`
![image](https://user-images.githubusercontent.com/24788222/200044864-00b7387e-317b-43ce-afda-9c85fe180a3a.png)
![image](https://user-images.githubusercontent.com/24788222/200044924-e81aa327-06fc-4767-829c-1083010cdbe2.png)
![image](https://user-images.githubusercontent.com/24788222/200044954-a17d23d3-c447-4854-bcd9-dade15799b99.png)
`make -j 4`
![image](https://user-images.githubusercontent.com/24788222/200045110-ed631e1b-5505-4eeb-bc94-fdc89d12ac9a.png)

```
[ 13%] Building CXX object src/common/CMakeFiles/common.dir/Collision/Management/MMapMgr.cpp.o
In file included from /root/azerothcore/src/common/Collision/DynamicTree.cpp:25:
In file included from /root/azerothcore/src/common/Utilities/Timer.h:22:
/root/azerothcore/src/common/Utilities/Duration.h:55:27: fatal error: no type named 'days' in namespace 'std::chrono'
using Days = std::chrono::days;
             ~~~~~~~~~~~~~^
1 error generated.
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:157: src/common/CMakeFiles/common.dir/Collision/DynamicTree.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:920: src/common/CMakeFiles/common.dir/all] Error 2
```

### Operating system

debian10 X64
CPU:AMD64

**Comment by ihardyslide** [comment]
I am experiencing the same issue with the recommended installation approach

**Comment by noisiver** [comment]
You should update Boost to at least 1.74.

**Comment by Kitzunu** [comment]
Debian not supported

**Comment by noisiver** [comment]
> Debian not supported

It is but only 11 natively has all the required packages.

**Comment by Kitzunu** [comment]
I will post this here too...

Debian is the only system where Clang11 doesn't recognize the Chrono library. Works perfectly with Clang11 on Ubuntu.

**Comment by ihardyslide** [comment]
Ok maybe then this should be written somewhere in the docs at "Requirements".
Because I only see "Debian" written there in some sections, but no mention of the version of it.

**Comment by Kitzunu** [comment]
Probably, the issue has only been brought up once before and I didnt really think about it then.

**Comment by noisiver** [comment]
Closing the issue is valid, it's not caused by AzerothCore in **any** way but rather because they didn't properly read the requirements so the issue shouldn't have been created in the first place. The specific problem they're having is because they're using Boost 1.67 which is too old.

Ubuntu is based off of Debian and both are supported if you read the information but the most important bit of information are the requirements. When installing packages you need to check what version of each package that AzerothCore requires is installed. Debian 10 requires you to build Boost, just like Ubuntu 20.04 does, to get the required version. Debian 11 has all the required packages by default, though, just like newer versions of Ubuntu - apart from 22.04 since that ships with OpenSSL 3.0.

I would say that using Debian 10 does come with issues, which is probably where the issue with Clang you mentioned comes from. It's very different in Debian 11.

I use Debian 11 myself and it's as simple as installing the packages and compiling the core - there are zero issues for me. The names of some packages do differ from Ubuntu but they're all there.

**Comment by Kitzunu** [comment]
Awesome
