### ISSUE TITLE
(DB/Spell): Thunder Clap talent bug

### ISSUE THREAD

**Issue by PivanDepolo** [azerothcore/azerothcore-wotlk#14127]
### Current Behaviour

https://www.wowhead.com/spell=6343/thunder-clap

This ability does NOT improve with the **Improved Thunder Clap** talent.

### Expected Blizzlike Behaviour

This ability should improve with this talent.

### Steps to reproduce the problem

1. Learn the "Improved Thunder Clap" talent to the maximum (3 talent points) and hit any NPC.
2. Look at the debuff of this NPC and see the problem

### AC rev. hash/commit

AzerothCore rev. 20da358afbd5+

### Operating system

Debian 11

### Custom changes or Modules

None

**Comment by Gultask** [comment]
Sorry. Added in masse and missed this one.

**Comment by Santaria94** [comment]
I know that you are using the Russian game client. Not sure about other locales, but the Russian client has a lot of visual bugs with debuffs/buffs and ability descriptions. Changes in the value of abilities by talents / glyphs in most or even in all cases are not displayed in the tooltip in any way, there is always a base value.

Therefore, you need to look at the actual change in value. In this case, it is better to use another character for testing, rather than an NPC, in order to visually see the changes in speed values in its characteristics.

Base speed
![1](https://user-images.githubusercontent.com/32459796/208733725-3ab969af-2c85-4580-8dc5-941e232e947a.jpg)

With Thunder Clap debuff (without talent)
![2](https://user-images.githubusercontent.com/32459796/208733874-4e7a412a-aeea-4339-aa0c-86a0c6bf6b56.jpg)

With Thunder Clap debuff (3/3 talent)
![3](https://user-images.githubusercontent.com/32459796/208733960-9cd62cc2-1b37-4aee-ad8c-fa30c119e7b9.jpg)

As you can see, the talent works as it should. There is a visual bug, but this is the client side, not the server side

**Comment by TheSCREWEDSoftware** [comment]
Can't reproduce the talent is working as intended.
