### ISSUE TITLE
Quest: Blueleaf Tubers

### ISSUE THREAD

**Issue by unrealking04** [azerothcore/azerothcore-wotlk#1491]
<Quest: Blueleaf Tubers razorfen Kraul>

##### SMALL DESCRIPTION:
<https://vanilla-twinhead.twinstar.cz/?quest=1221
the quest requires:

Blueleaf Tuber (6)
Crate With Holes
Snufflenose Owner's Manual
Snufflenose Command Stick

but can't drop Blueleaf Tuber (#2906)
the drop rate should be 100 %>

##### EXPECTED BLIZZLIKE BEHAVIOUR:
<obj Blueleaf Tuber dropped by mobs in the instance
Razorfen Quilguard
Razorfen Warden etc.>

##### CURRENT BEHAVIOUR:
<the mobs don't drob the obj.>

##### STEPS TO REPRODUCE THE PROBLEM:
<
1. take the quest (goto -928,98 -3697,22 8,06 1)  
2. enter the dungeon razorfen Kraul;
3. kill the mobs and drop the objects, but not the Blueleaf Tuber

##### BRANCH(ES):
<staging>

##### AC HASH/COMMIT:
<https://github.com/azerothcore/azerothcore-wotlk/commit/fce6267ae1c8221c314fea429960af825edd1c24>

##### OPERATING SYSTEM:
<linux>

**Comment by comix1988** [comment]
Branch
Staging

Operating system
Linux

**Comment by comix1988** [comment]
the item isn't dropped by the npc  but there is a way to "summon" it

![gg](https://user-images.githubusercontent.com/22867608/52979133-96f17280-33d4-11e9-8e96-3404893af230.png)

the item [[Crate With Holes]](https://wowwiki.fandom.com/wiki/Crate_With_Holes) is bugged because not summon npc

STEPS TO REPRODUCE THE PROBLEM:

.quest add 1221
.go 2095 1675 60.4 47
.add 5880
.add 6684
.add 5897
try to use [Crate With Holes]
