### ISSUE TITLE
Death Knights do not start with full health.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/azerothcore-wotlk#15115]
### Current Behaviour

Death knights are created with close to 70% of their health pool, immediately having to regenerate health.

### Expected Blizzlike Behaviour

Death Knights should be created with full health.

### Source

[Wrath Retail](https://www.youtube.com/watch?v=ADiaJS585RM?t=53).

### Steps to reproduce the problem

1. Create a Death Knight.
2. Observe.

### AC rev. hash/commit

84dc9e2ac8182e53dfca1540b3eb4f1a601128ea

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)
[mod-worgoblin](https://github.com/heyitsbench/mod-worgoblin)

**Comment by r0m1ntik** [comment]
I think this is due to the fact that when a dk enters the game for the first time, he is put on equipment that gives stats, these stats are only updated when you enter the game and not when creating a character, I did not check, but most likely because of this, somewhere in the code, you just need to swap the lines, or add them so that life is restored to the maximum.

**Comment by heyitsbench** [comment]
Moving the section at L590 of Player.cpp after the equipment section and adding a `UpdateAllStats();` right before it fixes this issue.

**Comment by r0m1ntik** [comment]
@heyitsbench Can u create pr ? Or i Can if need

**Comment by sudlud** [comment]
in your video proof the cinematic is not skipped and the DK is then seen starting at full health.

Just tested this on d21fa0cb5 and it's exactly the same - the cimenatic intro ends, the DK is at full health.

If you skip the cinematic intro, the DK will not be at full health.

I'll provide a PR in a second.
