### ISSUE TITLE
Improve configuration files' location

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#1519]
##### DESCRIPTION:

Primary:
- Add a Cmake option to specify the authserver.conf location

Secondary:
- Could also add an option to specify the modules' configuration location
- Specify the worldserver.conf location too (just change the name from  CONF_DIR to WORLDSERVER_CONF_DIR maybe?)
- Maybe add a way to rename the configuration directly in cmake so we can have "dev_1_worldserver.conf" alongside "worldserver.conf" and not overwrite it.
- Automatically read configuration files from subdirectories (read recursively, so we can organize all the configuration files how we want)
- Default output to `conf/` a separate directory from `bin/`

##### CURRENT BEHAVIOUR:

Actually all the config files are in a single location. But it's not practical.
In top of that, if you have multiple realms (worldservers), you most likely have only 1 authserver, so only 1 authserver.conf is required.

With my suggestions, we could have a structure like that:
```
conf/authserver.conf
conf/worldserver_1.conf
conf/dev/worldserver_1.conf
conf/dev/worldserver_2.conf
conf/my_modules/module_1.conf
conf/talamortis_modules/module_1.conf
conf/WIP_modules/module_1.conf
```

**Comment by AyaseCore** [comment]
Multiple "worldserver" can use this structure：
authserver.conf
authserver.exe
data/map
data/...
data/dbc
worldserver1/worldserver.exe
worldserver1/worldserver.conf
worldserver2/worldserver.exe
worldserver2/worldserver.conf

So I think it's okay if worldserver doesn't change.
But the config of the module does need to be sorted out, because it looks too messy at the moment.
Loading the config of the module in a new way before is a good start because it manages the config of the module in a unified way (previously each module handled the config).We can unify the config of the module into one directory

The final directory structure may be:
authserver.conf
authserver.exe
data/map
data/...
data/dbc
worldserver1/worldserver.exe
worldserver1/worldserver.conf
worldserver1/mod_config/xxx.conf
...
worldserver1/logs/server.log
...
worldserver2/...
...

**Comment by BarbzYHOOL** [comment]
Personally, I put my conf in a specific directory, not alongside the binary (.exe...)

**Comment by Winfidonarleyan** [comment]
I made for myself
`-- Windows`
1. Root dir
![image](https://user-images.githubusercontent.com/18329778/87097029-61ba1e80-c26e-11ea-811d-6b644ca47272.png)
2. `/configs`
![image](https://user-images.githubusercontent.com/18329778/87097079-87dfbe80-c26e-11ea-929f-418e7df9af57.png)
3. `/configs/modules`
![image](https://user-images.githubusercontent.com/18329778/87097087-8d3d0900-c26e-11ea-9ba7-9ce45d58e141.png)

`-- Linux`
1. `./etc`
![image](https://user-images.githubusercontent.com/18329778/87097133-b198e580-c26e-11ea-9adf-d475e0b71589.png)
2. `modules`
![image](https://user-images.githubusercontent.com/18329778/87097155-beb5d480-c26e-11ea-9fb4-02fceb72b610.png)

**Comment by Kitzunu** [comment]
Going to close this as we have the conf directory now
