### ISSUE TITLE
ObjectGridUnloader::Visit  crash

### ISSUE THREAD

**Issue by boom8866** [azerothcore/azerothcore-wotlk#15371]
### Current Behaviour

https://gist.github.com/boom8866/91b5548aa8f3c385533add4a96eb5f85

### Expected Blizzlike Behaviour

no

### Source

no

### Steps to reproduce the problem

no

### Extra Notes

no

### AC rev. hash/commit

no

### Operating system

Debian 10 x64

### Custom changes or Modules

Anticheat
BGReward
CFBG
mod_LuaEngine
GMChatColor
VIPChatColor
Individual-XP
InstanceBuff
mod_multilogin
ServerAutoShutdown.conf .dist
SkipDKModule
SoloLfg
transmog
UnbindInstance
mod-zone-difficulty

**Comment by boom8866** [comment]
PreloadAllNonInstancedMapGrids = 1  Will he start network uninstallation?

**Comment by crackxia** [comment]
I have encountered a similar issue, which seems to be caused by a bug in the list of m_modAuras being released.

**Comment by boom8866** [comment]
@crackxia  Can you tell me the mod connection?

**Comment by crackxia** [comment]
> @crackxia Can you tell me the mod connection?

I can now confirm that this issue is caused by an error in the release of m_modAuras in the Unit destructor function. It is possible that incorrect objects were inserted or memory corruption occurred. I haven't been able to resolve this issue for the time being. m_modAuras is defined in Unit.h

`AuraEffectList m_modAuras[TOTAL_AURAS];`

**Comment by crackxia** [comment]
This issue is due to the same reason.
#16128
