### ISSUE TITLE
Dead in Raid cannot be revived.

### ISSUE THREAD

**Issue by EvilCalf** [azerothcore/azerothcore-wotlk#15370]
### Current Behaviour

![image](https://user-images.githubusercontent.com/35754619/224660188-ff408c2d-334e-4fe6-854b-84e9bf42b694.png)
After died in Raid, and lost connect from the server, the character is in state of soul.
In a state of soul, but has blood bar and the character can regenerate health.
In this state, any pop-up confirmation boxes are gone including reviving or summon.

### Expected Blizzlike Behaviour

Keep the state of corpse or revived correctly.

### Source

[11298f8](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots/commit/11298f80442173dccf4c76a10696337554ee8667)

### Steps to reproduce the problem

1. Battle in ICC or TOC(Raid)
2. Die in raid.
3. Dont release the soul, and close the game or lost connect from the server.
4. Log in again
5. The character is in uncommon soul state.

### AC rev. hash/commit

AzerothCore rev. 11298f804421 2023-03-11 18:11:37 +0700 (npcbots_3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80032
Using CMake version: 3.16.3
Compiled on: Linux
Worldserver listening connections on port 41952
Realmlist (Realm Id: 1) configured in port 41952
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /opt/1/azeroth-server/data/maps. Total size: 291014339 bytes
vmaps directory located in /opt/1/azeroth-server/data/vmaps. Total size: 658111192 bytes
mmaps directory located in /opt/1/azeroth-server/data/mmaps. Total size: 2192899000 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.9-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-1v1-arena
- mod-ah-bot
- mod-transmog
- mod-weekend-xp

### Operating system

ubuntu 20.0.4

**Comment by Tony931023** [comment]
I think this does not correspond to AC since you use a modification of the core to allow NPC Bots. I tried to do the steps you say in the clean core but I think that this should be exposed to the developer https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots since in the AC core, it does not happen.

I tried dying and closing the game, dying and disconnecting the network, dying and bringing down the server, and in all cases it let me revive normally

From me this issue should be closed, since it is not a problem in AC, write the issue to @trickerer who is maintaining the core you use https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots

**Comment by EvilCalf** [comment]
Thank you

**Comment by Nyeriah** [comment]
Closing following the feedback above
