### ISSUE TITLE
[RACIAL SPELL] Shadowmeld

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#1548]
##### SMALL DESCRIPTION:

- The cooldown is started immediately after using the spell.
- When we are eating and we start it, it interrupts the action of eating

##### EXPECTED BLIZZLIKE BEHAVIOUR:

- The cooldown must not be triggered immediately after using the spell. But wait until you move or disable the spell manually
- It shouldn't interrupt eating or drinking

##### CURRENT BEHAVIOUR:

The cooldown is started immediately after using the spell.
![wowscrnshot_030219_213731](https://user-images.githubusercontent.com/31663279/53687362-0439c780-3d34-11e9-9965-974567768c56.jpg)
- When we are in combat we can use it.
- When we are eating and we start it, it interrupts the action of eating

##### STEPS TO REPRODUCE THE PROBLEM:

1. create nightelfe
2. use racial spell Shadowmeld
3. look the icon
4. eat or drink or both
5. use the spell

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

75bf44d 

##### OPERATING SYSTEM:

Win10

**Comment by Makpptfox** [comment]
> The cooldown must not be triggered immediately after using the spell. But wait until you move or disable the spell manually.

- Not in TLK, as of patch 3.0.3 I quote : "Cooldown starts upon melding instead of on becoming visible." (https://wow.gamepedia.com/Shadowmeld)

> When we are in combat we can use it.

- Also intended, as of patch 3.0.2 "[...] able to use in combat." (same source as above)

> When we are eating and we start it, it interrupts the action of eating

- I don't have any proof for this one beside my own experience, but eating and using stealth doesn't stop your character from eating, but shadowmeld sure did back then. Take my words for what it's worth tho.

**Comment by Maurowin** [comment]
U'are right, on your link shadowmeld interrupt eating action.
Wrath of the Lich King Patch 3.0.2 (2008-10-14): Cooldown increased to 2 minutes, able to use in combat. Can no longer eat while in Shadowmeld. If you are eating and/or drinking and then Shadowmeld, you stop eating/drinking 

I think west can close this issue
