### ISSUE TITLE
Doubt: ScriptMgr hook behavior

### ISSUE THREAD

**Issue by GoMateoGo** [azerothcore/azerothcore-wotlk#15893]
### Describe your feature request or suggestion in detail

Similarly, they can all return specific values that can be referenced and modified Why not bool, modify the reference by returning specific values. Because I added hooks myself through eluna, but the actual situation is not what I imagined

### Describe a possible solution to your feature or suggestion in detail

For example, this eluna hook.
https://github.com/azerothcore/mod-eluna/issues/122

I'm just confused

### Additional context

![image](https://user-images.githubusercontent.com/18229643/230780299-9460bdbc-c3c3-46c9-ae8a-e26a2d8919db.png)

**Comment by Kitzunu** [comment]
You make no sense. Try to explain again so you can be understood

**Comment by acidmanifesto** [comment]
We do not read minds. What is happening compared to what you are expecting to happen. What revision are you using. What version of eluna you are using?
I am attempting to inplement a hookt with eluna or in the core?
There is little to no information and the screen shots tell us nothiny.

**Comment by Nyeriah** [comment]
The damage/healing is altered after it is processed (when the creature receives the damage/heal and it's hp is modified), so it won't show you the updated values when you hit it

**Comment by hahalmtdhl** [comment]
@Nyeriah Thank you for your answer. If I want it to be updated, what should I do? Or what keywords to refer to?
I created a new OnDamage script in C++and loaded it. The modified values can be updated

**Comment by hahalmtdhl** [comment]
@Kitzunu Thank you for your reply
Because some C++hooks are of void type but have reference parameters, I tried to create new hooks in C++and load them to modify their reference values, and the client displayed them as modified values. However, although I could change the actual reference values by adding eluna hooks, the client displayed the values before the modification

**Comment by Kitzunu** [comment]
just share your code

**Comment by hahalmtdhl** [comment]
@Kitzunu 
The following is the eluna module code:
![image](https://user-images.githubusercontent.com/18229643/231136315-d762a139-03fe-4a3c-9bd7-8de9f5a7d9dd.png)
![image](https://user-images.githubusercontent.com/18229643/231136220-d27b48a1-4ea1-418c-a796-299d63af917c.png)
![image](https://user-images.githubusercontent.com/18229643/231136568-d52f7ae9-d886-44de-9805-ad1397a0d2f0.png)
The following is the C++code:
![image](https://user-images.githubusercontent.com/18229643/231136779-3b5be852-b35b-4155-bd26-607eefb8b0bf.png)
![image](https://user-images.githubusercontent.com/18229643/231136930-1f177151-8637-4f25-a75d-fe51c55ea53d.png)

I didn't copy the code, but took a screenshot because I tried to add the code using '', but the preview looked very messy and terrible
