### ISSUE TITLE
[server] my server is experiencing spell casting delays

### ISSUE THREAD

**Issue by zoo0074** [azerothcore/azerothcore-wotlk#16339]
Spell casting delay.
My server configuration is 40H 128G bandwidth 100Mb.
Console display
	Line 2589: Update time diff: 11. Players online: 675.
	Line 2604: Update time diff: 22. Players online: 666.
	Line 2647: Update time diff: 27. Players online: 672.
	Line 2669: Update time diff: 9. Players online: 676.
	Line 2692: Update time diff: 13. Players online: 662.
	Line 2718: Update time diff: 13. Players online: 660.
	Line 2731: Update time diff: 38. Players online: 667.
	Line 2753: Update time diff: 48. Players online: 675.
	Line 2800: Update time diff: 35. Players online: 673.
	Line 2824: Update time diff: 167. Players online: 655.
	Line 2856: Update time diff: 58. Players online: 665.
	Line 2882: Update time diff: 394. Players online: 652.
	Line 2924: Update time diff: 488. Players online: 644.
	Line 3000: Update time diff: 296. Players online: 636.
@FrancescoBorzi @Winfidonarleyan @UltraNix Have a look,please

**Comment by Kitzunu** [comment]
Okay so because you are probably going to ask why I closed it

1. You do not follow the bug report template
2. You are not reporting a bug, you are just complaining you got some delay. Which for all I know is caused by custom changes you made
3. You did not post a rev/hash
4. Never ping people

Have a wonderful day =)
