### ISSUE TITLE
[Boss Cities Leaders] I am not sure if it's bugged or i should change it from database...

### ISSUE THREAD

**Issue by Alexander990608** [azerothcore/azerothcore-wotlk#16520]
### Current Behaviour

Hello! Leader Bosses on Horde and Alliance cities has less  corpse decay. Their portrait are "??" which means they are "Boss". The thing is Corpse decay for Bosses is 1 hour if it's not looted, if it is looted, then 30 minutes. Mine it is 10 minutes if it's not looted and 5 mins if i loot it. How i can fix it?

### Expected Blizzlike Behaviour

Corpse should disappear after 30 minutes if it's looted or 1 hour if it's not looted by the player.

### Source

i don't have the source but, this is happening to my server, how i can fix this?

### Steps to reproduce the problem

1. .tele stormwkindkeep
2. Kill King Varian Wrynn.
3. Write .npc info command and check respawn time.

### AC rev. hash/commit

-

### Operating system

windows 10

### Custom changes or Modules

mod-ah-bot
mod-autobalance
mod-customlogin
mod-eluna
mod-instance-reset
mod-learn-spells
mod-npc-buffer
mod-solo-lfg
mod-solocraft
mod-transmog

**Comment by noisiver** [comment]
Aside from the fact that the report hasn't been filled out properly, it's not related to the database afaik. The *corpse decay* rate, as it's called in the core, is handled by the core.

I can't find any shred of information on corpse decay and how long it should be or even if it was changed and if so when and how. We would need proof that it's wrong, i.e by timing it using classic wotlk since it's the only active source we have, or it won't be changed.
