### ISSUE TITLE
Missing Class Skills on Skill Panel (K Hotkey)

### ISSUE THREAD

**Issue by gtao725** [azerothcore/azerothcore-wotlk#1659]
##### SMALL DESCRIPTION:

Class skills seem to be missing on the Skill Panel (when you press K) of all classes except Death Knights.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

All specs (normally 3 in total in correspondence to talent specs) should show as class skills, showing only 1 or 2 is NOT CORRECT. eg. the Death Knight class skills are the only ones that show correctly:

![image](https://user-images.githubusercontent.com/35093669/55291536-1cbfff00-5412-11e9-8d1d-c413e90a4da7.png)

##### CURRENT BEHAVIOUR:

![image](https://user-images.githubusercontent.com/35093669/55291544-36f9dd00-5412-11e9-9bc2-ea1880976e12.png)
Warlock: Missing Affliction.
![image](https://user-images.githubusercontent.com/35093669/55291548-411bdb80-5412-11e9-97b3-0cb31028a167.png)
Mage: Missing Arcane
![image](https://user-images.githubusercontent.com/35093669/55291551-4c6f0700-5412-11e9-9f43-927f304dcc7a.png)
Paladin: Missing Protection
![image](https://user-images.githubusercontent.com/35093669/55291554-58f35f80-5412-11e9-8c65-c9cefa90eb53.png)
Warrior: Missing Fury and Protection
![image](https://user-images.githubusercontent.com/35093669/55291565-6a3c6c00-5412-11e9-8eab-87ce0ff94ad5.png)
Hunter: Missing Beast Mastery
![image](https://user-images.githubusercontent.com/35093669/55291573-788a8800-5412-11e9-84a6-32c996d0e754.png)
Rogue: Missing Subtlety
![image](https://user-images.githubusercontent.com/35093669/55291581-850ee080-5412-11e9-8f54-760411f90c17.png)
Priest: Missing Shadow and Discipline
![image](https://user-images.githubusercontent.com/35093669/55291585-8c35ee80-5412-11e9-9c88-ddd9285b9403.png)
Shaman: Missing Enhancement
![image](https://user-images.githubusercontent.com/35093669/55291591-9657ed00-5412-11e9-9677-733f6b3ff417.png)
Druid: Missing Feral Combat
##### STEPS TO REPRODUCE THE PROBLEM:

1. Press K when logged in as Paladin/Druid/Rogue/Mage/Warlock/Warrior/Shaman/Priest/Hunter

##### EXTRA NOTES:

N/A

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

0f174ef

##### OPERATING SYSTEM:

Win 7/10/Svr 2016

##### MODULES:

N/A

##### OTHER CUSTOMIZATIONS:

N/A

**Comment by poszer** [comment]
Just how i can see, only DK is correct there. Other need to show all 3 spec's in skill tab. Good catch @gtao725

**Comment by gtao725** [comment]
@poszer no probs, I hope it isn't too much trouble fixing this one.

**Comment by Falstring** [comment]
TC has this issue as while back. It's only a visual that can be easily fixed.

https://github.com/TrinityCore/TrinityCore/issues/12311

**Comment by poszer** [comment]
> TC had this issue as while back. It's only a visual that can be easily fixed.
> 
> [TrinityCore/TrinityCore#12311](https://github.com/TrinityCore/TrinityCore/issues/12311)

Yeah, already on list to port. Thank you anyway for ref @Falstring

**Comment by pklloveyou** [comment]
TC repair is not correct.
The correct way to display it is to show the system name in the professional skills after learning the skills of that system.
:Google Translate

**Comment by JamesGent** [comment]
Issue still exists I would recommend anyone competant to port the trinitycore fix from 2014.

https://github.com/TrinityCore/TrinityCore/issues/12311

https://github.com/TrinityCore/TrinityCore/commit/2a3546ca36468b81d673bdb27315006144af3165

![Desktop 27-11-2020 18-24-36-561](https://user-images.githubusercontent.com/61194190/100476577-dbe42600-30dd-11eb-9e37-02f29593a0b1.png)

**Comment by BarbzYHOOL** [comment]
So, this PR has been started https://github.com/azerothcore/azerothcore-wotlk/pull/1817 to fix the issue

But we DONT want to do exactly that. We don't want to remove the original playercreateinfo_spell table in favour of playercreateinfo_skills and because in the PR it means reading the class spells from the DBC. We don't want to read from the DBC, we want to read from the DB (we ported several DBC to the DB unlike other emulators), it's more flexible and DBC are made for client anyway. We also don't want to screw up every custom query made in history about this table (imo) and about existing custom changes on people's servers without them having to resort to DBC editing...

However, the new table playercreateinfo_skills sounds interesting and useful.
We should use this PR (or TC commits) as a base, add the new skill table and keep the old spell table.

**Comment by T1ti** [comment]
> existing custom changes on people's servers without them having to resort to DBC editing...

I'm pretty sure you need to update the skillLine DBCs regardless or you spells won't work properly.

I recently had to convert all of my _skills table from TC to this _spells table recently when moving from TC to AC and it wasn't fun, This table is very badly designed, why are all class skills using a specific race mask rather than 0 ? Classes are generic
