### ISSUE TITLE
The Forging of Quel'Serrar quest doesn't work

### ISSUE THREAD

**Issue by star69rem** [azerothcore/azerothcore-wotlk#16628]
### Current Behaviour

You can't use the Ancient Unfired Blade. It won't drop the sword anywhere. Just says it's not ready yet.

### Expected Blizzlike Behaviour

In the original game, you can drop the ancient unfired blade basically anywhere. Even in a BG.

### Steps to reproduce the problem

Be on the quest and use the ancient unfired blade.

### AC rev. hash/commit

fb7164be05ff_

### Operating system

Windows 10

**Comment by heyitsbench** [comment]
First: fix the revision hash. Second: please provide a source.

**Comment by star69rem** [comment]
I don't know how to get the revision hash. The command provided doesn't work or return anything. 

What do you mean by source?

**Comment by heyitsbench** [comment]
> I don't know how to get the revision hash. The command provided doesn't work or return anything.

`.server debug` or `.server info` will provide the revision hash. Typing them in the worldserver console will also give you the hash, and it will provide it during startup.

> What do you mean by source?

I mean some sort of evidence that what you claim as the expected behavior is correct. A video, screenshot, or comment related to live Blizzard servers (preferably around the time of 3.3.5a) are typical sources. You can see [this issue](https://github.com/azerothcore/azerothcore-wotlk/issues/16525) as an example of a provided source.

**Comment by Johaine** [comment]
The quest for forging the original Quel'Serrar was disabled/removed in Patch 3.2.2 when Onyxia was revamped as a level 80 encounter: https://www.wowhead.com/wotlk/quest=7509/the-forging-of-quelserrar
And the item lost its use effect if people had it in their inventory: https://www.wowhead.com/wotlk/item=18489/unfired-ancient-blade

The the question would rather be: How did you acquire the quest and the item if it shouldn't be part of 3.3.5a anymore.

**Comment by Kitzunu** [comment]
Closing as no rev is given. Could be an old or modified version of the core

**Comment by star69rem** [comment]
No, this is the latest version of chromie craft. I'm not running a server myself.

**Comment by heyitsbench** [comment]
> No, this is the latest version of chromie craft.

Then report it on the [ChromieCraft issue tracker](https://github.com/chromiecraft/chromiecraft/issues).
