### ISSUE TITLE
Ulduar Steel Council automatically resets some time after death

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/azerothcore-wotlk#16670]
### Current Behaviour

steelbreaker
runemaster_molgeim
stormcaller_brundir

After all bosses are killed, the Steel Council will automatically reset within a certain period of time

### Expected Blizzlike Behaviour

It takes a week before it resets

### Steps to reproduce the problem

Pass all the bosses, then return to the Steel Council. You will find that it has been reset!

### AC rev. hash/commit

[21cab04]

### Operating system

Ubuntu 20.04

### Custom changes or Modules

Eluna

**Comment by zxnhrdz** [comment]
Enter the raid and keep beating XT-002 Dekonstruktor, then enter the Odur antechamber. There are three bosses in the antechamber, if you only kill boss_assembly_of_iron alone, it will not reset. But if you kill Kologarn or Auriaya first, and then kill assembly_of_iron, boss_assembly_of_iron will automatically reset in an hour or so.

Please focus on testing it! Thanks!

**Comment by kjack9** [comment]
I may take a look at this soon, but I see where the problem is coming from.

When the creatures evade, they are using the `DespawnOnEvade()` function triggered by their CREATURE_FLAG_EXTRA_HARD_RESET creature flag.

https://github.com/kjack9/azerothcore-wotlk/blob/7d3f237f71b2149c9d9758524150a6c27aea2de9/src/server/game/AI/CreatureAI.cpp#L225-L231

Since a respawn delay isn't specified, it defaults to 20 seconds.

https://github.com/kjack9/azerothcore-wotlk/blob/7d3f237f71b2149c9d9758524150a6c27aea2de9/src/server/game/Entities/Creature/Creature.h#L277-L278

`DespawnOnEvade()` calls `DespawnOrUnsummon()`, which immediately despawns the creature but gives it a 20s respawn timer, presumably to let it re-appear. It's notable that this isn't working right - the bosses immediately respawn when I reset the encounter.

Finally, since there is no mechanism to restore the craeture's respawn timers from 20s, they are stuck with the new respawn timer.

I'm not 100% sure what the "right" fix is for this - you almost need to restore the original respawn timer that's been saved somehow. I can do that pretty simply in some CustomData, but that certainly doesn't feel like a proper solution.

I'll sleep on it and see if I can figure out anything tomorrow.

**Comment by kjack9** [comment]
Also possible that the manual respawn that's happening in the boss script is causing this too.

https://github.com/azerothcore/azerothcore-wotlk/blob/4cb25b4b5e057e161d016b58606145a3fa901d57/src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp#L165-L181

**Comment by avarishd** [comment]
CanRespawn() override and check instance data, but probably better to find what is causing it to begin with.

The 20s timer comes from phased reset - https://github.com/azerothcore/azerothcore-wotlk/pull/7828 (was moved to the hard reset flag from hardcode)
