### ISSUE TITLE
Melee creatures attacking from range

### ISSUE THREAD

**Issue by acidion-ad** [azerothcore/azerothcore-wotlk#17543]
### Current Behaviour

When melee based npcs run up to attack they stop a notable distance away and melee from short range

![image](https://github.com/azerothcore/azerothcore-wotlk/assets/85262665/2dc591c4-aa1a-4965-8403-931f0ee9c667)

### Expected Blizzlike Behaviour

Melee should occur standing closer to the target

### Steps to reproduce the problem

Find a melee npc and engage in combat

* Go south from Goldshire and agro a spider/kobold on the way to the mines
* They will run toward you then stop a short distance from you and successfully melee from a notable distance

### AC rev. hash/commit

a39175b

### Operating system

Windows 11

### Custom changes or Modules

None

**Comment by noisiver** [comment]
I can confirm this as being an issue

**Comment by Kitzunu** [comment]
I can't find anything as to why this would happen because the calculations for the melee range are correct. My only guess would be that there is something wrong with 2d/3d range 🤷

**Comment by acidion-ad** [comment]
If there is anything I can do to provide more detail let me know. I'm quite sure this was not a problem the day before. 

From memory, I 

* Deployed a first time fresh build on this pc at revision 39db3de (Oct 18th). 
* No mods, all default worldserver configuration (Only DataDir was set). 
* Fluffed around for an hour as a fresh level warlock human, non-gm account. 
* On the 19th I pulled the above noted revision and cherry picked changes through in the worldserver.conf
* Continued with Warlock fluffing and immediately noticed the ranged melee on the way to mines
* Thought issue might have been caused by adjustments to agro distances and fleeing settings
* Restored worldserver.conf from worldserver.conf.dist 
* Problem persisted

Confirmed today that I was not alone so raised this issue.

In regards to #13630 being closed ~1 year ago I don't know how to tell if it's the same issue with SmartAI. Do the Kobold @Fargodeep mines use SmartAI?

**Comment by Kitzunu** [comment]
it is an issue in general

**Comment by Kitzunu** [comment]
@azerothcore/developers Anyone got a clue where to begin looking? Because I have no idea.

If you go to a creature at max melee range (like the picture above) and do `.dist` you will get exactly 5y (melee range). And if we were going by that then there is no issue here.

So the issue is not with melee range, but with range in general because I think we can all agree on that the image above is way over 5 yards

**Comment by Kitzunu** [comment]
On TC melee range is 2.5y, but I cannot find any differences in melee range calcs

**Comment by AGandrup** [comment]
Yes I have had, what I believe is a fix for this, for awhile. However I never made a PR because I couldn't find any issue at that time and when I asked on discord I got no response, so I thought perhasp I was wrong, and I also kinda forgot about it again. Anyway, the melee range isn't the issue, it has to do with chase movement in TargetedMovementGenerator.cpp. Right now when you aggro a creature it will stop its chasing when it reaches **exactly** max melee range, and yes it is as big as shown in the picture above. This also causes "laggy" running behaviour, especially for creatures that runs faster than you do, for example guards.

The fix is that chasing creature must predict the chase destination in order to keep up with its target - in order words, it must aim for a step ahead of its target. That way when the target stop moving it will continue running for a few steps before stopping, so it doesn't (always) stop at max melee range. There will still be cases where it might stop at max melee range, for example if you stand still and a mob patrols into you and aggro. But I do think that is correct behavior - but that can be up to discussion. It is all handled in the same file.

**Comment by heyitsbench** [comment]
Classic at least definitely has movement think a step ahead as you say, not sure about 3.3.5. It can easily be observed with high ping, can be quite difficult to move enemies around.

**Comment by Kitzunu** [comment]
Oh so I was on the right path when I was looking into it. This makes me marginally happier after wasting time and banging my head on the table for hours

**Comment by Kitzunu** [comment]
Feel free to PR it, and in future if you have questions just ping me in discord :D

**Comment by AGandrup** [comment]
Sure, I'll do that. Will upload some videos as well to show current and new behaviour. Then it can be discussed.
