### ISSUE TITLE
Regression: Stranglethorn Fishing Extravaganza Times

### ISSUE THREAD

**Issue by SuzumiK** [azerothcore/azerothcore-wotlk#18207]
### Current Behaviour

The Stranglethorn Fishing Extravaganza starts too late (5 pm).

### Expected Blizzlike Behaviour

The expected event timings are:

1 pm: Crew appears
2 pm: Pools appear, turn-ins possible

### Steps to reproduce the problem

```
use acore_world; select * from `game_event` where `eventEntry` in (14, 15, 62, 90);
``` 

### Extra Notes

This was fixed before:

* https://github.com/azerothcore/azerothcore-wotlk/issues/9532
* https://github.com/azerothcore/azerothcore-wotlk/pull/6201

I found relevant queries in archive/db_world/8.x/2022_10_20_01.sql, but archive does not seem to be applied?

The following sql fixed it for me (adapted from https://github.com/azerothcore/azerothcore-wotlk/pull/6201/commits/12b88383e5568cd1f358b1bd7ff8bbe809bbd100 to include turn-ins):

```sql
USE `acore_world`;

SET @ANNOUNCE = 14;
SET @FISHING_POOLS = 15;
SET @CREW = 62;
SET @TURN_INS = 90;
UPDATE `game_event` SET `start_time` = '2016-10-29 00:00:00' WHERE `eventEntry` = @ANNOUNCE;
UPDATE `game_event` SET `start_time` = '2016-10-30 13:00:00' WHERE `eventEntry` = @CREW;
UPDATE `game_event` SET `start_time` = '2016-10-30 14:00:00' WHERE `eventEntry` IN (@FISHING_POOLS, @TURN_INS);

```

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/c863a8cfb59ed17692f9da2956b85a53ecc09ed7

### Operating system

Windows 10 x64

**Comment by sudlud** [comment]
It looks like an maybe error was made on DB squish 8.0 (785bb5ed6) which contains the wrong starting time:

https://github.com/azerothcore/azerothcore-wotlk/blob/785bb5ed6b2de97ed463b65d8a4503cdc54b4c9d/data/sql/base/db_world/game_event.sql#L96

Although at this squash the sql update file you mentioned was moved from updates to archive:

https://github.com/azerothcore/azerothcore-wotlk/blob/785bb5ed6b2de97ed463b65d8a4503cdc54b4c9d/data/sql/archive/db_world/8.x/2022_10_20_01.sql

so the changes made in this file should have been included in the updated base sql files after the squish.

---

I've compared the values with commit e7cbc80a9 (right before the sqish 8.0).

The start date for event 62 was:
2016-10-30 14:00:00 (game_event.sql before squish @ e7cbc80a9 )
2016-10-30 13:00:00 (2022_10_20_01.sql @ e7cbc80a9 )
2016-10-30 16:00:00 (squish 8.0 @ 785bb5ed6)

👀

**Comment by Kitzunu** [comment]
Just fix it, no need to try figuring out what happened. The rest is history

**Comment by sudlud** [comment]
Im just trying to understand what went wrong so we don't have to unnecessarily fix the same things twice. And values randomly changing on a squish really feels very wrong to me and also prompts the question "what else might have been wrong in that squish?".

The starting time is e.g. also correct in the 8 year old DB, so this is at least the second time this was broken.

**Comment by Kitzunu** [comment]
My guess is that for some reason a clean up to date db was not used

**Comment by mercuryjlt** [comment]
Just experienced this issue today. 2PM server time and no Fishing Extravaganza. I applied the SQL in the OP (slightly modified to just ahead of current server time), restarted the world server and the Crew and Pools spawned as expected. Server installed about 2 months ago, so at least for me, this still seems to be an issue with new installs.

**Comment by Mondrethos** [comment]
This is also still an issue for us.

**Comment by Vortikai** [comment]
Still happening a few hours late as of this post rev. 4d380b987b2c. Mercury is right in that the proper test for this probably is having a clean/dropped world db

**Comment by CheckYourFax** [comment]
Still an issue here. I check the db and the times are wrong.

My database was created about 3 weeks ago, so some sql update is reverting it back from the correct base database install: 

https://github.com/azerothcore/azerothcore-wotlk/blob/a9e125b3f67e947670c49f5a31a8c3cdbaab6e2c/data/sql/base/db_world/game_event.sql

I can't find which sql update does it though. Someone should look into the sql update folder to see what is causing it.

```
mysql> SELECT eventEntry, description, start_time, end_time 
    -> FROM game_event 
    -> WHERE eventEntry IN (14, 15, 62, 90);
+------------+--------------------------------------------------+---------------------+---------------------+
| eventEntry | description                                      | start_time          | end_time            |
+------------+--------------------------------------------------+---------------------+---------------------+
|         14 | Stranglethorn Fishing Extravaganza Announce      | 2016-10-29 02:00:00 | 2030-12-31 08:00:00 |
|         15 | Stranglethorn Fishing Extravaganza Fishing Pools | 2016-10-30 15:00:00 | 2030-12-31 08:00:00 |
|         62 | Stranglethorn Fishing Extravaganza - The Crew    | 2016-10-30 14:00:00 | 2030-12-31 08:00:00 |
|         90 | Stranglethorn Fishing Extravaganza - Turn-ins    | 2016-10-30 15:00:00 | 2030-12-31 08:00:00 |
+------------+--------------------------------------------------+---------------------+---------------------+
4 rows in set (0.00 sec)
```


SQL command above fixes it.

**Comment by CheckYourFax** [comment]
Just a hunch: Could the issue be partly related to DST? On Sunday, October 30, 2016 at 3:00 AM DST ends, so maybe something is going on there? Maybe the event manager is shifting the event time an hour because the initial start date happened to be non-DST but in CEST we currently are in DST?

<img width="485" height="118" alt="Image" src="https://github.com/user-attachments/assets/dc762dd2-ac24-43d2-a361-afe43aa2e8e9" />

Seems to confirm this suspicion. event id 14 start date is inside DST (before october 30, 2016 3AM). event id 15 is non-DST. See how the state change hour is shifted?

Holidays already use a proper calendar driven code path, why not other events too? Using absolutes without using an absolute time standard (UTC) is a problem.


It would explain why the event starts 2 hours late:
1) The database has the event start date at 15:00
2) The absolute timestamp and occurrence caused another 1 hour shift to 16:00. 


The first fix is simple, provide a conditional database update .sql to fix the database start time (since it doesn't seem to affect everyone).
The second fix would require to either 1) exclusively use UTC and not localtime, even if the system has a DST-enabled timezone set, or 2) move the DB driven events to also use the same code path holidays use, which do account properly for DST.

For now the only workaround is to make the OS use a timezone which does not have any form of DST.

**Comment by CheckYourFax** [comment]
Found another problem and the main cause of all problems:

```mysql> DESCRIBE game_event;
+--------------+------------------+------+-----+---------------------+-------+
| Field        | Type             | Null | Key | Default             | Extra |
+--------------+------------------+------+-----+---------------------+-------+
| eventEntry   | tinyint unsigned | NO   | PRI | NULL                |       |
| start_time   | timestamp        | YES  |     | 2000-01-01 18:00:00 |       |
| end_time     | timestamp        | YES  |     | 2000-01-01 18:00:00 |       |
| occurence    | bigint unsigned  | NO   |     | 5184000             |       |
| length       | bigint unsigned  | NO   |     | 2592000             |       |
| holiday      | int unsigned     | NO   |     | 0                   |       |
| holidayStage | tinyint unsigned | NO   |     | 0                   |       |
| description  | varchar(255)     | YES  |     | NULL                |       |
| world_event  | tinyint unsigned | NO   |     | 0                   |       |
| announce     | tinyint unsigned | NO   |     | 2                   |       |
+--------------+------------------+------+-----+---------------------+-------+
```

Since the event manager uses local time everywhere, and events should all be using the server's wall-clock, using TIMESTAMP is a horrible idea, because when you insert a date from an .sql into a TIMESTAMP type, MySQL converts it into UTC. This means the real stored values are not the same as originally intended by the database INSERT if the .sql was ran on a server that was not originally using UTC. If a server then converts their system time to UTC, you will notice all entries have their times shifted and are not the same as the original .sql.

The best fix is to stop using TIMESTAMP and convert the column type to DATETIME (and update all the values with correct times to fix affected servers) , because MySQL won't do any timezone conversion shenanigans with DATETIME since all this stores are literal digits. Whether you're in Canada or in India, the stored (and read) value will always be the originally intended time, because hey, events want to use the server's wall clock right?!

To fix the other issue, the event manager's logic needs to be fixed to properly account for when start_time is not DST, but local time is DST, or vice versa.
