### ISSUE TITLE
[Quest] Jack Likes His Drink

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/azerothcore-wotlk#1854]
While doing quest, NPC takes money for it, but never provider furter service to complete quest.
6 players confirmed it on server so far.

.quest add 11466
.tele HowlingFjord

Commit: Up to date.

**Comment by sluggor** [comment]
I have been able to reproduce this. I can take this one unless someone else is already on it.

**Comment by sluggor** [comment]
This was an interesting one, because it's raising questions about the integrity of the database. Olga's character_template entry gossip menu was correct, but the smart_scripts table had a different menu id, and that mismatch was causing the sequence to stop abruptly.

Jack had the wrong menu id in the character_template *and* the smart_scripts table, causing weirdness like this...

![jacks_crazy](https://user-images.githubusercontent.com/50815505/58288604-f90d9b00-7d68-11e9-9ad7-352efeb588d9.jpg)

So that's all been fixed up, but I wonder *why* they were wrong, and how many others might be mismatched as well.

Here's the fix...

```SQL
USE `acore_world`;

-- Olga's gossip menu needs to be corrected in smart_scripts to register user selection

UPDATE `smart_scripts` SET `event_param1` = 9014 WHERE `entryorguid` = 24639 AND `source_type` = 0 AND `id` = 0;

-- Jack had the wrong gossip_menu_id in his creature_template entry

UPDATE `creature_template` SET `gossip_menu_id` = 9013 WHERE `entry` = 24788;

-- Jack needs the corresponding correction to smart_scripts so the debt item can be placed in character's inventory

UPDATE `smart_scripts` SET `event_param1` = 9013 WHERE `entryorguid` = 24788 AND `source_type` = 0 AND `id` = 3;
```

**Comment by poszer** [comment]
> This was an interesting one, because it's raising questions about the integrity of the database. Olga's character_template entry gossip menu was correct, but the smart_scripts table had a different menu id, and that mismatch was causing the sequence to stop abruptly.
> 
> Jack had the wrong menu id in the character_template _and_ the smart_scripts table, causing weirdness like this...
> 
> ![jacks_crazy](https://user-images.githubusercontent.com/50815505/58288604-f90d9b00-7d68-11e9-9ad7-352efeb588d9.jpg)
> 
> So that's all been fixed up, but I wonder _why_ they were wrong, and how many others might be mismatched as well.
> 
> Here's the fix...
> 
> ```sql
> USE `acore_world`;
> 
> -- Olga's gossip menu needs to be corrected in smart_scripts to register user selection
> 
> UPDATE `smart_scripts` SET `event_param1` = 9014 WHERE `entryorguid` = 24639 AND `source_type` = 0 AND `id` = 0;
> 
> -- Jack had the wrong gossip_menu_id in his creature_template entry
> 
> UPDATE `creature_template` SET `gossip_menu_id` = 9013 WHERE `entry` = 24788;
> 
> -- Jack needs the corresponding correction to smart_scripts so the debt item can be placed in character's inventory
> 
> UPDATE `smart_scripts` SET `event_param1` = 9013 WHERE `entryorguid` = 24788 AND `source_type` = 0 AND `id` = 3;
> ```

I don't think so that is correct fix. It should look like this : 

![First](https://user-images.githubusercontent.com/41213210/58289049-955d8f00-7db5-11e9-998e-78efb683a8a4.png)
![second](https://user-images.githubusercontent.com/41213210/58289053-97bfe900-7db5-11e9-8d72-650dc15d8ace.png)
![third](https://user-images.githubusercontent.com/41213210/58289057-9abad980-7db5-11e9-84cb-71b27374bdcf.png)
![fourth](https://user-images.githubusercontent.com/41213210/58289064-9d1d3380-7db5-11e9-97b3-47557696e8f5.png)
![five](https://user-images.githubusercontent.com/41213210/58289068-9f7f8d80-7db5-11e9-9850-62aea8102711.png)
![six](https://user-images.githubusercontent.com/41213210/58289090-ad351300-7db5-11e9-9f39-5e85eab15aa9.png)
![seven](https://user-images.githubusercontent.com/41213210/58289107-baea9880-7db5-11e9-980b-04a2cc21167e.png)
![eight](https://user-images.githubusercontent.com/41213210/58289109-bd4cf280-7db5-11e9-952d-499c5f85e0a4.png)

**Comment by sluggor** [comment]
My apologies, I was just showing what it looked like with the wrong menu ids. I have fixed that and it does indeed look like your images now. I was able to get his debt and turn in the quest successfully.

**Comment by poszer** [comment]
> My apologies, I was just showing what it looked like with the wrong menu ids. I have fixed that and it does indeed look like your images now. I was able to get his debt and turn in the quest successfully.

Np, it's okay. You can watch the old video here : 
https://www.youtube.com/watch?v=fk6gbalyNr4

**Comment by sluggor** [comment]
Hey, by the way, I notice that when you create PRs for your SQL changes, you're putting them in a pending directory with what looks like a timestamp, for example...

`data/sql/updates/pending_db_world/rev_1558616423152525700.sql`

Is that how I should make database fixes available?  Where is the number string coming from?

Thanks.

**Comment by poszer** [comment]
> Hey, by the way, I notice that when you create PRs for your SQL changes, you're putting them in a pending directory with what looks like a timestamp, for example...
> 
> `data/sql/updates/pending_db_world/rev_1558616423152525700.sql`
> 
> Is that how I should make database fixes available? Where is the number string coming from?
> 
> Thanks.

Yes, in your fork (AC folder) \data\sql\updates you have these (image below):

![Screenshot_1](https://user-images.githubusercontent.com/41213210/58289578-2b45e980-7db7-11e9-8720-0d50d5d7d25d.png)
If you want for example to post fix which belong to `world` db, you will open  `pending_db_world` folder, and inside you have shell script called `create_sql` -> When you run it, it will generate the .sql file for example `rev_1558616423152525700.sql` --> Open it, end place there your fix, push -> Done :D
P.S. Always leave first row how it's generated, don't delete it. : 
INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1558616423152525700');

Giving you here a little example from your fix posted:

```sql
INSERT INTO `version_db_world` (`sql_rev`) VALUES ('1558616423152525700');

-- Olga's gossip menu needs to be corrected in smart_scripts to register user selection
UPDATE `smart_scripts` SET `event_param1` = 9014 WHERE `entryorguid` = 24639 AND `source_type` = 0 AND `id` = 0;

-- Jack had the wrong gossip_menu_id in his creature_template entry
UPDATE `creature_template` SET `gossip_menu_id` = 9013 WHERE `entry` = 24788;

-- Jack needs the corresponding correction to smart_scripts so the debt item can be placed in character's inventory
UPDATE `smart_scripts` SET `event_param1` = 9013 WHERE `entryorguid` = 24788 AND `source_type` = 0 AND `id` = 3;

```

**Comment by sluggor** [comment]
Got it. Thanks again!
