### ISSUE TITLE
Wrong Auctionhouse name in mail

### ISSUE THREAD

**Issue by V-Cyberpunk** [azerothcore/azerothcore-wotlk#18772]
### Current Behaviour

Buy something in AH e.g. in Darnassus and in mail title is not the correct AH name.
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/44802344/b9e400ee-fd95-46dc-8903-9e77a7d7ba81)

### Expected Blizzlike Behaviour

Should be in this case Darnassus in mail title from AH. In other cities is this problem, too.

### Steps to reproduce the problem

buy something in ah and look in mail

### AC rev. hash/commit

53864433888c

### Operating system

Debian 12 x64

### Custom changes or Modules

BreakingNewsOverride
ExtendedXP
mod-1v1-arena
mod-account-achievements
mod-account-mounts
mod-ah-bot
mod-anticheat
mod-autobalance
mod-boss-announcer
mod-duel-reset
mod-dynamic-xp
mod-eluna
mod-emblem-transfer
mod-gain-honor-guard
mod-instance-reset
mod-learn-spells
mod-npc-beastmaster
mod-npc-buffer
mod-npc-enchanter
mod-pvp-titles
mod-rdf-expansion
mod-reagent-bank
mod-solocraft
mod-solo-lfg
mod-starter-guild
mod-TimeIsTime
mod-transmog
mod-weekend-xp
mod-world-chat
ReusablePotion

**Comment by Kitzunu** [comment]
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/d897110a-7ced-475d-a2e9-b145fd1fae04)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/24550914/7a27bf9a-d978-445b-bff4-d600492de29e)

This is because in WotLK there are only 3 auctionhouses. Alliance, Horde, and Blackwater (Booty Bay)
