### ISSUE TITLE
Docker WSL: Modules won't import SQL data

### ISSUE THREAD

**Issue by gruselgg** [azerothcore/azerothcore-wotlk#18965]
### Current Behaviour

I can't seem to figure this one out. I installed AzerothCore via Docker on Windows 10 using WSL. Things seemed to run fine, docker images are running, I can connect with a client, create characters, run around, use in-game commands and everything.

Then I tried to install the basic [skeleton module](https://github.com/azerothcore/skeleton-module) and after a few tweaks to the file names I got it to compile. But for some reason it just won't import the sql data (in this case the hello world acore string). I then tried different mods, and all seem to be suffering from this. No imports to the database. Therefore no mod seems to be working.

Here you can see the [ac-worldserver logs](https://gist.github.com/gruselgg/12cfb9c4cf63aa33888cd2c06d58d106).

Errors I discovered so far:
- When logging in with a character: In the ac-worldserver console I get `Acore string entry 35410 not found in DB.` (ac-worldserver logs last line)
- When logging in with a character: In-game I get the message `<error>` in the chat
- When starting the docker containers i get in the ac-worldserver `Can't set process priority class, error: Permission denied` right at the start (ac-worldserver logs line 24)

I'm not sure the last error is relevant to this problem, but it seems off.

### Expected Blizzlike Behaviour

Modules should work.

### Steps to reproduce the problem

1. Install AzerothCore via Docker and WSL on Windows 10.
2. Add a module (like the basic skeleton module) and compile again.
3. Log in with a character and see errors in ac-worldserver console and in-game.

### Extra Notes

Things I tried:
- Applying fixes from #92
- Changing file permissions
- Using/not using `sudo` and checking user groups
- Reinstalling

### AC rev. hash/commit

AzerothCore rev. 46aed4dec768+ 2024-05-28 06:44:38 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Windows 10

### Custom changes or Modules

- [skeleton module](https://github.com/azerothcore/skeleton-module)

**Comment by Kitzunu** [comment]
isn't there a general issue for SQL files in modules not being able to be loaded, or was that fixed? I can't recall

**Comment by michaeldelago** [comment]
> isn't there a general issue for SQL files in modules not being able to be loaded, or was that fixed? I can't recall

kinda? I had this open a while back. https://github.com/azerothcore/azerothcore-wotlk/pull/16157. General consensus was to ultimately let the user manage SQL for modules.

otherwise though, docker doesn't mount SQL from modules because it's a difficult to copy only the SQL into the container. To get around this, you can copy SQL files into the appropriate dir at `data/sql/custom` and the database import should pick it up.

**Comment by ben-of-codecraft** [comment]
I read through the issues around this and have encountered it myself now.  It seems the native way it works if you do not run in a docker container is for it to pick up modules sql code if it is at 'modules/name/data/sql'. But because the way docker relies on the db-import container, the modules have to be managed manually. 

Someone mentioned some would have issues if it was fixed to run the queries automated, similar to how the non docker version works.  Ideally, I think it would be better to have consistency between the two. 

So what are the thoughts on just fixing the issue  SQL statements automatically run for modules in db-import or at least being able to allow them to be run automatically if set in configuration for dbimport?

**Comment by ben-of-codecraft** [comment]
I put the solution I ended up with on the discord support. 
https://discord.com/channels/217589275766685707/1280317898140680307
