### ISSUE TITLE
boss_krikthir_the_gatewatcher.cpp does not work properly

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#1939]
boss_krikthir_the_gatewatcher.cpp does not work properly

##### SMALL DESCRIPTION:

boss_krikthir_the_gatewatcher.cpp does not work properly, upon engaging him all his minions are engaged too quickly

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Minions/Watchers should engage in longer timers after the event starts

##### CURRENT BEHAVIOUR:

boss_krikthir_the_gatewatcher.cpp does not work properly, upon engaging him all his minions are engaged too quickly, causing low geared 5 mans to wipe.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go To AzJol Nerub
2.  Engage First Boss
3.  Profit

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

latest

##### OPERATING SYSTEM:

ubuntu 16.04

##### MODULES:

none

**Comment by FrancescoBorzi** [comment]
Please do NOT just put "latest" as with time it will no make sense and we won't have trace about when the bug was actually found. Please put your actual commit hash value.

**Comment by Selyria** [comment]
Yes I can confirm can lead quite quickly to a wipe

AzerothCore Video https://youtu.be/uGe6S5krybg

AzerothCore rev. f47c2d2f8c23+ 2019-06-03 05:30:11 +0000 (master branch) (Win64, Release)

EXPECTED BLIZZLIKE BEHAVIOUR:

The Event Edit
The boss is guarded by three groups of three spiders. The pulls are successive, meaning that once you pull the first group an event has started. Sometimes you can catch a break between groups to drink if you are able to kill them fast enough. There is no break before the boss is pulled.

Each pull consists of a miniboss and two adds. In addition to the constant risk of Anub'ar Skirmishers and Web Wrap, each miniboss has a special ability: from left to right these are:

Left: A poison spit that hits targets in a cone; it is ideal for the tank to face this boss away from the party, but given the chaos of the fight this is not always possible. The group can eat the damage.

Middle: A blast of webs that hits targets in a cone and disorients everyone for about three seconds. Beware of drops in healing and aggro.

Right: Attacks rapidly as through dual wielding with a Frenzy-style effect. Be prepared for massive incoming damage.

Some groups have an Anub'ar Skirmisher, which will drop aggro during the fight and focus on a random party member, becoming immune to taunt and CC, so they should be killed first. Throughout these pulls a random party member will become encased in webbing which needs to be attacked in order to free them. It's helpful to have one party member keeping a lookout for this. A good way to handle this encounter is to start with the furthest left group and pull them back into the hall a bit, giving the mana-users time to drink when the second group aggroes.

**Comment by Voxstrasza** [comment]
Still an issue as of `37d1f2be4729`

**Comment by Ragelezz** [comment]
Besides the groups spawned too close (im at irl work atm so just checked the code) is the fight itself working accordingly ? If anybody knows, ofc, atm the script itself has around 200 lines and those guardian-adds don't seem to do too much, if they have SAI (didn't checked) that db scripts needs to be merged into c++ file.
