### ISSUE TITLE
Battle for Mount Hyjal - Azgalor not dropping loot after being killed by npcs after the raid group all died.

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#1981]
Battle for Mount Hyjal - Azgalor not dropping loot

##### SMALL DESCRIPTION:

Battle for Mount Hyjal - Azgalor not dropping loot after being killed by npcs after the raid group all died.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Azgalor should still drop loot even if npcs were left to kill him, when the raid died.

##### CURRENT BEHAVIOUR:

Azgalor should still drop loot even if npcs were left to kill him, when the raid died.
![azgalor no loot](https://user-images.githubusercontent.com/18629476/59677224-ef5a4480-91fb-11e9-86ef-64884ccf6a89.jpg)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Do a raid go to Battle for Mount Hyjal 
2. Kill all previous bosses before Azgalor 
- Rage Winterchill
- Anetheron
- Kaz'rogal
3. Start encounter with Azgalor
4. Try to almost kill azgalor, kill yourself and let the npcs help u kill azgalor
5. no loot

##### EXTRA NOTES:

still researching on this, i am not 100% if its a bug or not. Maybe a player is required to last hit the boss? or one player needs to be alive by the end

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

AzerothCore rev. 97e65bd

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment]
[Infos](https://www.engadget.com/2007/05/30/blizz-responds-to-hyjal-bugs/)

NPCs killing Bosses 

Hyjal is a zone that has you fighting along side Jaina, Thrall and their Alliance and Horde forces against the invading armies of the Burning Legion. The NPCs can be a big help when fighting the Legion. They provide the raid with a supplementary source of damage, and occasionally even tank a Ghoul or Abomination for you. This is great, except for one case. If your raid attacks one of the bosses, then damages the boss to a very low health amount, the NPCs can continue on with the fight and finish the boss even if the raid has wiped out. Thrall is particularly good at this, as he has an immense amount of health and summons Dire Wolves to help him. This is a problem because the raid can lose tap on the boss while they are all dead. **This then means the raid can no longer loot the boss**. The raid at this point can also not retry the encounter, as the death of the boss has moved the zone's progress further. The raid can continue on and fight another boss, and eventually even Archimonde, but that **loot is no longer available** for that week.

**Comment by spinzaku** [comment]
Thank you @poszer

**Comment by poszer** [comment]
The informations that i share in previous comment are blizz behaviour. Closing this issue
