### ISSUE TITLE
[Creature Spell] creature_template_spell "index" = 0 will not appear and work

### ISSUE THREAD

**Issue by kissingers** [azerothcore/azerothcore-wotlk#20149]
### Current Behaviour

creature_template_spell "index" = 0 will not appear and work.
the creature 25653, if you try control the blue dragon and see the spell, the index 0 spell in Database will not appear
but if change index big than 0, such as 4, will appear. the bug about 2 month. and before all ok.

### Expected Blizzlike Behaviour

N/A

### Steps to reproduce the problem

.go c 55066
fight with the boss kljd and wait 2m, try control the blue dragon and see the spell, the index 0 spell in Database will not appear

### AC rev. hash/commit

AzerothCore rev. 01b86ec7a6c9 2024-10-04 11:01:36 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 0.
服务器运行时间: 45 second(s)
Update time diff: 100ms. Last 38 diffs summary:
|- Mean: 101ms
|- Median: 100ms
|- Percentiles (95, 99, max): 101ms, 133ms, 152ms
Using SSL version: OpenSSL 3.0.14 4 Jun 2024 (library: OpenSSL 3.0.14 4 Jun 2024)
Using Boost version: 1.74.0
Using CMake version: 3.25.1
Using MySQL version: 80402
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 6.8.12-1-pve
Worldserver listening connections on port %u
Realmlist (Realm Id: 3) configured in port 54347
VMAPs status: Enabled. LineOfSight: true, getHeight: true, indoorCheck: true
MMAPs status: Enabled
maps directory located in /root/wow3/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow3/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow3/bin/mmaps. Total size: 2192911264 bytes
Default DBC locale: zhCN.
All available DBC locales: zhCN 
Using World DB: ACDB 335.12-dev
Latest LoginDatabase update: 2024_01_20_00.sql
Latest CharacterDatabase update: 2024_09_22_00.sql
Latest WorldDatabase update: mod-zone-difficult.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
List of enabled modules:
|- mod-difficult
|- mod-eluna

### Operating system

Debian 12 with PVE

**Comment by kissingers** [comment]
I tested other creature, if control by player, will not appear index 0 spell and replaced will normal attack ico

**Comment by heyitsbench** [comment]
I suspect a result of https://github.com/azerothcore/azerothcore-wotlk/commit/887495386246a0a282edfbd83ec3816d353632aa in some manner.

**Comment by kissingers** [comment]
Might index 0 even if AddSpellToActionBar(spellInfo, ACT_PASSIVE, 0), will always replace by client with normal meel attack?

**Comment by kissingers** [comment]
or here ACT_DISABLED problem?
 if (PetActionBar[i].IsActionBarForSpell() && sSpellMgr->GetFirstSpellInChain(action) == first_id)
            {
                SetActionBar(i, 0, ACT_DISABLED);
                return true;
            }

**Comment by Nefertumm** [comment]
The following code initializes the command attack action in the index 0 always for most of the creatures (unless the ones you add in the switch you previously used) because that method is called multiple times throughout without a parameter (making the parameter true as default).
https://github.com/azerothcore/azerothcore-wotlk/blob/d340ae029b19c5c8ddfa61f0bb0d4725234f3452/src/server/game/Entities/Unit/CharmInfo.cpp#L67-L75

Since now, the creatures have an action already in index 0, the following code will prevent the spell from being correctly added to the action bar:
https://github.com/azerothcore/azerothcore-wotlk/blob/d340ae029b19c5c8ddfa61f0bb0d4725234f3452/src/server/game/Entities/Unit/CharmInfo.cpp#L187-L188

Also, the pr added a possible segmentation fault by dereferencing a null pointer here
https://github.com/azerothcore/azerothcore-wotlk/blob/d340ae029b19c5c8ddfa61f0bb0d4725234f3452/src/server/game/Entities/Unit/CharmInfo.cpp#L190

Maybe the solution is either initializing the empty action bar with the parameter withAttack = false for entries that have index = 0 or something like that.
