### ISSUE TITLE
Player::addTalent does not properly update m_usedTalentCount

### ISSUE THREAD

**Issue by FingerKnoten** [azerothcore/azerothcore-wotlk#20231]
### Current Behaviour

Since Player::addTalent does not properly update m_usedTalentCount this causes a wrong state of the player talent representation. This will be fixed with a relogin so only rare cases where this becomes an issue.
E.g. if talents are added using Player::addTalent and then, without relogging, someone tries to reset the talents. This will not work.

### Expected Blizzlike Behaviour

Talents that have been added with addTalent should be able to reset without relogging.

### Steps to reproduce the problem

1. Add talents using Player::addTalent
2. Try to reset talents (Do not relog in between step 1 and 2)

### AC rev. hash/commit

na

### Operating system

Windows 11, Ubuntu 22.04

**Comment by sogladev** [comment]
I ran into this issue while working on [mod-npc-talent-template](https://github.com/azerothcore/mod-npc-talent-template) where [`addTalent` is used to learn talents](https://github.com/sogladev/mod-npc-talent-template/blob/2fa441066f250653c7cb547d2032ecb1f4e4c2c7/src/TemplateNPC.cpp#L79)

Not allowing to reset talents is indeed due to `m_usedTalentCount` not being incremented by `addTalent`, so `m_usedTalentCount` remains at 0
https://github.com/azerothcore/azerothcore-wotlk/blob/7abbca0f5b4ab3a15d78db7ec40e3b4358bed7da/src/server/game/Entities/Player/Player.cpp#L3697 

I can reproduce/test with the module. You'll need [my fork with `pr-test-add-talent` branch](https://github.com/sogladev/mod-npc-talent-template/tree/pr-test-add-talent). 

the module auto imports SQL needed

gear must be destroyed and talents reset before applying talents 
1. level 80
1. `.npc add 55009`
1. reset talents
1. observe it doesn't work unless reloading
