### ISSUE TITLE
[DK Starter Chain Quest] Bloody Breakout is optional.

### ISSUE THREAD

**Issue by Rorschach91** [azerothcore/azerothcore-wotlk#20834]
### Current Behaviour

The quest Bloody Breakout is optional on AC, so the players can unlock the quest A Cry For Vengeance! simply delivering the quest The Path Of The Righteous Crusader.

### Expected Blizzlike Behaviour

Bloody Breakout is not optional. 
Bloody Breakout and The Path Of The Righteous Crusader quests must be delivered both to unlock the quest A Cry For Vengeance!

### Source

Cata Classic Live

### Steps to reproduce the problem

1. Start the quests The Path Of The Righteous Crusader and Brothers In Death.
2. Complete and deliver The Path Of The Righteous Crusader without delivering Brothers In Death or Bloody Breakout.

### Extra Notes

Probably the quests Brothers In Death and Bloody Breakout are optional on AC for some bugs during the Koltira Deathweaver's event. 

### AC rev. hash/commit

[97937d1](https://github.com/azerothcore/azerothcore-wotlk/commit/97937d1724668b4c3d5b0779ff42a23886cd9f01)

### Operating system

Windows 11

**Comment by TheSCREWEDSoftware** [comment]
Correct me if wrong since you tested in Cata.

You get `Brothers In Death` and go to the keep, kill the guard and talk to the npc delivering the quest.

You now get `Blood Breakout`, defend the guy and kill the inquistor (this quest has a PR open better mechanic for that quest).

After you kill the inquistor you get his head and than you can delivery it back where you got `Brothers in Death` (in the house if not mistaken) than you will `A Cry For Vengeance!` That's how the chain should be if not mistaken.

I think the optional one is `The Path Of The Righteous Crusader`

**Comment by TheSCREWEDSoftware** [comment]
See [here](https://youtu.be/B21NbuUlinw?si=Bs5IFmy54SEkky0d&t=2498) at 41:38 he delivers first `Blood Breakout` giving him `A Cry For Vengeance!` and he still has the `The Path Of The Righteous Crusader` to deliever

**Comment by Rorschach91** [comment]
> See [here](https://youtu.be/B21NbuUlinw?si=Bs5IFmy54SEkky0d&t=2498) at 41:38 he delivers first `Blood Breakout` giving him `A Cry For Vengeance!` and he still has the `The Path Of The Righteous Crusader` to deliever

So something has changed during Cataclysm Classic. Thank you dude. I can close the issue.
