### ISSUE TITLE
[Creature Leash] - Gnolls behaviour in Westfall has longer leash than intended

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/azerothcore-wotlk#20859]
Issue linked from CC: https://github.com/chromiecraft/chromiecraft/issues/7576

Triage Notes: Since they got social aggro they will continue to be aggro until the caller that got aggro leashes. Which it doesn't in this case.

Similiar to this: https://github.com/azerothcore/azerothcore-wotlk/issues/20786

Original Post Below: 

---

### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

1-19

### Current Behaviour

Follow range was at least five times longer than usual for these Riverpaw Scouts and Mongrels.
They started all the way from those trees in attached picture.
And if you see the video, im certain that they shouldnt even have been close to the road where the leash should have reset. They should (mob units has many times for me) let go long before that.
And they even crossed it and followed for an even longer distance still.

### Expected Blizzlike Behaviour

Leash range should release about 1/4th-1/5th of the way that they actually followed me.

### Source

None

### Steps to reproduce the problem

Follow the same steps I did in video.

1. Aggro riverpaw gang in accordande to video linked.
2. Run south. They should release aggro before they even crossed the road.
3. They continued alot further than the road and was approximately 4-5 times longer than usual aggro range.

### Extra Notes

Video link:
https://drive.google.com/file/d/1ckI5OJOWI52H918T5rduWjVYhjJq878m/view?usp=drive_link

Image link:
https://drive.google.com/file/d/12IbUs05UIl98wHXDAMWckRYgXy1T1k1G/view?usp=drive_link

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8c3c75122162c56ae3d73386206077ec23b7683e

### Operating system

Ubuntu 22.04

### Modules

- [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
- [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
- [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-costumes](https://github.com/azerothcore/mod-costumes)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by sihensel** [comment]
This applies to all mobs, not just the Gnolls in Westfall.
When a mob damages the player, it resets the leash timer, which causes mobs that can continually hit the player (i.e. meelee ones) to never leash off and chase the players across the zone. Combine this with the daze mechanic and mobs will chase you relentlessly until you are dead.
This is why casters leash off pretty quickly if you run away - they try to cast, you outrange the spell's maximum range, they run after you until they leash off, because the leash timer runs out since they can't deal damage to you.
The same applies to when the player is mounted - you can simply outrun the mob, it can't deal damage, the leash timer runs out and the mob resets.
The only thing that should extend the leash timer are actions by the player that generate aggro/threat, such as dealing damage via attacks/spells, healing/shielding or CC, but it seems like any damage a mob does to the player also reset the leash timer, which should not be the case.

**Comment by heyitsbench** [comment]
> The only thing that should extend the leash timer are actions by the player that generate aggro/threat, such as dealing damage via attacks/spells, healing/shielding or CC

Healing/shielding should not reset the leash timer. If the mob attacks while standing still (details hazy, haven't done a crazy amount of testing myself) it should also reset the leash timer, but this threshold is not correct on AC currently.

**Comment by sihensel** [comment]
Just did some quick tests on the Classic WoW realms with a Paladin:
If you just run away, the mob instantly resets once it reaches its max leash range (which is relatively small), even when using Retribution Aura.
If you slowly walks backwards and stop regularly, to let the mob catch up and hit you, you can extend the leash range by a bit, but even then the mob resets eventually and runs back.
Either way, mobs never chase the player across the entire zone if the player does not actively cause damage/aggro.

> Healing/shielding should not reset the leash timer.

Thats for pointing that out, I could observe this as well.

**Comment by heyitsbench** [comment]
> max leash range

For the vast majority of mobs, this isn't a thing. They use a timer for their leash, only 12-15 seconds for practically all vanilla mobs, but it has nothing to do with distance. This isn't the case for iirc some worldbosses since they wanted them to have boundaries so people couldn't take, e.g., Kazzak to Stormwind anymore.

[This video](https://www.youtube.com/watch?v=xnrUkbEbiJk) has a lot of information regarding leash behavior on Classic (i.e. what we're aiming to emulate).

**Comment by heyitsbench** [comment]
Correction to my comment, there is a small range surrounding their either spawn or pull point where they will not leash no matter what, but that isn't what you were referring to.

**Comment by sihensel** [comment]
Thanks for linking the video, this is very insightful!

>  there is a small range surrounding their either spawn or pull point where they will not leash no matter what, but that isn't what you were referring to

That's what I was referring to, and I confused it as a "leash range" which apparently does not seem to exist, as long as you leave that small circle where they never leash off.
This also explains why I was under the impression that healing resets the leash timer - it doesn't but the fact that you have to stand still to cast, allows the mob to stand still and hit you, which then extends the leash.

**Comment by wizzymore** [comment]
The leash timer is around 11-12 seconds for the level of these mobs, atleast on retail.

Here are some of the conditions for the leash to reset:
- The mob should go more then 31 yards for the reset to work, so if you are spinning him in once place he will never reset.
- The mob should not be able to do a standing melee hit on you
- You should not cause any attack on the mob or cast any spells
- All resists on the mob will reset the leash timer
- Dots/thorns DON'T reset the leash timer

Because the pull you did is based on social aggro it means they all share the same leash, reset one leash timer will reset the leash for all the mobs.

The timer for the leash to reset starts from 0 everytime any of the mobs stand to attack you and they manage to get a hit on you ( not a parry, miss, dodge ) with a melee hit. If the melee mobs attack you while moving the leash timer is not reset.

I believe the bug from the video comes from the fact that he is attacked by the hunter mobs which on AC would cause the mobs to reset their leash, which is not correct, only melee standing hits should reset the leash.

In the video it took from second 13 (when the arrow hit the mob) to second 36 when the mob knocked you down and did a standing hit on you to reset the leash timer ( if there would be no bug in AC ) this means that the leash timer did not reset in 23 seconds which is way too long.

So there can be 3 things here:
1. The mobs have way too longs of a timer. (BUG)
2. The mob that was first pulled and started the leash timer did not went 31 yards from it's starting location and then the warrior got knocked and hit so the leash timer reset, i can't tell from the video as the warrior is walking with his back at the mobs ( never do that btw as you get dazed )
3. The ranged ( hunter ) gnolls reset the leash timer for doing a standing ranged hit (BUG)

**Comment by heyitsbench** [comment]
> The mob should go more then 31 yards for the reset to work, so if you are spinning him in once place he will never reset.

This depends mob to mob unfortunately, and is currently not implemented correctly on AC. These mobs have a significantly smaller "deadzone" than on official servers in every case.

> You should not cause any attack on the mob or cast any spells

Not quite true, attacks would reset leash as would "hostile action spells", e.g. applying a debuff or a damaging spell would reset the leash, but throwing a Renew on yourself or even full casting a Flash of Light for example would not reset the leash (assuming you have the distance).

> Dots/thorns DON'T reset the leash timer

The *application* of DoTs *does* reset the timer, but the DoTs ticks do not.

> I believe the bug from the video comes from the fact that he is attacked by the hunter mobs which on AC would cause the mobs to reset their leash, which is not correct, only melee standing hits should reset the leash.

This is almost certainly the case. Unfortunately, the true trigger for when a ranged attacking creature resets the leash as compared to a melee attacking creature is not something I understand myself, so that's not something I could implement properly on AC. It's possible that the linked PR will solve this issue as it takes less time for the creature to do its ranged attack than the proposed interval (but not the current one), but I have my doubts that it will match 1:1 with official behavior.

**Comment by wizzymore** [comment]
Ok, after looking at the code I can see it's a shitshow, there is a static 12 second timer before reset and before your change there is a 1.5 second standing still check that doesn't take into consideration attacks at all, idk if that T owner is a player or the leash owner, but if it would be the player it doesn't make sense on what happened on the video as the player never stood still for 1.5 seconds within the 12 seconds timer and the leash timer is only reset there and if the player is unreachable, which that is not the case also. If the `T owner` variable is a owner of the leash that makes sense tho, as the owner of the leash did stand still to shoot the arrows. Yeah I guess your fix is atleast fair, but this is 0% blizzlike

**Comment by heyitsbench** [comment]
> but this is 0% blizzlike

It's at least a significant improvement (in my opinion) from before the leashing system was overhauled. 😛

**Comment by wizzymore** [comment]
I will try to test your fix to see if it works. Tried to check now on latest commit hash and i really can't make any mob to stop chasing me and they are gray to me (lvl 20 vs 10/11).

**Comment by wizzymore** [comment]
Look at this: https://drive.google.com/file/d/1qanJ1CE3Ulb8r6YegL3EKQIeMBUEsmvT/view?usp=sharing

The mob will continue to attack you indefinitely if he can reach you in any way, this means that you can't escape mobs that have >=100% movement speed. If you can leave the melee range of the mob and he doesn't attack you he will reset after around 12 seconds, check 1:20

**Comment by heyitsbench** [comment]
Was that video recorded on latest master or with the PR applied?

**Comment by wizzymore** [comment]
The latest, did not check your pr as i just went to bed, i'll have a look tomorrow.
