### ISSUE TITLE
[Quest] The Force of Neltharaku - not counting

### ISSUE THREAD

**Issue by spinzaku** [azerothcore/azerothcore-wotlk#2091]
[Quest] The Force of Neltharaku - not counting

##### SMALL DESCRIPTION:

[Quest] The Force of Neltharaku - not counting at all every time netherwing drake is freed

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Should get a quest count when you free netherwing drake like this: https://www.youtube.com/watch?v=jOtutz3JMRI

##### CURRENT BEHAVIOUR:

Get quest: https://www.wowhead.com/quest=10854/the-force-of-neltharaku
Use quest item [Enchanted Nethervine Crystal] on netherwing drake. Wait for a second then  Netherwing Drake tag turns to green and attacks the orc (you kill this orc) and netherwing drake flies away. At this time you should get Enslaved Netherwing Drake Freed: 1/5. but nothing happens.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get quest: https://www.wowhead.com/quest=10854/the-force-of-neltharaku
2. Find netherwing drake 
3. Use quest item [Enchanted Nethervine Crystal]
4. Netherwing drake name plate turns to green and attacks the orc
5. help netherwing drake kill the orc.
6. Netherwing Drake flies away
6. Should get a quest count: Enslaved Netherwing Drake Freed: 1/5. but nothing happens.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

5086af8

##### OPERATING SYSTEM:

Ubuntu 16/18

**Comment by poszer** [comment]
Interesting i can't reproduce that. Correctly giving killcredit, while using this item on Drake, and helping killing creature near him. Just what i can see there, issue with inhabittype, should be set to use Ground + Flying so the Drake can fly away correctly, instead of this hip-hop flying animation (like stucking). Will open PR with that, changing inhabit. Could you please test again this about killcredit, or someone other to confirm this, since i can't reproduce it :/
http://prntscr.com/oejce0
http://prntscr.com/oejg63

**Comment by spinzaku** [comment]
Will do, im out now

**Comment by spinzaku** [comment]
I got to test this again. And it was working.. so weird. I will be closing this. and re-opening if the problem comes back, il also get more info like a video.
