### ISSUE TITLE
About the issue of attack strength display

### ISSUE THREAD

**Issue by isgoog** [azerothcore/azerothcore-wotlk#2097]
My equipment database property is relatively large, I found that the attack strength exceeds a certain value and it shows 0. This thing has puzzled me for a few days, can anyone help me.
Sorry, my English is not good. I hope that Google Translate can't cause dyslexia for you.
Thank you!

**Comment by w5860363** [comment]
confirm

Current behaviour: invalid in the file StatSystem.cpp
Expected behaviour: Rand attack intensity type
Steps to reproduce the problem:
Item Long Range Attack Intensity Over 32767
Or under Sunwell Core < 65534
Enter the game and open the panel to display 0
Branch: Master.
AC hash/commit: https://github.com/azerothcore/azerothcore-wotlk/commit/7b105b75dd2afda008c6a0b6f0fa42e806be1fd8
Operating system: Linux, Ubuntu 14.04 and Windows 7.
Modules: No.
Other Customizations: No.

**Comment by w5860363** [comment]
@poszer

**Comment by isgoog** [comment]
@FrancescoBorzi

**Comment by poszer** [comment]
What? I don't undestand

**Comment by poszer** [comment]
Missing information, closing this.
