### ISSUE TITLE
Ulduar bosses on hardmode, do not drop Hardmode loot [$10]

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#2116]
Ulduar bosses on hardmode, do not drop Hardmode loot

##### SMALL DESCRIPTION:

Ulduar bosses on hardmode, do not drop Hardmode loot

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Ulduar bosses on hardmode, drop hardmode loot

##### CURRENT BEHAVIOUR:

Ulduar bosses on hardmode, do not drop Hardmode loot

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter ulduar
2. kill a boss on hardmode
3. no hardmode loot drops (232/245) 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

171f289c2d0a+

**Comment by solidmaxtor** [comment]
What boss exactly have problems ?
I am runs everyday ulduar

**Comment by disclosurez** [comment]
> What boss exactly have problems ?
> I am runs everyday ulduar

run them in hardmode and check your loot, none of them work properly

**Comment by solidmaxtor** [comment]
Confirm this, not all loot HM its possible droop

**Comment by Misheel** [comment]
Huh? Hardmode Ilvl for 10 man is  232 Hardmode Ilvl for 25 man is 239. I have checked Flame Iron Council They all droping Hardmode ilvl items. I think you got it wrong man.

**Comment by disclosurez** [comment]
Specific bosses:

Iron Council
Thorim

**Comment by BarbzYHOOL** [comment]
So I tried the iron council in 10man, by killing steelbreaker last, I received 3 normal loot items (ilvl 219) and 1 hard mode item (ilvl 232). The archivum data drops too.

A WOWhead comment says "Molgeim last is considered the "Medium mode" of the encounter, and will reward 2 additional Runed Orbs and an Archivum Data Disc (starts the Algalon quest) if you kill him last. Steelbreaker last will also drop these, in addition to a level 239 piece of loot (like those shoulders)."

Molgeim killed last should drop 2 orbs if killed last, but he drops only one. He also drops correctly the archivum data.
Steelbreaker correctly dropped a higher ilvl piece in both 10man and 25man. So I guess Disclosurez thought it should drop ONLY hard mode items but it's not how it was.

In our DB, we have:
- 1 runed orb in both 10 and 25man (in medium mode) for Molgeim. https://webdb.fusion-host.eu/?npc=32927#drops-2
- 1 runed orb for Steelbreaker in 10man hard mode, and 2 runed orbs in 25man hard mode https://webdb.fusion-host.eu/?npc=32867#drops
- They all drop at 75% which sounds weird to me.

So here are the changes that must be done, in my opinion:
- Drop 2 runed orbs instead of 1. Or only drop 1 in 10man but drop 2 in 25man
- Probably increase to 100% drop rate, no?

Otherwise it's fine for the iron council, not gonna test every boss one by one.

**Comment by FALL1N1** [comment]
https://raw.githubusercontent.com/TrinityCore/TrinityCore/f7283d97660be93921fdabb58a9fc3a245ece6e2/sql/old/3.3.5a/TDB46_to_TDB47_updates/world/2012_04_18_02_world_reference_loot_template.sql

maybe this can help?

**Comment by mpfans** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/e2d7dc9bd7fc636469e46b82587a92f43e7825d9

There are no bugs in this commit
