### ISSUE TITLE
Trial of The Crusader Faction Champions Do Not Hold Agro.

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/azerothcore-wotlk#2193]
##### SMALL DESCRIPTION:

Trial of The Crusader Faction Champions Do Not Allow Agro to be rebuilt.
This occurs in ToC 25/10 Man Heroic

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Trial of The Crusader Faction Champions should reset their agro as planned, but then allow agro to be rebuilt.

##### CURRENT BEHAVIOUR:

Trial of The Crusader Faction Champions reset their agro, and then do not allow agro to be rebuilt during the fight they just do wtf they want.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enter ToC On Heroic Mode 
2.  Do Faction Champions 
3.  Profit

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

189d4db1a7d5 2019-08-08 

##### OPERATING SYSTEM:

Linux

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by talamortis** [comment]
This is a pvp based combat event, they should not be able to store aggro.

**Comment by mik1893** [comment]
not a bug, by design. You cannot aggro them.
The NPC's AI uses Proximity, Health and Damage to decide who to attack. Try to never be in the center of a group of NPCs or they are likely to all turn and one-shot you (Rogues beware!). If you Aoe, be prepared to get aggro. If something is attacking you or even heading your way, run.
Taken from https://wowwiki.fandom.com/wiki/Faction_Champions
