### ISSUE TITLE
Gameobject pooling for herbs and mines not working correctly

### ISSUE THREAD

**Issue by Malow** [azerothcore/azerothcore-wotlk#2211]
##### SMALL DESCRIPTION:
The gameobject pooling for herbs and mines is supposed to only spawn some nodes of the available ones within a zone if I understand it correctly. Currently it seems to be spawning all, or at least way too many, of them at the same time.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
There should be fewer herb and mining nodes in the world, and especially mining nodes where either a rare-version or a common-version can spawn (Truesilver/Mithril, Iron/Gold, Tin/Silver) should only have 1 of them spawned, and not both at the same time spawned inside of each-other.

##### CURRENT BEHAVIOUR:
![Image1](https://i.imgur.com/MTjTT9E.png)
![Image2](https://i.imgur.com/5lJVY2z.jpg)
![Image3](https://i.imgur.com/u9KAChR.jpg)
![Image4](https://i.imgur.com/2MBNs8j.jpg)
![Image5](https://i.imgur.com/GuLvtZz.png)

##### EXTRA NOTES:
I've only tested the Vanilla-world, but the problem exists in all zones I've tested (10+ I think). Black Lotuses in Burning Steppes is a good example, Black Lotuses should be pretty rare, but doing a full sweep in Burning Steppes you can easily find 10+ Black Lotus nodes.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
178315f8e263394063a602cda17d6eca1bd294da

##### OPERATING SYSTEM:
Win 10

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
Completely fresh non-modified server.

**Comment by andoys** [comment]
Hmm in my live server,  players also reported same thing for Classic World. But it's a different story for Northrend there's too few herbs and mining nodes. 
Might be related. Which for me fixed some of it here: https://github.com/azerothcore/azerothcore-wotlk/issues/1857#issuecomment-496941534

**Comment by BarbzYHOOL** [comment]
Do we have to fix the DB one by one or is it core related? I don't know but that's kinda annoying

**Comment by Si1ker** [comment]
Could this be related? #2510

**Comment by Zoidwaffle** [comment]
I reworked all the herbs/treasures/minerals for Bloodmyst Isle recently. I also looked at other zones - and some zones seem like they are working well, using pools and pools of pools etc., while others don't use pools and everything just spawns at once and then respawns after 1 hour etc.. I didn't check the zones above, but it's quite probable that they don't use any pooling at all.

It was super boring - the only fun part was semi-automating it...

In short, I tried to find all objects based on map coordinates for a zone, trying to make a square matching the 4 corners. If the spawning locations seem right, maybe the issue is just making a pool - should be super easy. Anyway, for Bloodmyst there where alsmost no objects, so I removed them all (but kept the guid for re-use).

Then I teleported to all locations from Gathermate - and spawned objects. With the detail that I only spawned minerals on hills / inside mines, some herbs should grow only in water etc., and no 2 similar objects should be super close. So some "artistic" liberty there...

The end was 435 locations where objects could spawn. Then I pooled all herbs and set 30 to spawn. Treasures 10. MInerals also 30. I made the respawn rate 5 minutes, to fill up the pool fast (the objects are not rare).

I didn't make any pool of pools, which is also an option, so say a mineral vein has 10% to spawn as silver, 20% as tin and 70% as copper.  For very precious herbs, like Black Lotus, a pool of all zone locations and only 1 spawn, might be needed with a long respawn timer. Similarly, some mines could get a pool of their own - to make sure that inside those, there's almost always something.

Some weirdness with pool-sizes, but as a player I think it turned out nicely.

The end result for Bloodmyst Isle can be seen here: https://github.com/azerothcore/azerothcore-wotlk/pull/4689#issuecomment-800286229

Doing something similar for all zones where stuff seems wrong, would solve this... but it's a lot of work.

The crude scripts I made to help me out are made to run as Bash on Linux (Debian 10) - I could try to clean them up and share them, if others want to try it out.

**Comment by dantav** [comment]
The way this should work, is a queueing system. Two queues for each zone, one for herbs one for mines. Once a node is taken, its put in the back of the queue. Next item is then spawned based on its timer. There should be a const number defined for each zone and type on how many nodes are currently a available.

Im not sure if this is the way it currently works with ObjectPool as I have no looked at the code yet, but I plan on changing my fork to have this behavior. Ill send a PR once its fully tested. Let me know what you all think.

I do not think this is a DB issue.

**Comment by sudlud** [comment]
@Gultask you got any opinion on this?

**Comment by Gultask** [comment]
Not an issue anymore! 🥳🥳
Yeah it was only a thing because the DB was very disorganised.
