### ISSUE TITLE
Quest You Are Rakh'likh, Demon

### ISSUE THREAD

**Issue by katz1** [azerothcore/azerothcore-wotlk#2328]
##### SMALL DESCRIPTION:
In the quest _You Are Rakh'likh, Demon_ (3628), you cannot teleport up to the mountain to fight _Razelikh the Defiler_. The quest can be only completed if a GM teleports you up.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
In the quest you are provided with the _Ward of the Defiler_ item (10757). While you have this item in your inventory, running over a _Rune of the Defiler_ game object should teleport you up to the top of the mountain near the _Altar of the Defiler_ game object.

##### CURRENT BEHAVIOUR:
Running over _Rune of the Defiler_ game objects while having the quest and the _Ward of the Defiler_ item in your inventory does nothing.

##### EXTRA NOTES:
The quest worked on CMangos classic the last time I tried it.
The Rune of the Defilers are the purple scribblings on the ground.

##### AC HASH/COMMIT:
a9f66d6f14425ebdc56766ced90602bb21cdda59

**Comment by wizzymore** [comment]
> In the quest you are provided with the Ward of the Defiler item (10757). While you have this item in your inventory, running over a Rune of the Defiler game object should teleport you up to the top of the mountain near the Altar of the Defiler game object.

This is incorect, i watched a lot of videos and in the new way you have to cross over the rune, in the Wotlk blizzlike way you have to talk with `Deathly Usher` which is correct ( .go c 2704 ) The only thing that differs is the location of the rune and Deathly Usher being a little more to the right than it should

**Comment by katz1** [comment]
Thanks.

**Comment by Arcitec** [comment]
This quest works properly now (2024): You speak to the Ghostly Usher and he teleports you up. It doesn't teleport your team (it didn't on Blizzard either).

There is an issue with the pathfinding on AzerothCore. The boss cannot path down the mountain, so you cannot kite him down to friends waiting below, unfortunately. He will path halfway down and then he teleports back home again. That's not blizzlike. On official, he can be kited down.

That's unfortunately not a problem specific to this quest. It is generic pathing differences compared to official. So I don't think there's any point reporting it.

Unfortunately that means the quest is impossible for most players on AzerothCore, since friends cannot teleport up, and he cannot path down, and he's a group quest who can easily 4-shot kill most players.
