### ISSUE TITLE
[Crash] [$100]

### ISSUE THREAD

**Issue by IceNet** [azerothcore/azerothcore-wotlk#2422]
##### CURRENT BEHAVIOUR:
Server crashes for 2 days now, after the newest commit, with crash log.

##### STEPS TO REPRODUCE THE PROBLEM:
 I don't know. 

##### EXTRA NOTES:
 Crashlog:
https://gist.github.com/IceNet/d4aed5961be66e541dbbaa8afa96555b

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/0fd565d5573dce91dc87874b6de2ca4b3f884bfa

##### OPERATING SYSTEM:
Windows Server 2016

##### MODULES:
1vs1
Account Mounts
Better Item Reloading
Duel Reset
Individual XP
PvP Titles
Teleporter
Transmog
Weekend XP

**Comment by vhiperdev** [comment]
You are suffering attack through OPCODES by WPS
we will be working to block this track the PR
https://github.com/azerothcore/azerothcore-wotlk/pull/2410

**Comment by lineagedr** [comment]
Crash same as in https://github.com/azerothcore/azerothcore-wotlk/issues/2409

**Comment by Helias** [comment]
I'm working on it, need time.

**Comment by Helias** [comment]
Try it: https://github.com/azerothcore/azerothcore-wotlk/pull/2410

I tested it with HEARTBEAT, and it prevent the crash

**Comment by Winfidonarleyan** [comment]
I have fix for this

**Comment by Helias** [comment]
I already found a way to prevents the crashes.
But now I'm looking to do it in a clean way for others opcode, indeed I want to make a general fix for all malformed packet / opcode.

**Comment by Helias** [comment]
I think that I finished the PR, test it pls.

https://github.com/azerothcore/azerothcore-wotlk/pull/2410

**Comment by Wokwer** [comment]
> I already found a way to prevents the crashes.
> But now I'm looking to do it in a clean way for others opcode, indeed I want to make a general fix for all malformed packet / opcode.

The servers have problems, people can't play, every day and every hour, attacked by a hacker, greatly upset the players, and they leave the server, the owners of the servers do not have time to wait, they bear the loss of the game audience. Winfidonarleyan
Offers a real way to protect yourself from this. The method is tested on my server in real time! During the hacker attacks, and the proposed way works! Attacks have stopped! 
Please accept #2426 as soon as possible, so that people do not suffer without a game, and after that you will make large-scale changes in opcodes.

If you don't have a server or you haven't been attacked, then you won't understand how expensive it is for the players to spend the time of its inaccessibility!

**Comment by Wokwer** [comment]
> I finished the PR, test it pls.
> 
When we were protecting our server, we were attacked by a real intruder, how do you want to test it? Do you think you can call him and he will help you to repair what he threatened before?

**Comment by FrancescoBorzi** [comment]
@Wokwer thanks for your feedback. If you've tried https://github.com/azerothcore/azerothcore-wotlk/pull/2426 please leave a comment in that page about your results (not here) so we can merge it

**Comment by Helias** [comment]
@Wokwer, I already prevents the crashes yesterday evening [(14 hours ago)](https://github.com/azerothcore/azerothcore-wotlk/pull/2410/commits/fbe0505d77a01ab49d88f286a39856ab1386f9e8) using some try / catch, so you could use from yesterday evening a lot time before the winfi's PR.

I tested it several times, but after I also accepted the suggestion of @lineagedr, to improve the PRs, I improved it asap and tested it again, I just ask to "test" the PR again, because any improvements about opcode could close one bug but open more, so I asked to several users to test it, but I already tested the PRs yesterday evening and several time this morning, indeed if you really want to make safe your server you should already tried my PR 14 hours ago I think :P ?

I understand your point of view about safety and security of your server indeed I update ever my PRs and scripts when I did it.

**Comment by Wokwer** [comment]
@Wokwer Okay, I'll write a review there.
And I want to say that this code, I do not want to test, just because it may not protect my server, now my server is good and quiet, I do not want to risk the morale of my players.

**Comment by FrancescoBorzi** [comment]
@IceNet the issue must be open until the fix is on `master` branch

**Comment by IceNet** [comment]
Okay, sorry!
