### ISSUE TITLE
[Quest] Into Hostile Territory 

### ISSUE THREAD

**Issue by trudster-gaming** [azerothcore/azerothcore-wotlk#2428]
[Quest] Into Hostile Territory 

##### SMALL DESCRIPTION:
"Into Hostile Territory" quest is currently not working like expected.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
After accepting the quest, you are informed to go see the gryphon master to get a ride. When you see the master, he tells you to hop on one of the gryphons behind you and it takes you to the desired location.

##### CURRENT BEHAVIOUR:
After mounting the grphon sitting on the ground, nothing happens. You just sit there until you click to "Leave Vehicle"

https://wowgaming.altervista.org/aowow/?quest=12325

##### AC HASH/COMMIT:
4a483aa3fd6e7fbc34081361b2a3c381d676b5ca

##### OPERATING SYSTEM:
 Windows 10

##### MODULES:
Auctionhouse Bot
AutoRevive on death
NPC Instance, LFG, Dungeon cooldowns reset
Individual-XP
npc_beastmaster
npc_enchanter
BuffMaster
VASAutoBalance
Transmogrifier

**Comment by pklloveyou** [comment]
```sql
1.   .qu ad 12321
2.   .qu c 12321
3.   .go c id 27136
4.   quest 12325
```

**Comment by Hacaw** [comment]
I **can not** reproduce this issue.

TESTING
---
The author is making a confusion between quests, in the expected-behavior of the issue is referring to the quest: https://www.wowhead.com/quest=12237/flight-of-the-wintergarde-defender#videos:id=86320, while in the title/small-description is referring to another quest which works fine.

For 
>After accepting the quest, you are informed to go see the gryphon master to get a ride. When you see the master, he tells you to hop on one of the gryphons behind you and it takes you to the desired location.
>
You don't need to hop on the gryphons that are already spawned, you need to use the item received from the quest-giver: https://www.wowhead.com/item=37287/wintergarde-gryphon-whistle and ride that gryphon, which is similar to a normal flying mount that have some vehicle options.

See images for proof:

Wintergarde Gryphon - the one that is spawned by the https://www.wowhead.com/item=37287/wintergarde-gryphon-whistle 
![image](https://user-images.githubusercontent.com/6963500/101525964-b6d09c80-3994-11eb-9de2-d3f573461ad0.png)


Wintergarde Gryphon - the one that the author is refering to, but it's not the one which you should mount
![image](https://user-images.githubusercontent.com/6963500/101525931-a91b1700-3994-11eb-8553-05508c4a155e.png)


Flying Quest Gryphon - works fine
![image](https://user-images.githubusercontent.com/6963500/101525855-8a1c8500-3994-11eb-90ba-dfc4670fbe05.png)

SPEC
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10+Docker
MODULES / CUSTOMIZATION: None

**Comment by LukasVolgger** [comment]
Thx for checking @Hacaw !
