### ISSUE TITLE
Professor Putricide: Mutated Abomination not being energized by players

### ISSUE THREAD

**Issue by OcelotGear** [azerothcore/azerothcore-wotlk#2485]
Professor Putricide: Mutated Abomination not being energized by players

##### DESCRIPTION:
Putricide's Mutated Abomination is not building energy through players healing (druids) & shielding (priest)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The abomination should generate energy through Revitalize(http://wotlk.cavernoftime.com/spell=48539) and Rapture (http://wotlk.cavernoftime.com/spell=47535). 

##### CURRENT BEHAVIOUR:
The abomination only generate energy through Eat Ooze caused by https://github.com/azerothcore/azerothcore-wotlk/pull/2386

##### STEPS TO REPRODUCE THE PROBLEM:
1. Enter ICC, (include a resto druid with Revitalize talent and a disc priest with Rapture talent in you raid)
2. Druid should heal Mutated Abomination with Rejuvenation (http://wotlk.cavernoftime.com/spell=48441) or Wild Growth(http://wotlk.cavernoftime.com/spell=48438) be aware that abomination wont gain 8 energy when Revitalize proc.
3. Priest should cast Power Word:Shield (http://wotlk.cavernoftime.com/spell=17) on Mutated Abomination, when Shields breaks by damage abomination wont gain 16 energy.

##### PROOF:
https://www.wowhead.com/forums&topic=158065
```proper specced priests and druids can give you free energy while healing the abo (keep rejuvenation up)```

https://www.mmo-champion.com/threads/720230-Prof-Putricide-25-Heroic
```with 2 resto druids they should both have revitalize which feeds the abom tons of energy```

##### BRANCH:
Master

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/64aa475d0f605bb31b784722e555ec166b22b09c

##### FIX:
revert https://github.com/azerothcore/azerothcore-wotlk/commit/da6c255a7074b7ccb09156ea8c4711b31b2fc865

**Comment by GMKyle** [comment]
This guys missed that part apparently......lol
https://wowwiki.fandom.com/wiki/Professor_Putricide  
Or perhaps i should include more links.
I think this was a very big ancient bug that make players' life more easy over years.

**Comment by OcelotGear** [comment]
There is nothing in that wiki. Old behavior was correct, you are the one who is making fight harder now. Where is your proof/data/changelog showing this was a bug back in 3.3.5?

```with 2 resto druids they should both have revitalize which feeds the abom tons of energy``` date: 2010-05-22 patch: 3.3.3a

next patch was released on june
https://wow.gamepedia.com/Patch_3.3.5
https://wow.gamepedia.com/Patch_3.3.5_(undocumented_changes)
the other, a minor patch in july
https://wow.gamepedia.com/Patch_3.3.5a

in none of the changelogs is mentioned a bugfix related to the energy or the talents

**Comment by GMKyle** [comment]
There is not info in https://wowwiki.fandom.com/wiki/Professor_Putricide because like i said  it's a bug xD
You keep repeating  ```with 2 resto druids they should both have revitalize which feeds the abom tons of energy``` well yea the date it's correct but in which server?
 And now your are clamming for proofs xD, check
https://www.engadget.com/2010/06/03/wow-coms-guide-to-professor-putricide/
not mentioned your trick
https://ezinearticles.com/?World-of-Warcraft-Tactics---How-to-Kill-Professor-Putricide&id=3546414
not mentioned your trick
https://www.mmo-champion.com/threads/687581-Guide-to-Professor-Putricide%EF%BC%8825-Man%EF%BC%89
not mentioned your trick, mmo champion what?? :P
finally
http://wotlktactics.blogspot.com/2010/09/icecrown-citadel-professor-putricide.html
especially this part ``` If you abomination notices his energies are too low, have him leave one puddle on the floor as a "food source"```
https://www.youtube.com/watch?v=35p21sdb4us
https://www.youtube.com/watch?v=35p21sdb4us
Please check both videos. Mutated Abomination driver use puddle as food source an don't eat them completely. Now, maybe there is an issue https://github.com/azerothcore/azerothcore-wotlk/issues/2252 but this was a bug... best regards

**Comment by OcelotGear** [comment]
Man you are just guessing. If that was a bug must be in the changeloag or undocomented changes. And if there is a bug not solved in 3.3.5 you are not supposed to fix that becouse is blizzlike.
This is not a bug mmochampios was a retail forum back in the time like wowhead where also the trick is mentioned in the same patch and olders.

you mentioned engaded dated March 06
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-exploits/279110-unlimited-energy-abom-putricide-fight.html#post1796516
now in patch 3.3.3 dated March 23
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-exploits/279110-unlimited-energy-abom-putricide-fight.html#post1796516

All the links you post are dated pre 3.3.3
If is not mentioned maybe is just not present on pre 3.3.3 or just they dont know that.

In none of your links says something about a bugfix, you are just guessing
Even on owned core where they mark a exploit or bug as fixed was marked that way.

The tanlent was doing what is suppose to do:
```Your Rejuvenation and Wild Growth spells have a 5% chance to restore 8 Energy, 4 Rage, 1% Mana or 16 Runic Power per tick.```

**Comment by OcelotGear** [comment]
Video Proof
https://youtu.be/hT4C_3RvtIU?t=32
0:32-0:36
See how the abomination gain energy through rejuvenation when there is no puddles on the floor.

**Comment by solidmaxtor** [comment]
> And if there is a bug not solved in 3.3.5 you are not supposed to fix that becouse is blizzlike.

Mmm... Azerothcore with old bug / exploit blizzard or azerothcore without old bug / exploit blizzard.
Difficult decision, I better go for coffee.

**Comment by OcelotGear** [comment]
Is not even a bug, just this dude pushing without research.

**Comment by Stoabrogga** [comment]
As far as I read this was fixed with the talent changes implemented in patch 4.0.1. If this **really** was an exploit at the time then it's good to have it fixed in AC, no matter if it's blizzlike or not. That's just my opinion, though.

**Comment by OcelotGear** [comment]
Are you guys serious?
The talent in 3.3.5 restores Energy, Rage, Mana or Runic Power
http://wotlk.cavernoftime.com/spell=48544

In 4.0.1 the talent was reworked and only restores Mana obviously is not going to restore abomination's ENERGY.
http://www.cavernoftime.com/spell=48544

BUT the abominations is a vehicle and vehicles are creatures, knowing that and knowing that pets ares creatures you can see how the talents keeps restoring pet's mana as well how the talent was restoring energy on Death Knights Ghoul in wotlk.

Talent restoring Pets mana in Cata:
http://www.worldoflogs.com/reports/ugp4twfhhoobbwzl/xe/?enc=bosses&boss=36678&x=type+%3D+TYPE_GAIN%0D%0AAND+powerType+%3D+POWER_MANA%0D%0AAND+targetType+%3D+%27Pet%27

Talent restoring Pets energy in Woltk:
http://www.worldoflogs.com/reports/eye60iq5l6c9zxih/xe/?s=3718&e=4045&x=type+%3D+TYPE_GAIN%0D%0AAND+powerType+%3D+POWER_ENERGY%0D%0AAND+sourceType+%3D+%27Pet%27

Rapture was reworked too and only restores priest mana.

This is not a bug and i my be wrong but this is a wotlk emulator isn't it?
Kyle please stop smoking grass, peace.

**Comment by BarbzYHOOL** [comment]
Stay polite and lower your tone when you talk to contributors to this **voluntary based** project.

Also the last person to answer was agreeing with you...

**Comment by OcelotGear** [comment]
Stoabrogga wants apply cata stuff to a wotlk emulator only to not accept that the commit was wrong.
He is not agreeing with me.

**Comment by Stoabrogga** [comment]
> Stoabrogga wants apply cata stuff to a wotlk emulator only to not accept that the commit was wrong.
> He is not agreeing with me.

No, the reason I did not agree is because the game mechanic clearly states to eat ooze to gain energy. Using player spells for this is an exploit in my opinion, which was never intended by Blizz. But nethertheless, it has to be discussed with the other staff members and we'll then decide what to do.

**Comment by Knindzagxg** [comment]
Ocelot is right about this one.

Since start of ICC, Abomination was able to gain extra energy trough Revitalize and Rapture, but not many guilds knew about this one at start.
Players tried to abuse it after from what i remember, but they did stealth fix that will apply it only from 1 druid and 1 priest, to prevent class stacking (Wish that was the case today tho -.-')

They never said anything about this, and it was up till Cataclysm and change of Talent system.

Thing is, this won't change fight that much at all. It will help yes, but soaking for energy still remain top priority. Also, if anyone gonna try and sort this, it have to be done super super carefully towards part that you are allowed to have only 1 priest and 1 druid able to do this.

Not sure about proc chance yet, but will check it soon enough, cause it was nerfed towards Abomination.

**Comment by Stoabrogga** [comment]
@Knindzagxg 
Thanks for your feedback. So in order to get this right we need a new PR with the following changes, correct?
- Revert commit da6c255
- Ensure that Revitalize (Rank 1-3: 48539, 48544, 48545) and Rapture (Rank 1-3: 47535, 47536, 47537) can only be applied once on the Mutated Abomination, no matter how many players cast this

**Comment by OcelotGear** [comment]
@Knindzagxg this is stackeable

http://www.worldoflogs.com/reports/c6ql9qrug06m8yy7/xe/?s=4974&e=5330&x=type+%3D+TYPE_GAIN%0D%0AAND+powerType+%3D+POWER_ENERGY%0D%0AAND+targetType+%3D+%27Vehicle%27%0D%0AAND+%28spellID+%3D+48540+or+spellID+%3D+63655%29
this is a 3.3.5 combat log, no hotfix was applied
![mutated](https://user-images.githubusercontent.com/49760010/70390486-415d7500-19aa-11ea-866a-38d84fdfcf7f.png)

Less than a 1s difference between procs meaning that are from differents druids

**Comment by Knindzagxg** [comment]
That was just lucky proc since even they were nerfed.

U were not able to stack multi druids on it, cause it would be easy game then.
1 priest 1 druid, nothing more.

**Comment by solidmaxtor** [comment]
Possible solution.
Add in Custom server options:

```
Acore with old bug / xploit
Default 0
with bug/xploit 1
```
An add list of cases like these, for people like OcelotGear

... ok its only a joke, for me without this old bug like more  <3

**Comment by OcelotGear** [comment]
@Knindzagxg Its not a lucky proc
![notlucky](https://user-images.githubusercontent.com/49760010/70393862-91016800-19cd-11ea-9e79-ebae26563e94.png)
both druid are healing the abomination, this is stacking

log querry:
http://www.worldoflogs.com/reports/c6ql9qrug06m8yy7/xe/?s=4974&e=5330&x=%28type+%3D+TYPE_HEAL+or+type+%3D+TYPE_GAIN%29%0D%0AAND+targetType+%3D+%27Vehicle%27%0D%0AAND+%28spellID+%3D+48441+or+spellID+%3D+53251+or+spellID+%3D+48540%29

**Comment by Knindzagxg** [comment]
Im on Blizz since 2005 and playing druid as main since 2009.
Trust me they dont stack.

Reason is simple - If you could stack multi resource gain abilities, u would not need other classes.
It will go same towards, lets say Rogues - Bring 5 druids, keep them casting and rogue DPS will be crazy high due 100% uptime energy gain.

Only mechanic that were super bugged through all this years was Nefarian in Cata, where you could stack multi Rip DMG increase DoT on boss from druids - After very first kill it was changed, and loot was removed.

**Comment by OcelotGear** [comment]
For that reason is a 5% proc chance talent is not a 100% proc.
I only trust on proofs.

**Comment by Knindzagxg** [comment]
Well, if you take proofs and dunno how to read them then it's to bad.

If we gonna make PR, it's not gonna be stack able.

Do math, and calculate how much chance it will be there with 5 druids.
Pointless to give you more information unless you get this part correct.

**Comment by BarbzYHOOL** [comment]
"And if there is a bug not solved in 3.3.5 you are not supposed to fix that becouse is blizzlike."

Btw I disagree with that strongly.

**Comment by OcelotGear** [comment]
5*5= 25% still not 100% and 5 druids is not viable or common for raiding or any situation.

1. The guys saying this is a bug does not show a link proving that.
2. The guys saying this was a hotfix neither.
3. The guys saying this was fixed with cataclysm forget that almost all class spell was reworked with the release of the expansion and if the spell was changed this doesn't mean is broken.
4. This is not a bug because was present from the release of Icecrown Citadel to the release of Cataclysm where a lot of spells and mechanics and more and more has changed.

17 Junary 2010 (Patch 3.3.0):
http://www.worldoflogs.com/reports/f477l46z2m5dxncz/xe/?enc=bosses&boss=36678&x=%28type+%3D+TYPE_HEAL+or+type+%3D+TYPE_GAIN%29%0D%0AAND+targetType+%3D+%27Vehicle%27%0D%0AAND+%28spellID+%3D+48441+or+spellID+%3D+53251+or+spellID+%3D+48540%29

28 July 2010 (Patch 3.3.5)
http://www.worldoflogs.com/reports/aavff7dn5549b1oj/xe/?s=975&e=1300&x=%28type+%3D+TYPE_HEAL+or+type+%3D+TYPE_GAIN%29%0D%0AAND+targetType+%3D+%27Vehicle%27%0D%0AAND+%28spellID+%3D+48441+or+spellID+%3D+53251+or+spellID+%3D+48540%29

5. From 3.3.0 to 3.3.5a(**7 Patches**) there is no mention about a nerf to this mechanic in the changelogs or undocumented changes.

https://wow.gamepedia.com/Patch_3.3.0
https://wow.gamepedia.com/Patch_3.3.0_(undocumented_changes)
https://wow.gamepedia.com/Patch_3.3.0a
https://wow.gamepedia.com/Patch_3.3.2
https://wow.gamepedia.com/Patch_3.3.2_(undocumented_changes)
https://wow.gamepedia.com/Patch_3.3.3
https://wow.gamepedia.com/Patch_3.3.3_(undocumented_changes)
https://wow.gamepedia.com/Patch_3.3.3a
https://wow.gamepedia.com/Patch_3.3.5
https://wow.gamepedia.com/Patch_3.3.5_(undocumented_changes)
https://wow.gamepedia.com/Patch_3.3.5a
https://wow.gamepedia.com/Patch_3.3.5a_(undocumented_changes)

**Comment by GMKyle** [comment]
Having read members comments, i think future PR(if it's decide make one) should be focused on Revitalize' stacking part, because the mechanics of Priest Power word: shield prevent Rapture stacking.
But wait , i'm just a smoker grass dude. i'm just saying ....... :P

**Comment by OcelotGear** [comment]
Im not going to push something like stack nerf without proof, if is required (because github have the functionality to reverts commits and someone with permissions and one click can do that) i will do a pr for a revert.

**Comment by Stoabrogga** [comment]
I discussed this with AC staff and we will leave the encounter as it is now, which means that you cannot use the exploit anymore. The abomination was meant to get energy by eating ooze, not by player spells, and we keep this fixed on AC. If you don't want this behaviour you can revert the changes on your own server, should be easy enough. There will be no further discussion, so closing and locking this issue.
