### ISSUE TITLE
Event dates not correctly

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#2501]
Event Darkmoon Faire not work. Brewfest not work. Events does not match the dates on the calendar.

**Comment by FrancescoBorzi** [comment]
Missing AC version (commit hash)

**Comment by Mitradis** [comment]
Always last. Just check all events in game, none of them work correctly. Check the sequence of events every month. You yourself must see everything, you are not blind. I have enUS client. Darkmoon Faire no or does not match the dates on the calendar.

**Comment by Mitradis** [comment]
https://ibb.co/Tq9XNRM
https://ibb.co/p1H8bnk
https://ibb.co/qMbcc6r
https://ibb.co/yp0ZgZk

**Comment by FrancescoBorzi** [comment]
@Mitradis "always last" is not useful, you should add the commit hash

**Comment by Mitradis** [comment]
and it’s really so difficult for you to check it yourself to make sure this is so. Probably hard to translate the date. 

it doesn’t matter, I have already fixed it in myself. And if you want or do not want, you can not pay attention further.

**Comment by FrancescoBorzi** [comment]
@Mitradis do you mind sharing your fix?

**Comment by BarbzYHOOL** [comment]
Show more respect.

Your comments are really stupid because the commit hash is notably useful after a long period of time. Do you think in one month we will verify which commit was done at which date ?

If you want to share your fix, you can open a PR immediately, no need to open an issue, no need to tease us with "if you want it, maybe I can give it" etc...
