### ISSUE TITLE
Docker ac-database image build failed,Permission denied

### ISSUE THREAD

**Issue by espaja** [azerothcore/azerothcore-wotlk#2565]
docker ac-database image build failed,Permission denied
##### SMALL DESCRIPTION:
docker ac-database image build failed,Permission denied  with root user
##### EXPECTED BLIZZLIKE BEHAVIOUR:
build successful
##### CURRENT BEHAVIOUR:
ERROR: Service 'ac-database' failed to build: The command 'bin/sh -c ./azerothcore/bin/acore-db-asm 1' returned a non-zero code:126
##### STEPS TO REPRODUCE THE PROBLEM:
1. run ./bin/acore-docker-generate-etc
2. run ./bin/acore-docker-build

 my current user is root~
##### EXTRA NOTES:
I add a RUN chmod -R 755 /azerothcore before RUN ./azerothcore/bin/acore-db-asm 1 to avoid this Permission denied error

maybe it's my operation system or docker  user group config problem？
##### BRANCH(ES):
master
##### AC HASH/COMMIT:
55b23c53ad6e10c63e57eb589f0e61ac1136aa2e
##### OPERATING SYSTEM:
CentOS7 & Docker19.03.5&docker-compose1.25.0
##### MODULES:
none
##### OTHER CUSTOMIZATIONS:
none

**Comment by FrancescoBorzi** [comment]
Unfortunately, your reproducing steps don't help to reproduce the issue :(

```
run ./bin/acore-docker-generate-etc
run ./bin/acore-docker-build
my current user is root~
```

I guess this is probably not a bug but some permission issue.

I leave this open for a while, in case I or someone else can reproduce it. Otherwise, it would be better to move this to stackoverflow.

**Comment by Kitzunu** [comment]
@h0lysp4nk Since I saw your previous issue I thought I could snatch a quick review for this from you ;)

**Comment by h0lysp4nk** [comment]
@Kitzunu @espaja 

Confirmed, I can reproduce this but, this isn't an issue with AzerothCore but is more a docker thing. 

As you are trying to run AzerothCore as root the resulting issue is caused by file ownership problems. As the Dockerfile for all the containers in AzerothCore don't specify that they should run as root you're getting the `Permission Denied` error because Docker is creating a generic user which doesn't have permission to access the files.

To fix this you'd need to go into each Dockerfile and add the below: after `FROM`
```
FROM ...

USER root

....
```

Any questions or issues please feel free to let me know :)

**Comment by Kitzunu** [comment]
Is this something that could be "fixed" from our side, or is it just an issue for Docker itself?

**Comment by h0lysp4nk** [comment]
It certainly is yes but, the only fix would be to make all the containers run as root. The problem with doing that is because the containers are running as root you then have a possible security vulnerability.

But overall it's a docker best practice thing. They officially say on their website to run the containers on a non-root user as it's more secure.

**Comment by Kitzunu** [comment]
Okay, I will close this as it then is not an AC issue, but an end-user error :)

**Comment by espaja** [comment]
thanks! @h0lysp4nk @Kitzunu @FrancescoBorzi
