### ISSUE TITLE
Loot Problem using Dungeon finder

### ISSUE THREAD

**Issue by solidmaxtor** [azerothcore/azerothcore-wotlk#2603]
Problem whit loot items distribution using Dungeon Finder

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Items must have priority by type / class, for example:
Item plates only war/dk/Pala can give need and the other classes only greed.
SP items per SP class (caster, helers)
AP items for AP class.
Tanks items by Tank class
Etc.

##### CURRENT BEHAVIOUR:
any class/function can need any item

##### STEPS TO REPRODUCE THE PROBLEM:
Go dungeon using "dungeon finder" kill boses check requeriments free need for any loot.

##### BRANCH(ES):
rev. 77a877c82a70+ 2020-01-21

##### OPERATING SYSTEM:
Ubuntu 18

##### MODULES:
Anticheat
Transmorg

**Comment by Si1ker** [comment]
Tested, not confirmed.

5 different accounts
5 different classes = dk, druid, rogue, war and mage
- The group used dungeon finder (normal)

* Dungeon: https://www.wowhead.com/ahnkahet-the-old-kingdom
* Boss: https://www.wowhead.com/npc=29309/elder-nadox
* Item: https://www.wowhead.com/item=35607

DK cannot pick need, only greed.
![2020-02-19 14_34_14-Window](https://user-images.githubusercontent.com/61223313/74873665-408b7c80-5325-11ea-86ec-27fdf1e8dd4d.png)

Mage cannot pick need, only greed.
![2020-02-19 14_34_39-Window](https://user-images.githubusercontent.com/61223313/74873892-9fe98c80-5325-11ea-94da-29d0b7dd75a5.png)

Warrior cannot pick need, only greed.
![2020-02-19 14_34_54-Window](https://user-images.githubusercontent.com/61223313/74873918-ae37a880-5325-11ea-95ec-38bb531e8b5c.png)

Only the druid and rogue were able to select Need, rogue got the gloves.
![2020-02-19 14_35_22-Window](https://user-images.githubusercontent.com/61223313/74874008-d6270c00-5325-11ea-843a-1b9afd7c3e06.png)



* If a tried to reproduce the issue with a wrong procedure, let me know, otherwise check your core.

My rev ..
![2020-02-19 10_55_06-Window](https://user-images.githubusercontent.com/61223313/74874184-2605d300-5326-11ea-91e5-4baa36383145.png)

I hope it helps.

**Comment by Helias** [comment]
Probably is related to the modules anticheat or transmit?

**Comment by pklloveyou** [comment]
After testing, I did not have this error
