### ISSUE TITLE
.gm off doesn't make NPC disappear

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2662]
##### SMALL DESCRIPTION:

I have a non phased NPC, it can't be seen by a normal player when in a phase (i use the mod-guildhouse for that). If I turn `.gm on` I can see the NPC. If I turn it off `.gm off` he doesn't disappear.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The NPC should disappear when gm mode is off

##### STEPS TO REPRODUCE THE PROBLEM:

I don't know how to manipulate phases with commands.
What I did was to just use the mod-guildhouse and buy some NPCs for my guildhouse and also spawn a normal NPC there, then disconnect, reconnect and fiddle with `.gm on` and `.gm off`

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

35f3265

##### OPERATING SYSTEM:

deb9

##### MODULES:

mod-guildhouse

**Comment by BarbzYHOOL** [comment]
I feel like it screws up any phase, even for players too

**Comment by Stoabrogga** [comment]
It's the same issue like the Wintergrasp phases bug associated with the guildhouse in my opinion. I wrote a comment some time ago:
https://github.com/azerothcore/mod-guildhouse/pull/6#issuecomment-539960023

**Comment by BarbzYHOOL** [comment]
ok but i'd like to be able to reproduce the bug elsewhere without this module (because i remember having issues with phases in orgrimmar with gm mode, already reported it here and pondaveia tested) but i don't know much about phases :(

**Comment by gengarshadowball** [comment]
~Wintergrasp NPCs are visible due to some bug around hidden flags, because the way wintergrasp is coded is NPCs are loaded up on start and they get hidden or shown depending on the state of the battlefield.

**Comment by Bogir** [comment]
Install mod-guildhouse correctly and every phases start to  appears very fine

**Comment by Stoabrogga** [comment]
I'll write here the same as on Discord:

The phasemasks are necessary because creatures and gameobjects can have multiple phases at once and the players can see multiple phases using multiple auras. The guildhouse mod changes this via patch for area 876 (GM Island) in order to be able to provide a phase for each guild (otherwise only 32 different phases would be possible). This means that you are not able to use multiple phases at once on GM Island anymore, which is not needed in this case anyway. But the guildhouse does not restore the phases of the players correctly if leaving GM Island, it only restores the first one which is a problem e.g. on Wintergrasp where players can have up to 2 phase auras and so seeing 2 different phases.

**Comment by Bogir** [comment]
The question was why .gm off doesn't make NPC to disappear. Some phases can be seen by characters  from other phases. For example - some event NPC in Dalaran. Currently, the server uses phase masks by default and this is very inconvenient. It would be much simpler and more reliable to use specific phases for certain cases, for territories, for NPS or zones. If Whintergrasp battle need to use several phases for characters at the same time - it is trouble of Wintergrasp script.

**Comment by Stoabrogga** [comment]
I don't think you fully understood how phases work. I'll add here an explanation I wrote to Barbz in Discord:
Each creature/gameobject has a phasemask... which is just a bit mask combining the phases in which the creature is visible, e.g. phase 1 = 1, 2 = 2, 3 = 4, 4 = 8, 5 = 16 etc... so a creature which should be visible in phases 2 and 4 would use phasemask 2+8 = 10. You can modify your phase as GM using the command "modify phase". If you use "gm on" you automatically set your own phasemask to "PHASEMASK_ANYWHERE" (0xFFFFFFFF), so you see all phases together. For a player the phases are managed via specific auras, e.g. spell 59062 which forces the player to only see phase 7 (bit 64). This is normally handled via table "spell_area". What the patch for the guild house does is remove the ability to combine phases for area 876 (GM Island), because this would only allow 32 phases, and instead use the phasemask as actual value, which means phase 1 = 1, 2 = 2, 3 = 3, 4 = 4, 5 = 5 etc., so you potentially get 4294967295 different phases there. Concerning the bug: After leaving the guildhouse only the first phase is restored to the player, but he could have more than one phase by his auras.

**Comment by Bogir** [comment]
If you want to keep this logic - why not to use negative region for phasemasks or for phases? Bitmasks -1, -2, -4, -8  or -1,-2,-3,-4,-5,-6,-7 ? This would save the current system as it is, and add the ability to work with each phase separately. And this would not be an exception, as Talamortis suggested for the GM island zone.

**Comment by Stoabrogga** [comment]
A bitmask cannot be negative, it's just 0 and 1 combined together. Using 4 Bytes you can combine a total of 32 phases:
0000 0000 0000 0000 0000 0000 0000 0000 (0x00000000) No phase
0000 0000 0000 0000 0000 0000 0000 0001 (0x00000001) phase 1
0000 0000 0000 0000 0000 0000 0000 0010 (0x00000002) phase 2
0000 0000 0000 0000 0000 0000 0000 0011 (0x00000003) phase 1 & 2
...
1111 1111 1111 1111 1111 1111 1111 1111 (0xFFFFFFFF) All 32 phases together

**Comment by Bogir** [comment]
ok, you are right. So, negative values can be used by phases )

**Comment by BarbzYHOOL** [comment]
I think maybe this can be closed, because I noticed this only when using mod-guildhouse when missing the .patch

@Stoabrogga please, reopen it if I'm wrong
