### ISSUE TITLE
GM who list options do not seem to work at all

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/azerothcore-wotlk#2840]
##### EXPECTED BLIZZLIKE BEHAVIOUR:

These config options should work.

##### CURRENT BEHAVIOUR:

```
#
#    GM.InGMList.Level
#        Description: Maximum GM level shown in GM list (if enabled) in non-GM state (.gm off).
#        Default:     3 - (Anyone)
#                     0 - (Only players)
#                     1 - (Only moderators)
#                     2 - (Only gamemasters)

GM.InGMList.Level = 3

#
#    GM.InWhoList.Level
#        Description: Max GM level showed in who list (if visible).
#        Default:     3 - (Anyone)
#                     0 - (Only players)
#                     1 - (Only moderators)
#                     2 - (Only gamemasters)

GM.InWhoList.Level = 3
```

##### STEPS TO REPRODUCE THE PROBLEM:

1. Try to change the config from 0 to 3
2. Login with two accounts (one admin, one player) and use /who
3. Result = always the same

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

397c5d916fe1330510b1d815d23d18eaa18116a7

##### OPERATING SYSTEM:

deb9

**Comment by Kitzunu** [comment]
@h0lysp4nk didn't you test this earlier this week?

**Comment by h0lysp4nk** [comment]
@Kitzunu @BarbzYHOOL 

Yes I did, someone else earlier this week had an issue with GMs not showing up in the who list. The reason why they weren't showing up was because they set the accounts GM Level to 4.

The config options worked for me while I was testing them earlier this week but, something might've changed since then that has broken it. I can say that on my server that I'm using to do the Temple of Ahn'Qiraj rework the config options do work, I can't say for sure on the latest master branch though.

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/c0728f6e2d8c867780cf71d536c5c633bbcc03ba
