### ISSUE TITLE
I want to use azerothcore-wotlk as my server and some lnowleges want to know.

### ISSUE THREAD

**Issue by wplatform** [azerothcore/azerothcore-wotlk#2906]
1. Is The Wintergrasp available?
2. Is The Trial of the Champion available?
3. How many players can support online on one server?(4G memory)
4. How to port the trinitycore db into azerothcore-wotlk?

**Comment by Viste** [comment]
1. Yes
2. Yes
3. http://www.azerothcore.org/wiki/Memory-Usage
4. what part account and characters? Or world ?

**Comment by wplatform** [comment]
3. It seems that Trinitycore can support more users with less memory, do they make a difference in memory usage?
4. yes, I want to port the characters world account database.

**Comment by wplatform** [comment]
12.6 35.8 2248228 1447804 ?     Sl   Apr15 666:37 ./worldserver

**Comment by Viste** [comment]
>     1. It seems that Trinitycore can support more users with less memory, do they make a difference in memory usage?

its hard to explain but they have another code base and base library for threading network and etc 

>     2\. yes, I want to port the characters world account database.

you dont need to port world db to AC because in end you get broken server
characters and auth DB are almost the same you can check our wiki and correct the dump of auth and characters:
http://www.azerothcore.org/wiki/database-auth
http://www.azerothcore.org/wiki/database-characters

**Comment by LukasVolgger** [comment]
Hello @wplatform and welcome to our project. 

If you look for differences between the projects i recommend this article:
http://mangosrumors.org/trinitycore-vs-azerothcore/

For technical questions you can ask us on Discord: https://discord.gg/5wtxKH

Since this is not an issue, the ticket is closed. 
http://www.azerothcore.org/wiki/How-to-ask-for-help

**Comment by FrancescoBorzi** [comment]
You can also use the forum for discussions like this: https://github.com/azerothcore/forum
