### ISSUE TITLE
Proc Val'anyr, Hammer of Ancient Kings

### ISSUE THREAD

**Issue by Irome** [azerothcore/azerothcore-wotlk#296]
**Description**: The proc of Val'anyr, Hammer of Ancient Kings is incorrect.

http://www.wowhead.com/item=46017/valanyr-hammer-of-ancient-kings

** ** Current behavior: The buff shield, has a proc when doing any buff, even when someone with Val'anyr enters a istance.

** ** Expected behavior: The Val'anyr should not have a proc in these two cases.

** Steps to reproduce the problem **:

1. Wear the Val'anyr and try to make any buff on your PG, or on another PG.
2. Wear the Val'anyr and try to enter or exit a dungeon several times.

** AC hash / commit **: 068ac593cb2894a16f3bfa78867fd901fc3122ed

**Comment by Irome** [comment]
Missed proc shield were found in some Shaman spells. The spells that do not apply the shield are:

1. Dot applied by chain heal by 4 pcs set t10 (link items with four-piece bonus description: http://wotlk.openwow.com/item=51241
2. Earthliving Weapon (http://wotlk.openwow.com/spell=51994): the dot its not apply the shield

Read this: http://www.mmo-champion.com/threads/717698-Question-about-Heroic-Trauma?p=7877190&viewfull=1#post7877190

These 2 described procs have to proc shield, which currently does not happen.

Also on: http://www.wowhead.com/forums&topic=94136/valanyr-hammer-of-the-ancient-kings-proc-info

The shield has to proc on direct care of the player. In fact, even the healing stream player totems (http://wotlk.openwow.com/spell=58757) shield procs no, and it seems correct. Same thing for the 'ancestral awakenin (http://wotlk.openwow.com/spell=52752)

**Comment by poszer** [comment]
Tested, there are some issues having this item Equiped. Since it says  

> The shield can grow to a maximum size of 20, 000 damage absorbtion

We should add the case for it and also refresh and return to prevent replacing the aura.

C/P Info: 
The effect reads “Your healing spells have a chance to cause Blessing of Ancient Kings for 15 seconds allowing your heals to shield the target absorbing damage equal to 15% of the amount healed.”

The way this works is that when the proc happens (which is a 10% chance whenever a hot or direct spell heals, with a 45 sec internal cooldown) you gain a buff (the Blessing) on yourself. Now all of your heals for the next 15 sec cause an 8 sec damage shield. The shield stacks with itself. It includes healing done by subsequent ticks of existing hots on the target. Note that the spell has to actually heal, so hots ticking on a fully-healed target cannot cause the proc. However the shield is based on the size of the heal itself, not the amount healed – i.e. 100% overhealing will not proc the Blessing on the healer, but the shield itself includes overhealing once the Blessing is active. The shield can grow to a maximum size of 20,000 damage absorbed.

Example 1: A paladin casts Holy Light for 10K on the tank, which partially heals her. The Blessing procs, so the paladin’s Holy Light immediately causes a shield on the tank which will now absorb 1500 damage. The tank dodges the next two hits, so no damage is absorbed. The paladin then casts another heal for 8K, but only heals the tank for 600 before she is at full health. The shield is now at 2700 damage absorbed (1500 + 1200) for 8 sec.
Example 2: A druid casts Rejuv on the tank, healing her. The Blessing procs on the druid on the second tick. A shield is applied to the tank which absorbs 15% of the amount healed by that tick and each remaining tick of the Rejuv. If the druid also gets Lifebloom and Regrowth on the tank while the Blessing is up, then those ticks also contribute to the shield. If the shield goes down because the 8 sec duration expires or it absorbs that much damage, it can go up again as long as the Blessing lasts, which is 15 sec.

**Comment by sucofog** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Spells/spell_item.cpp#L1504
