### ISSUE TITLE
The player can't receive a mail when use the SOAP api to send items/ money

### ISSUE THREAD

**Issue by wplatform** [azerothcore/azerothcore-wotlk#3005]
##### SMALL DESCRIPTION:

The server SOAP is enabled and the player can't receive a mail when using the SOAP to send items/ money

##### CURRENT BEHAVIOUR:

The server SOAP is enabled and the player can't receive a mail when using the SOAP to send items/ money

##### STEPS TO REPRODUCE THE PROBLEM:

1. Enable SOAP
2. Send http command with curl

curl --user user:password--header "Content-Type: text/xml;charset=UTF-8" --header "SOAPAction: " --data '
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance" xmlns:xsd="http://www.w3.org/1999/XMLSchema" xmlns:ns1="urn:AC">
    <SOAP-ENV:Header>
    </SOAP-ENV:Header>
    <SOAP-ENV:Body>
         <ns1:executeCommand>
             <command>send item BreakingBad "appand" "appand" 51809:5 13335:1</command>
         </ns1:executeCommand>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
' -X POST http://127.0.0.1:7878/urn:AC
##### EXPECTED BLIZZLIKE BEHAVIOUR:

The player receive a mail when using the SOAP to send items/ money

3. enter the game

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

commit b429b7331d5d0eabd1835c39e0afa2ce86834ced (HEAD -> master, origin/master, origin/HEAD)
Author: AzerothCoreBot <azerothcorebot@gmail.com>
Date:   Thu Apr 30 08:07:10 2020 +0000

    Import pending SQL update file...

    Referenced commit(s): fedd6577f1c530affff4acf29c41ff7f0694e662

##### OPERATING SYSTEM:

Ubuntu 18

**Comment by NiganNi** [comment]
Good day, I have the same problem with SOAP enabled but no emails are coming. Have you solved the problem?

**Comment by Hacaw** [comment]
@FrancescoBorzi 
Is the mail system based on SOAP protocol in AzerothCore for sending and receiving items? 
Why not a simple .cpp file for the mail system ?

@wplatform
I am new to the TrinityCore, but I will try to reproduce it on my config.

**Comment by Hacaw** [comment]
CONCLUSION
---
I can reproduce this issue, but...

@wplatform:
- Please correctly format the expected behavior and reproduction steps.
- Please format currently the body of the soap-request, you need to close some brackets.

TESTING
---
Used testing steps mentioned by author.
I also tried using Postman, but I keep getting a socket hang up.
Using curl as suggested by the author, but got curl (52) error, empty response.
`
curl --user test1:a --header "Content-Type: text/xml;charset=UTF-8" --header "SOAPAction: " --data '
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/1999/XMLSchema-instance" xmlns:xsd="http://www.w3.org/1999/XMLSchema" xmlns:ns1="urn:AC">
<SOAP-ENV:Header>
</SOAP-ENV:Header>
<SOAP-ENV:Body>
<ns1:executeCommand>
send item Magne "appand" "appand" 51809:5 13335:1
</ns1:executeCommand>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
' -X POST http://127.0.0.1:7878/urn:AC
`

The command inside the soap-body is working if run from the wow-client.

CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by Helias** [comment]
@Hacaw https://stackoverflow.com/questions/59382665/how-to-send-commands-using-soap-to-azerothcore-worldserver-console

**Comment by Hacaw** [comment]
Thanks @Helias I already found this, but didn't want to add perl or php scripts to run and prefered the curl solution of the author.

**Comment by Helias** [comment]
You can even add the CURL solution as answer of that stackoverflow question if you make it works

**Comment by Kitzunu** [comment]
works. make sure your commands are correct
