### ISSUE TITLE
(DB/Quest): What Illidan Wants, Illidan Gets...

### ISSUE THREAD

**Issue by TheWatchingI** [azerothcore/azerothcore-wotlk#3010]
##### SMALL DESCRIPTION:
There are two mobs besides the quest target, which aren't supposed to be there and make the quest impossible.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
During the quest (https://www.wowhead.com/quest=10577/what-illidan-wants-illidan-gets) you will disguise yourself as a blood elf, which is supposed to work on every mob in that area, except dragonhawks. In your disguise you will need to speak with Grand Commander Ruusk, who is a high level elite mob, flanked by 2 bodyguards, which are elite too. https://youtu.be/qgp-f_nwd8w?t=30s

##### CURRENT BEHAVIOUR:
Ruusk has two additional bodyguards, which are called "Shadowmoon Retainer" and shouldn't be there. The mobs are part of another, unrelated quest in a different location (https://www.wowhead.com/npc=22102/shadowmoon-retainer). The disguise doesn't work on them and since every fight breaks the disguise, it isn't possible to go close to Ruusk without having to fight him too.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Just go to Ruusk and see, if the two extra mobs are there. https://www.wowhead.com/npc=20563/grand-commander-ruusk
2. Additionally you might try to put on the disguise, to see, if it works on the two  Shadowmoon Retainer (https://www.wowhead.com/item=30639/blood-elf-disguise)

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
cdf518a

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
ah-bot
morphsummon
solo-lfg

**Comment by Hacaw** [comment]
CONCLUSION
---
I can reproduce this issue.

TESTING
---
Used testing steps mentioned by author.

Watching the video posted by the author those 2 extra mobs shouldn't be there, maybe we should move them where they are related instead of deleting them at all.

![image](https://user-images.githubusercontent.com/6963500/102016629-8f9a1680-3d6a-11eb-92ae-fad0b881b5f5.png)


CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by Gultask** [comment]
Fixed by: https://github.com/azerothcore/azerothcore-wotlk/pull/15112
