### ISSUE TITLE
Minor NPCs bugs

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#3026]
##### SMALL DESCRIPTION:

There's something wrong with the pnj that's generating rage when it shouldn't.

![WoWScrnShot_051120_004443](https://user-images.githubusercontent.com/31663279/81662227-8e53e480-943d-11ea-893a-889c8b968c85.jpg)

Source : https://tbc.wowhead.com/quest=6/bounty-on-garrick-padfoot
https://tbc.wowhead.com/npc=103/garrick-padfoot

Source WoW Classic : https://youtu.be/Tss_e796d_U?t=132
https://youtu.be/X00FCqp3s_I?t=67
https://youtu.be/leCrXXRn7UA?t=73

Source TBC Classic : https://youtu.be/2QqBzUidj-Q?t=444

**NOTA : THIS SECOND ONE IS NOT A BUG** /  The second, concerning the guard, the waypoints are missing.
![WoWScrnShot_051120_005102](https://user-images.githubusercontent.com/31663279/81662234-8f851180-943d-11ea-8d11-d609976f2d05.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Dont generate rage

**NOTA : THIS SECOND ONE IS NOT A BUG** / Have waypoint

##### STEPS TO REPRODUCE THE PROBLEM:

1. Human start zone
2. and entrance of SW
3. 

##### BRANCH(ES):

master

**Comment by Helias** [comment]
is stil valid?

**Comment by Maurowin** [comment]
yes stiff here

**Comment by Hacaw** [comment]
CONCLUSION
---
1. I can reproduce this issue.
2. I don't find the npc(probably because I have the english client).

@Maurowin I have some suggestions:
- please use some npc ids so I can easily teleport to them 
- please use map coords for locations / or taxi nodes
- maybe you should update the title of this issue with: Minor Stormwind NPC bugs ?

TESTING
---
Used testing steps mentioned by author.

CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by Maurowin** [comment]
The second one is blizzlike, this guard dont move too in Shadowland retail.

**Comment by T1ti** [comment]
shadowlands retail is not a reference, the closest is TBC classic and then Classic, Blizz reworked every zones and core mechanics in cata+

But I verified this on Classic, and he also stands still, this is correct behavior

**Comment by Si1ker** [comment]
no source for the first point and point 2 has been already discarded.
