### ISSUE TITLE
Unable to Compile AC

### ISSUE THREAD

**Issue by starrheld** [azerothcore/azerothcore-wotlk#319]
Tried several times, I know the requirements of the installation. 
Tried it with Ubuntu 16.04 and below, fresh installations all the time... stops at around 60 %...

My server is good with 16 GB RAM / 8 Cores and so on...

root@ubuntu-16gb-lon1-01:/home/azerothcore/azerothcore/build# cmake ../ -DCMAKE_                                                         INSTALL_PREFIX=/home/azerothcore/azeroth-server/ -DTOOLS=0 -DSCRIPTS=1
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Running cmake hook: AFTER_LOAD_CONF
No hooks registered for AFTER_LOAD_CONF
-- Detected 64-bit platform
-- UNIX: Using jemalloc
-- UNIX: Using default configuration directory
-- UNIX: Using default library directory
-- UNIX: Configuring uninstall target
-- UNIX: Created uninstall target
-- UNIX: Detected compiler: /usr/bin/cc
-- GCC: Enabled c++11 support
-- GCC: Enabled C99 support
-- GCC: SFMT enabled, SSE2 flags forced
-- Found ACE library: /usr/lib/libACE.so
-- Found ACE headers: /usr/include
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/                                                         libcrypto.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found Readline library: /usr/lib/x86_64-linux-gnu/libreadline.so
-- Include dir is: /usr/include
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found git binary : /usr/bin/git

* AzerothCore revision   : a655ddcbc02f 2017-01-06 13:36:09 +0100 (master branch                                                         )
* AzerothCore buildtype  : Release

* Install core to        : /home/azerothcore/azeroth-server
* Install libraries to   : /home/azerothcore/azeroth-server/lib
* Install configs to     : /home/azerothcore/azeroth-server/etc

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (default)
* Build map/vmap tools   : No  (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Use GIT revision hash  : Yes

Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD
Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
Running cmake hook: AFTER_AUTHSERVER_CMAKE
No hooks registered for AFTER_AUTHSERVER_CMAKE
-- SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: World
  -> Prepared: Outdoor PVP Zones
  -> Prepared: Eastern Kingdoms
  -> Prepared: Kalimdor
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: Events
  -> Prepared: Pet
-- SCRIPT PREPARATION COMPLETE

Running cmake hook: AFTER_WORLDSERVER_CMAKE
No hooks registered for AFTER_WORLDSERVER_CMAKE
Running cmake hook: AFTER_SRC_LOAD
No hooks registered for AFTER_SRC_LOAD
-- Configuring done
-- Generating done
-- Build files have been written to: /home/azerothcore/azerothcore/build

And I get this...

/home/azerothcore/azerothcore/src/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp: In member function ‘virtual void boss_shade_of_aran::boss_aranAI::UpdateAI(uint32)’:
/home/azerothcore/azerothcore/src/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp:399:61: error: invalid conversion from ‘int’ to ‘Unit*’ [-fpermissive]
                     Unit* pTarget = (SELECT_TARGET_RANDOM, 0);
                                                             ^
/home/azerothcore/azerothcore/src/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp:414:61: error: invalid conversion from ‘int’ to ‘Unit*’ [-fpermissive]
                     Unit* pTarget = (SELECT_TARGET_RANDOM, 0);
                                                             ^
/home/azerothcore/azerothcore/src/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp:429:61: error: invalid conversion from ‘int’ to ‘Unit*’ [-fpermissive]
                     Unit* pTarget = (SELECT_TARGET_RANDOM, 0);
                                                             ^
/home/azerothcore/azerothcore/src/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp:444:61: error: invalid conversion from ‘int’ to ‘Unit*’ [-fpermissive]
                     Unit* pTarget = (SELECT_TARGET_RANDOM, 0);
                                                             ^
[ 61%] Building CXX object src/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Karazhan/boss_netherspite.cpp.o
[ 61%] Building CXX object src/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Karazhan/boss_maiden_of_virtue.cpp.o
[ 61%] Building CXX object src/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Karazhan/boss_midnight.cpp.o
[ 61%] Building CXX object src/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp.o
[ 61%] Building CXX object src/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Karazhan/bosses_opera.cpp.o
[ 61%] Building CXX object src/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Karazhan/boss_moroes.cpp.o
src/scripts/CMakeFiles/scripts.dir/build.make:4742: recipe for target 'src/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp.o' failed
make[2]: *** [src/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1223: recipe for target 'src/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/scripts/CMakeFiles/scripts.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@ubuntu-16gb-lon1-01:/home/azerothcore/azerothcore/build#

**Comment by talamortis** [comment]
please input karazhan rework then try that

**Comment by starrheld** [comment]
And how is that done easily? With git? And your pull 316?

**Comment by ShinDarth** [comment]
[How to test an open Pull Request](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-test-a-pull-request)

**Comment by talamortis** [comment]
yes it's pr 316

**Comment by talamortis** [comment]
@starrheld wanted tested and if compliled correctly please test the full PR, and then comment so we can merge into master

**Comment by starrheld** [comment]
Lol, I feel really stupid

git remote add talamortis https://github.com/talamortis/azerothcore-wotlk.git
git fetch talamortis
git checkout -b talamortis_master talamortis/master

?
Did this and trying to compile now

**Comment by talamortis** [comment]
ur getting my fork, you dont want to do that, u want to get my branch in azeroth it self. sorry i dont know how to use git myself

**Comment by talamortis** [comment]
i think try that but not 100% sure

git remote add talamortis https://github.com/azerothcore/azerothcore-wotlk.git
git fetch azerothcore
git checkout -b azerothcore_karazhan_reowrk azerothcore/karazhan_rework

**Comment by starrheld** [comment]
Bare with me

**Comment by starrheld** [comment]
[100%] Linking CXX executable worldserver
[100%] Built target worldserver

git fetch origin pull/316/head:MASTER
git checkout MASTER 

... think that did it??
lol

**Comment by talamortis** [comment]
so it compiled correctly?

**Comment by starrheld** [comment]
Yes

**Comment by talamortis** [comment]
can you test the PR then I can merge

**Comment by starrheld** [comment]
Yes, will try to start the worldserver and everything! Hang on will update soon

**Comment by Rushor** [comment]
better comoile tc and work there

**Comment by starrheld** [comment]
Works great @talamortis !

**Comment by talamortis** [comment]
tested karazhan?

**Comment by starrheld** [comment]
Yes a little

**Comment by ShinDarth** [comment]
@starrheld it would be nice if you can give your feedback in the PR discussion

**Comment by starrheld** [comment]
Trying to compile today again, on a new platform

c++: internal compiler error: Segmentation fault (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
modules/worldengine/nucleus/src/CMakeFiles/shared.dir/build.make:62: recipe for target 'modules/worldengine/nucleus/src/CMakeFiles/shared.dir/Configuration/Config.cpp.o' failed
make[2]: *** [modules/worldengine/nucleus/src/CMakeFiles/shared.dir/Configuration/Config.cpp.o] Error 4
CMakeFiles/Makefile2:498: recipe for target 'modules/worldengine/nucleus/src/CMakeFiles/shared.dir/all' failed
make[1]: *** [modules/worldengine/nucleus/src/CMakeFiles/shared.dir/all] Error 2
Makefile:127: recipe for target 'all' failed

Any info on this?

**Comment by talamortis** [comment]
nothing has changed since last time you reported this issue maybe your missing programs or files?

**Comment by starrheld** [comment]
Could it be due to the fact that I'm using:
Ubuntu Server 16.10 "Yakkety Yak"?

**Comment by talamortis** [comment]
I don't know m8 I use Windows I don't know how to use Linux

**Comment by starrheld** [comment]
Tried with 16.04 and same

modules/worldengine/nucleus/src/CMakeFiles/shared.dir/build.make:62: recipe for target 'modules/worldengine/nucleus/src/CMakeFiles/shared.dir/Configuration/Config.cpp.o' failed
make[2]: *** [modules/worldengine/nucleus/src/CMakeFiles/shared.dir/Configuration/Config.cpp.o] Error 4
CMakeFiles/Makefile2:498: recipe for target 'modules/worldengine/nucleus/src/CMakeFiles/shared.dir/all' failed
make[1]: *** [modules/worldengine/nucleus/src/CMakeFiles/shared.dir/all] Error 2

**Comment by talamortis** [comment]
try reinstalling the required files I can't really help with this issue as I don't have Linux

**Comment by starrheld** [comment]
Case closed, had to update my kernel.

**Comment by ss958** [comment]
Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD
Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
Running cmake hook: AFTER_AUTHSERVER_CMAKE
No hooks registered for AFTER_AUTHSERVER_CMAKE

Have you solved these questions? How do you do it?

**Comment by Inifield** [comment]
those are not errors

**Comment by ss958** [comment]
But because my compilation has always been a failure.

**Comment by ss958** [comment]
CMake Deprecation Warning at CMakeLists.txt:16 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Running cmake hook: AFTER_LOAD_CONF
No hooks registered for AFTER_LOAD_CONF
Detected 64-bit platform
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled extended object-support for debug-compiles
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled INTMAX_MAX warnings
MSVC: Disabled generic compiletime warnings
Using installation path for configuration files
Found MySQL library: F:/MySQL/lib/libmysql.lib
Found MySQL headers: F:/MySQL/include
Found git binary : F:/Git/cmd/git.exe

* AzerothCore revision   : 445b88563f07+ 2017-06-23 15:03:51 +0200 (master branch)

* Install core to        : C:/Program Files/AzerothCore
* Install configs to     : C:/Program Files/AzerothCore

* Build world/auth       : Yes (default)
* Build with scripts     : Yes (default)
* Build map/vmap tools   : No  (default)
* Build core w/PCH       : Yes (default)
* Build scripts w/PCH    : Yes (default)
* Show compile-warnings  : No  (default)
* Use coreside debug     : No  (default)
* Use MySQL sourcetree   : No
* Use GIT revision hash  : Yes
* Disable extra features     : No  (default)
* Disable vmap DisableMgr checks     : No  (default)

Loading module: modules/worldchat
Loading module: modules/player_announcer
Loading module: modules/mod-transmog-master
Loading module: modules/mod-duelreset-master
-- DUEL RESET CONFIGURED --
Loading module: modules/mod-anticheat-master
Loading module: modules/Boss_Announcer
Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD
Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
Running cmake hook: AFTER_AUTHSERVER_CMAKE
No hooks registered for AFTER_AUTHSERVER_CMAKE
Running cmake hook: BEFORE_SCRIPTS_LIBRARY
No hooks registered for BEFORE_SCRIPTS_LIBRARY
SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: Custom
  -> Prepared: World
  -> Prepared: Outdoor PVP Zones
  -> Prepared: Eastern Kingdoms
  -> Prepared: Kalimdor
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: Events
  -> Prepared: Pet
SCRIPT PREPARATION COMPLETE

Running cmake hook: AFTER_WORLDSERVER_CMAKE
Including F:/wow/Azerothcore/azerothcore-wotlk/modules/mod-transmog-master/src/cmake/after_ws.cmake
Including F:/wow/Azerothcore/azerothcore-wotlk/modules/mod-duelreset-master/src/cmake/after_ws_install.cmake
Including F:/wow/Azerothcore/azerothcore-wotlk/modules/mod-anticheat-master/src/cmake/after_ws_install.cmake
Running cmake hook: AFTER_SRC_LOAD
No hooks registered for AFTER_SRC_LOAD
Configuring done
Generating done
-------------------------------------------------------------------------------------------------------
But because my compilation has always been a failure.

**Comment by talamortis** [comment]
Configuring done
Generating done

looks like it works problem is not with Cmake make sure you followed the install tutorial on the wiki.
