### ISSUE TITLE
(DB/Quest): Re-Cursive

### ISSUE THREAD

**Issue by wowissues** [azerothcore/azerothcore-wotlk#3204]
https://www.wowhead.com/quest=11712/re-cursive

**SMALL DESCRIPTION**:
For each use, 2 is counted at once, not 1.

**STEPS TO REPRODUCE PROBLEM**:
1. `.q add 11712`
2. `.tele borean tundra`

**BRANCH(ES)**: master

**AC HASH/COMMIT**: AzerothCore rev. aeab506+ 2020-07-03

**OPERATING SYSTEM**: Debian 10

**MODULES**: Anticheat, ResetDuel, CFBG, Transmog, PvPTitles

**Comment by Hacaw** [comment]
@FrancescoBorzi please update the labels of this issue, since a solution is already provided.
@grimgravy can you please tell me which insert line or column value is fixing the progress of this quest ? I think I found a similar quest with the similar bug, and maybe the same fix could be applied.

I can reproduce this issue on my version.
![image](https://user-images.githubusercontent.com/6963500/101534931-87279180-39a0-11eb-98fa-34bd038381ff.png)


TESTING
---
Used testing steps mentioned by author.

SPEC
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10+Docker
MODULES / CUSTOMIZATION: None
