### ISSUE TITLE
vmap4extractor extractor problem - Linux

### ISSUE THREAD

**Issue by darvinrivera** [azerothcore/azerothcore-wotlk#337]
I compile the source in Debian Jessie. When i run ./vmap4extractor i get this error:

Extracting GameObject models...Extracting World\Wmo\Band\Final_Stage.wmo
No such file.
Couldn't open RootWmo!!!
Done!

any solution?

**Comment by Inifield** [comment]
it's known, it doesn't matter

**Comment by talamortis** [comment]
Vmaps does not exstract just yet please use the ones on the Wiki site.

**Comment by Inifield** [comment]
All extractors works fine, it's not a critical error

**Comment by ArthasCore** [comment]
Map file '/home/game-server/tools/data/maps/0004331.map' is from an incompatible clientversion. Please recreate using the mapextractor. Wiki site.

**Comment by d3tr0l** [comment]
> 
> 
> Vmaps does not exstract just yet please use the ones on the Wiki site.





> 
> 
> All extractors works fine, it's not a critical error

Well, i tested it today, fresh compile. And what to say...the extractors are stuck at the error mentioned at the begining of this issue #337 . The error is still here. So, talamortis, since the maps are in the wiki page, updated...how anyone managed to extract them in order to even upload them? I do not want to sound mean. But, this issue is kinda frustrating. I believe everyone using the core would love to have working extractors to get their own fresh (even if it might be the same as on wiki page) data. 

I have this issue too, windows actually. Reopen please?

**Comment by Kingswow** [comment]
confirm !

**Comment by Kitzunu** [comment]
Just saying "confirm" is useless. Please add the rev you are on

**Comment by Helias** [comment]
I think he solved the issue
