### ISSUE TITLE
Alive Creteus is standing on a dead Creteus

### ISSUE THREAD

**Issue by felwyn** [azerothcore/azerothcore-wotlk#3373]
Alive Creteus is standing on dead Creteus

Alice Creteus DB GUID is 1976493

Dead Creteus DB GUID is 1976574

##### CURRENT BEHAVIOUR:

Alive Creteus is standing on dead Creteus. https://i.imgur.com/mKyl6To.jpg

Creatures are not very positioned. https://i.imgur.com/4qkmGyj.jpg

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This bug appears in GM Mode ON only! If you disable GM Mode the NPCs will disappear entirely.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tel StormPeaks
2. Go towards the Southwestern End of the big hole
3. .gm on

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/33613254351f7715afbd5adc5186a1e45853083a

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

No

##### OTHER CUSTOMIZATIONS:

No

**Comment by Helias** [comment]
This is because they are in 2 different phasemask.
In phasemask 4 there are 2 giant with Creteus dead.
In phasemask 2 there is only Creteus.

It makes sense, this is not a bug.

to change phase just use `.mod phase 2` targeting yourself (or no-one).

with `.gm on` you can see all phase at once, but with gm off
