### ISSUE TITLE
Professor Putricide - Regurgitated Ooze

### ISSUE THREAD

**Issue by mnclaras** [azerothcore/azerothcore-wotlk#3533]
##### CURRENT BEHAVIOUR:
Abomination -> [Regurgitated Ooze](https://www.wowhead.com/spell=70539/regurgitated-ooze) Spell (slow down spell) can be used on multiple times without cooldown. It must be 1 second. This is a problem because if you have enough energy to use it two times, and use the spell two or more times, it will be casted twice.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Regurgitated Ooze should have cooldown between casts: 1 second.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Enter with 2 characters on ICC and reach Professor Putricide.
2. Attack the boss with one character and take abomination with the other.
3. Take 90+ energy with the abomination.
4. Cast Regurgitated Ooze and you will notice that it does not have Cooldown. You can basically spam it and drain all your energy

##### AC/HASH COMMIT
[e19a217](https://github.com/azerothcore/azerothcore-wotlk/commit/e9bce8a0f4544c87a6ce00d7123a634802f12800)

**Comment by Si1ker** [comment]
@mnclaras  Provide proof/evidence/source/reference for your blizzlike behavior, thanks.

**Comment by mnclaras** [comment]
> @mnclaras Provide proof/evidence/source/reference for your blizzlike behavior, thanks.

Did you tested it? Just take 90+ energy and spam the spell. You will notice that is casted without cooldown.

Source/Reference: The spell that I've linked says the following:

Cost: 45 Energy
Cast time: Instant
**Cooldown: 1 second**
GCD: 0 seconds

**Comment by Si1ker** [comment]
@Kitzunu  Seems a spell.dbc thing, what do u think here?

**Comment by Kitzunu** [comment]
Don't trust Wowhead. It is up-to-date with current retail.

this is a snapshot of late WotLK https://web.archive.org/web/20100921095013/https://www.wowhead.com/spell=70539/regurgitated-ooze which gives us this info

Cost 45 energy
50 yards (Extended)
Instant
n/a

**Comment by Kitzunu** [comment]
What would be useful is a video from wotlk showing the 1s cd

**Comment by Si1ker** [comment]
@Kitzunu Thanks!

@mnclaras Look at the info below, this webpage goes with the 3.3.5a information instead of BFA xpac as wowhead does:
https://db.rising-gods.de/?spell=70539

![image](https://user-images.githubusercontent.com/61223313/95018138-f1c3f600-061a-11eb-8a7d-76a43cd75ccb.png)

**Comment by Kitzunu** [comment]
Also, don't trust private server databases :D

**Comment by Si1ker** [comment]
Yeap, also true, basically open issues/PRs with proofs in video from retail (2008/20009)

**Comment by Knindzagxg** [comment]
Spell should have 1sec cooldown to prevent spamming.
Cast itself is instant, but there is cooldown between casts.

**Comment by Knindzagxg** [comment]
Need to check more into this.
Looks like it's missing GCD while in Abbo, which is totally weird.

**Comment by Si1ker** [comment]
Thanks @Knindzagxg 

@Kitzunu I was speaking with Knidza about this and there's one point here.. the GCD which anything should have. There are multiple sources in which it does not have the GDC but it has its own CD of 1 second, and then other examples where it does not have CD but GCD

Proof 1:
https://db.rising-gods.de/?spell=70539
![image](https://user-images.githubusercontent.com/61223313/95022097-4f177180-0632-11eb-880f-1e53cc37e5b7.png)

http://wotlk.cavernoftime.com/spell=70539
![image](https://user-images.githubusercontent.com/61223313/95022142-90a81c80-0632-11eb-98e9-aba68fb90ae3.png)


In-game:
![image](https://user-images.githubusercontent.com/61223313/95022249-3bb8d600-0633-11eb-856f-28ec9188a78f.png)



Proof 2:
https://www.youtube.com/watch?v=A4m8A7U-enQ
(1:50)
Look how the abbo is not spamming it like crazy

================

To me, is a yes, if anyone else wants to give the material in order to confirm or discard, is totally welcome. 🐱 
Nobody is looking to prove themself right, we only want blizzlike stuff.

**Comment by Kitzunu** [comment]
Proof 1 & 2 is just DBC data, so yes. I never said it was wrong, I also thought it should have a gcd/cd I merely pointed out that wowhead is not a good source :)

**Comment by Si1ker** [comment]
Right, well take only the video from retail  :, )

**Comment by Kitzunu** [comment]
dbc good too tho, as Long as it is not edited x)

**Comment by Goatform** [comment]
Tested it myself and I couldn't reproduce the bug, it has a 1-sec cooldown. Did you maybe use .cheat cooldown as you were testing?

**Comment by Kitzunu** [comment]
Cannot reproduce
