### ISSUE TITLE
[Trinket] The General's Heart

### ISSUE THREAD

**Issue by mnclaras** [azerothcore/azerothcore-wotlk#3544]
##### CURRENT BEHAVIOUR:
[This Trinket](http://wotlk.cavernoftime.com/item=45507) applies [The General's Heart](http://wotlk.cavernoftime.com/spell=64764) Spell, which should reduce the amount of damage received by 205 of each attack up to 5200 absorbed damage in the next 10 seconds (with 5% proc it activates [The General's Heart](http://wotlk.cavernoftime.com/spell=64765)), is absorbing 5200 damage directly, and not 205 on each attack.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
It should reduce the amount of damage received by 205 of each attack, up to 5200.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Duel a player with the trinket equipped.
2. Attack him until the trinket procs.
3. Do any damage superior to 205 and see that all damage tha exceeds that quantity is also absorbed. For example, if you do a Hit of 4205 damage, it should do 4205-205=4000, but the trinket is absorbing all. You can view it on Combat Log. The next attacks will be absorbed until enemy receives 5200 damage.

##### AC/HASH COMMIT
[e19a217](https://github.com/azerothcore/azerothcore-wotlk/commit/e9bce8a0f4544c87a6ce00d7123a634802f12800)

**Comment by Hacaw** [comment]
I cannot confirm this issue reproduces on the way you described, but there is definitely an issue, since this is a 80 item trinket it would be cool to have it fixed since it's one of the best tank trinkets.

TESTING
---
I created 2 characters and put them to duel.
Once the trinket activated, I did a .damage 5000 to see if everything was absorbed and it was not absorbed 100%. 
I haven't found anywhere reliable that this buff should be stackable, it seems it's pure absorb. Why ? Check second image, with a trinket that is a lower version of the epic one. It absorbs each time the damage mentioned.

combat-log: http://wotlk.cavernoftime.com/item=45507
![image](https://user-images.githubusercontent.com/6963500/101393826-5bd57180-38d0-11eb-9619-0dbdfb990aa7.png)

combat-log: https://wotlkdb.com/?item=37220
![image](https://user-images.githubusercontent.com/6963500/101394039-a525c100-38d0-11eb-844d-cf8660fb2e88.png)


SPEC
---
COMMIT: 920f19f
OPERATING SYSTEM: Win10+Docker
MODULES / CUSTOMIZATION: None

**Comment by FrancescoBorzi** [comment]
@Hacaw thanks for checking this. Do you think it's somewhat related with the original issue or maybe this deserves a separate repo?

**Comment by Hacaw** [comment]
> @Hacaw thanks for checking this. Do you think it's somewhat related with the original issue or maybe this deserves a separate repo?

I'd say let's continue investigating here the issue, but update the description of it (current/expected) behavior and strikethrough the old one, since something is fishy.

Also, maybe someone more experienced whom should know or provide the real expected behavior of the item would want to share his opinion.

My opinion is that this item should behave like gossamer.

**Comment by Hacaw** [comment]
> > @Hacaw thanks for checking this. Do you think it's somewhat related with the original issue or maybe this deserves a separate repo?
> 
> @FrancescoBorzi  I'd say let's continue investigating here the issue, but update the description of it (current/expected) behavior and strikethrough the old one, since something is fishy.
> 
> Also, maybe someone more experienced whom should know or provide the real expected behavior of the item would want to share his opinion.
> 
> My opinion is that this item should behave like gossamer.
