### ISSUE TITLE
[Quest] "Crowleg" Dan

### ISSUE THREAD

**Issue by LukasVolgger** [azerothcore/azerothcore-wotlk#3675]
##### CURRENT BEHAVIOUR:

- You have to confront "Crowleg" Dan by using a the following gossip and the fight should start, but it does nothing.

![image](https://user-images.githubusercontent.com/55922592/98726607-04a6b480-2397-11eb-9fdf-a1176f61d8cf.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

YouTube Video from 2008: https://www.youtube.com/watch?v=mqwZeSVjO7I&ab_channel=wtbblue

- After clicking the gossip the fight should start as shown in the video

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 108170
2. .q rem 11479 & .q a 11479
3. use the gossip and see that nothing happens

##### AC HASH/COMMIT:

AzerothCore rev. 9a9308afd16a+ 2020-11-04 16:30:40 +0000 (master branch) (Win64, Release)

##### OPERATING SYSTEM:

Windows 10 Pro x64

##### MODULES:

- Auctionhouse Bot
- Autobalance
- Solo LFG

##### OTHER CUSTOMIZATIONS:

None

**Comment by Hacaw** [comment]
CONCLUSION
---
I can partialy reproduce this issue.
@LukasVolgger it does nothing if you have .gm on
But I cannot start the chain quest, even with the first quest, since all of them act like enemies and do not become neutral.
Is there any reputation needed to start the hain ?

https://www.wowhead.com/quest=11434/forgotten-treasure

TESTING
---
Used testing steps mentioned by author.

CONFIG
---
COMMIT: 1b156ef7
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by LukasVolgger** [comment]
Try 

.q a 11509 

& 

.q c11509

**Comment by Hacaw** [comment]
@LukasVolgger I know these commands, but I can't start the chain as a normal player with gm off.

**Comment by LukasVolgger** [comment]
It's a different quest to be friendly wirh that NPCs

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/4030
