### ISSUE TITLE
Core: Rested bonus persists outside of inn/capitals [$15]

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#3712]
Reported by @Maurowin 
##### CURRENT BEHAVIOUR:

Currently if you exit the inn or a capital city you will still store up the rest.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When you leave the inn or capital city you should no longer store up rest.
When you are resting it is displayed like this on your character image
![image](https://user-images.githubusercontent.com/24550914/99258671-35fd0580-2819-11eb-8737-5c49b335963d.png)
https://wowwiki.fandom.com/wiki/Rest?oldid=2331121

This can clearly be shown here https://www.youtube.com/watch?v=q9ufWJOlCrQ

##### STEPS TO REPRODUCE THE PROBLEM:

1. Walk into an inn / Capital
2. Walk out and see that the rest will continue to store up

##### OPERATING SYSTEM:

W10

**Comment by Maurowin** [comment]
Confirm. More precision, you will continue to store up during few seconds like +-30sec (random). The "zzz" mark staying too few seconds.

**Comment by FrancescoBorzi** [comment]
was this bug always there?

**Comment by Kitzunu** [comment]
Yea it was reported over a year I go I think but I closed it back then https://github.com/azerothcore/azerothcore-wotlk/issues/671

**Comment by Helias** [comment]
@Kitzunu claim the bounty if you didn't

**Comment by BarbzYHOOL** [comment]
Alright, i'll show you how to debug an issue...

so... i thought maybe there is a deep bug (as I told you @Kitzunu in private message) and i did more tests in the Ratchet Inn

Basically, the areatrigger for the Inn is 30 radius. (prob the same on every inn?)
Actually, in the code, it doesn't remove the "zzzz" when you leave the Inn's areatrigger radius, it removes the "zzzz" you leave the "area" as in `UpdateArea()` and THEN it checks if you are inside the inn's radius. I don't have any idea what is considered an Area or not sadly.
So when I leave the Inn, the UpdateArea() function triggers, but I'm still INSIDE the inn's radius.

So basically I get this when it doesn't remove the "zzzz":
```
trigger radius: 30.000000
distance to inn: 27.280859
```

And when it correctly removes the "zzzz" (example, you teleport out of the zone or run very fast), of course "distance to inn" is > 30.

How to make the inn work ingame? that's very simple, you .mod speed 10, and you run as fast as you can to get out and you jump before hitting the area trigger of the inn (to know where it is, you simply move slowly step by step near the inn and when you have "zzzz" on your portrait it means you're in).
You can also simply go to the Ratchet's inn, then you type `.tele ratchet` and the "zzzz" will disappear.

Now further researches show me that the UpdateArea() happens twice (sometimes) when you leave an Inn, like the crossroads' inn. That's because the following function UpdateZone() triggers UpdateArea(). Not sure how performant this is but it probably can be improved.

Another example, when you fiddle with the gm mode, it triggers UpdateArea, why?? makes no sense to me:
```
        // restore FFA PvP area state, remove not allowed for GM mounts
        UpdateArea(m_areaUpdateId);
```
so to restore the FFA pvp flag on the player, you run the entire function?? Imo, it should be divided into smaller functions.

Anyway, when you leave an inn, you trigger UpdateZone() which triggers UpdateArea. But you also trigger UpdateArea. that's why it happens twice but it happens all at the same time and you're still inside the inn's radius (if you get out of the inn by walking at normal speed)

This function triggers the AreaTrigger distance check when you ENTER the inn:
```void WorldSession::HandleAreaTriggerOpcode(WorldPacket& recv_data)```
I'm not an expert but i'm 99.9% sure this is triggered by the client sending an opcode to the server. The client perfectly knows when you are inside an inn's radius.

The server, however, should detect the exact moment when the player leaves the inn's radius. Actually, it's a HACK, it is added in the UpdateArea() check and that's why it's extremely inconsistent.

@Kitzunu can you tell me what is the trinitycore commit that inspired you? From what i've seen, the UpdateArea is triggered inside the Player::Update(), so i'm thinking that we should test the areatrigger radius in Player::Update() as you tried here, but i'm really not sure how to proceed. I gave you a lot of information, it's not just copy and paste from TC that will resolve that imo.

**Comment by Kitzunu** [comment]
A commit didnt, I saw the code.
But they have refactored the whole rested system and I dont know which commit it is. but you probably right ^^

**Comment by BarbzYHOOL** [comment]
https://github.com/TrinityCore/TrinityCore/pull/15327/files can help
