### ISSUE TITLE
[Core] Applying glyphs with dual spec

### ISSUE THREAD

**Issue by aradep** [azerothcore/azerothcore-wotlk#3772]
##### CURRENT BEHAVIOUR:
Players are sometimes prevented from inscribing the same Glyph into both specs.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Create a character, level to 80, learn Dual Talent Specialization.
3. Get 2x of the same glyph.
4. Apply one glyph to first spec.
5. Activate secondary specialization.
6. Apply other glyph to second spec.

##### EXTRA NOTES:
[Video](https://www.youtube.com/watch?v=i7ha0Wx4RuI)

Was fixed once in the past
https://github.com/azerothcore/azerothcore-wotlk/commit/562833c9d6959a3f31578c1a9434a06ea3e1bf0f

Also found this from MaNGOS.
https://github.com/mangos/MaNGOS/commit/00cc0e3b5c0b3fc107aba71a84e5dabda00dbf55

.
##### AC HASH/COMMIT:
b9c7874

##### OPERATING SYSTEM: 
Win 10 + Docker

##### MODULES: 
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Hacaw** [comment]
I can confirm this is still an issue, and probably should be considered an almost game breaking issue, since some minor glyphs are chosen for both specs, and it's probably applicable to all classes.

I have created an warrior level 80, learn dual-spec from trainer.

![image](https://user-images.githubusercontent.com/6963500/101195201-be780480-3667-11eb-9daf-acb95e4140ac.png)
![image](https://user-images.githubusercontent.com/6963500/101195231-c8016c80-3667-11eb-835b-8804d41b3c2b.png)


**COMMIT**: 920f19fa
**OPERATING SYSTEM:** Win10+Docker
**MODULES / CUSTOMIZATION:** None

**Comment by aradep** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/7162
