### ISSUE TITLE
[Talent] Demonic Pact stacking behaviour

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#3783]
##### CURRENT BEHAVIOUR:
In its current state, the [Demonic Pact](https://wotlkdb.com/?spell=47240) stacks with itself:

If Demonic pact procs from the felguard critical strike, it does correctly increase the spell power for party and raid members. However, if it procs again while Demonic Pact is already up, it a adds another 10% (assuming 5/5 talents) on top of the spell power gained from the buff. This goes on indefinitely until the gain is too small to grant another 1 SP.

For example, a toon with 1037 spell power unbuffed will have 1141 SP after the first procc of demonic pact, 1152 after the second proc and 1153 after the third.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Buffs should'nt award bonus stats based on themselves at all. The toon should stay at 1141 SP even when subsequent procs happen.

##### STEPS TO REPRODUCE THE PROBLEM:
- Have a warlock with some spell damage gear. Spec the [Demonic Pact](https://wotlkdb.com/?spell=47240) talent
- Summon a felguard and let it attack a dummy
- Check your spellpower on each proc of [Demonic Pact](https://wotlkdb.com/?spell=47240)

##### EXTRA NOTES:
none

AC HASH/COMMIT:
c208a12
from June 3rd

OPERATING SYSTEM:
OS: Ubuntu Server 20.04

MODULES:
none

OTHER CUSTOMIZATIONS:
No customizations at all

**Comment by Hacaw** [comment]
Conclusion
---
**_TLDR_**: Tested, reproduced, tried couple of solutions, but didn't work, tagged some people that might share some insights on this, since I am not that experienced with the API.

I already did some investigation on this ticket, but I still think some more experienced devs could contribute to this.

Code Analysis
---

I have reproduced this issue successfully from the commit: 885f45c6.
I have found the formula used in Unit.cpp, line 9016:9022.

`int32((aurEff->GetAmount() * owner->SpellBaseDamageBonusDone(SpellSchoolMask(SPELL_SCHOOL_MASK_MAGIC)) + 100.0f) / 100.0f);
`

The value from above formula is sent to this method 2 times as parameter for some mod-logic (weird):
` CastCustomSpell(this, trigger_spell_id, &basepoints0, &basepoints0, NULL, true, castItem, triggeredByAura); `

Testing
--- 
I have debugged the following scenario.
Level 80 Warlock with 1283 Bonus Damage. 
Let the Fellguard attack some dummies until Demonic Pact triggered 4 times described below:
1) Base-Damage: 1283 | Demonic-Pact: 128 => Total: 1411
2) Base-Damage: 1411 | Demonic-Pact: 13 => Total: 1424
3) Base-Damage: 1424 | Demonic-Pact: 1 => Total: 1425
4) Base-Damage: 1424 | Demonic-Pact: 1 => Total: 1425

Debugging
---
Added some logs before/after the method to cast-spell is triggered and here I found an interesting scenario.
Below are the previous scenarios but from the code-perspective.

Before cast: Demonic Pact 128 => with Amount 10 and Base Damage 1283
After cast: Demonic Pact128 => with Amount 10 and Base Damage 1411

Before cast: Demonic Pact 141 => with Amount 10 and Base Damage 1411
After cast: Demonic Pact 141 => with Amount 10 and Base Damage 1424

Before cast: Demonic Pact 142 => with Amount 10 and Base Damage 1424
After cast: Demonic Pact 142 => with Amount 10 and Base Damage 1425

Before cast: Demonic Pact 142 => with Amount 10 and Base Damage 1424
After cast: Demonic Pact 142 => with Amount 10 and Base Damage 1425

:warning: It looks like the base-damage is changed in the CastCustomSpell method. 
:warning: Could it be from the mod logic used in the CastCustomSpell method?
```
SpellCastResult Unit::CastCustomSpell(Unit* target, uint32 spellId, int32 const* bp0, int32 const* bp1, int32 const* bp2, bool triggered, Item* castItem, AuraEffect const* triggeredByAura, uint64 originalCaster)
{
    CustomSpellValues values;
    if (bp0)
        values.AddSpellMod(SPELLVALUE_BASE_POINT0, *bp0);
    if (bp1)
        values.AddSpellMod(SPELLVALUE_BASE_POINT1, *bp1);
    if (bp2)
        values.AddSpellMod(SPELLVALUE_BASE_POINT2, *bp2);
    return CastCustomSpell(spellId, values, target, triggered ? TRIGGERED_FULL_MASK : TRIGGERED_NONE, castItem, triggeredByAura, originalCaster);
}
```

Shouldn't mod logic be decoupled from the core-logic ?


@Winfidonarleyan, I added you in the loop, since you are the last user who modified most of the behavior.
@sanctum32 , I added you, because I saw you added a bunch of those SpellCast methods recently, can you please tell me which method should I use for casting a buff like this ? 
@FrancescoBorzi, is there any documentation when to use API methods for specific scenarios ?

**Comment by FrancescoBorzi** [comment]
@Hacaw thanks for your feedback!

> Shouldn't mod logic be decoupled from the core-logic ?

yes, it should. There are a lot of things in AzerothCore current design that should have been done differently, but we inherited a lot of legacy code from older mangos/trinitycore projects and changing it is not always easy.

> @FrancescoBorzi, is there any documentation when to use API methods for specific scenarios ?

as far as I know, unfortunately, there isn't any
