### ISSUE TITLE
Dimensius the All-Devouring cast spell error

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#3869]
The console can see the log as follows
`CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 198488 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)
CastSpell: unknown spell id 193195 by caster: creature (Entry: 19554)`

**Comment by Helias** [comment]
Do you use any modules? what is the version/commit of your AzerothCore?

**Comment by mpfans** [comment]
use mod-anticheat  
AzerothCore revision : 62e7bb332ac9+ 2020-12-03 05:28:21 +0000 (master branch)

**Comment by Kitzunu** [comment]
Weird, they dont have that spell to cast in Smart_scripts, and I can confirm that those spell does not exist so it is a valid error just don't know how

**Comment by Si1ker** [comment]
https://www.wowhead.com/spell=198488/infernal-power
Added in patch 7.0.1.20740

🤔  wtf ..

I can confirm the spell is neither in the core nor into the NPC's 'smart_script'

@mpfans , were you able to check at the exact moment when the NPC was doing something and then you get that error in the console? We could reduce the scope of this unexpected behavior in that way.

**Comment by Raelorasz** [comment]
This issue is still present as of 9821a930e8de.
Apparently the error is generated because, when Spell::damage is determined in Spell::HandleEffects, both Spell Effect base values are getting scaled up with caster level. 
Now, the first spell effect (the Glaive effectively doing damage part) being scaled up is fine, the second (SCRIPT_EFFECT which should be the glaive returning to the caster) is not fine and it is here that those 193195 and 198488 values are calculated.

In my opinion there are two solutions : 
- The preferable one, prevent damage from being scaled up if spell effect is SCRIPT_EFFECT. This could affect other spells which have SCRIPT_EFFECT but honestly the correct SCRIPT_EFFECT value shouldn't be based on it being scaled up.
- Otherwise, prevent both effect values from being scaled up altogether. This would mean that the base spell damage should be changed accordingly.
