### ISSUE TITLE
Core/Spell: SPELL_EFFECT_CREATE_RANDOM_ITEM will still cast even if there are no free bag space

### ISSUE THREAD

**Issue by Hacaw** [azerothcore/azerothcore-wotlk#4095]
##### CURRENT BEHAVIOUR:
Container item gets deleted.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Container item should be opened up to visualize what contains even though the backpack is full.

##### STEPS TO REPRODUCE THE PROBLEM:
1. create fresh character with default backpack (only hearthstone)
2. additem 2212 14
3. additem 5523
4. your backpack is now full
5. try to open up the shell
6. you get the error message: Inventory is full but it deletes your clam and the contents of it

##### AC HASH/COMMIT: 
e7dc6df31e0eff050103eb5ded28c419a2e748fc

##### OPERATING SYSTEM:
Windows 10 - Docker for Desktop

##### EXTRA NOTES: 
First encountered on ChromieCraft Server + Client

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by FrancescoBorzi** [comment]
are we sure that it's not a problem in the client?

**Comment by r0m1ntik** [comment]
confirm [5d8ada5
](https://github.com/azerothcore/azerothcore-wotlk/commit/5d8ada587d043e17ee9115260206158623b01468)

**Comment by Hacaw** [comment]
> are we sure that it's not a problem in the client?

Tested with warmane client and chromie craft client.

**Comment by wizzymore** [comment]
Confirm this, this is treaky to get done.
The item is using the spell: 58172
So the checks we need to do is:
Before casting spell that has the effect: "Open Item" we need to check if the player has enough inventory space, but you can't check it without casting the spell to know what dropped, and if you cast it and then just don't give the player the items because he has no space in inventory you need to give the player the item back, also, resetting the loot_chance everytime he tries to do this.

It's a mess

**Comment by Kitzunu** [comment]
@Hacaw https://github.com/azerothcore/azerothcore-wotlk/pull/4298 :)
