### ISSUE TITLE
[Spell/Glyph] Glyph of Molten Armor keep bonus on talent tree change

### ISSUE THREAD

**Issue by mnclaras** [azerothcore/azerothcore-wotlk#4208]
##### CURRENT BEHAVIOUR:
Fire Mage.
[Glyph of Molten Armor](https://www.wow-mania.com/armory/?item=42751) keeps the bonus if you change your active talent tree, until the buff is renewed.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Character should lose all buff benefits from glyphs if you change the spec (at least if the glyph is not in the other talent tree), without the need of renew it.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Put the glyph in your primary talent tree (Molten Armor).
2. Cast Molten Armor
3. Learn Double Specialization and change your talent to the secondary talent tree.
4. The glyph bonus is still applying to the character until you cast it another time.

##### AC/HASH COMMIT
[90526df](https://github.com/azerothcore/azerothcore-wotlk/commit/64c686c40c54f638a1cc3baeffcbbacc966a4a3d)

**Comment by r0m1ntik** [comment]
confirm [90526df8aba6dfa84e2941f61ef74f988b07976a](https://github.com/azerothcore/azerothcore-wotlk/commit/90526df8aba6dfa84e2941f61ef74f988b07976a)

**Comment by FrancescoBorzi** [comment]
thanks for confirming @r0m1ntik

**Comment by Synful-Syn** [comment]
I know that the T9's 2 pieces set bonus should retain its buff even after you switch out of the T9.
(Source: "Mage T9 2p" on mmo-champion back on [2010-04-08, 01:40 PM](https://www.mmo-champion.com/threads/707670-Mage-T9-2p).
Since it was known, someone asked for a macro that helped them have Molten Armor with the bonuses of the 2pT9.
(Source: "T9+molten armor macro??" on mmo-champion back on [2010-07-03, 02:06 AM](https://www.mmo-champion.com/threads/732477-T9-molten-armor-macro)).
![image](https://user-images.githubusercontent.com/22718174/163677711-379e18ba-aea6-4097-b9d9-68733801a811.png)

However, about the dual specialisation, again on the "Mage T9 2p" thread, back on 2010-04-09, 04:02 PM, the dual specialisation allowed a paladin to benefit the 10 expertise bonus of the Glyph of Seal of Vengeance with the following steps.
1. Be on the talent tree with Glyph of Seal of Vengeance
2. Use Seal of Vengeance or Seal of Corruption
3. Change specialisation with Dual Specialisation or replace your Glyph of Seal of Vengeance with another glyph
4. Profit!

![image](https://user-images.githubusercontent.com/22718174/163677840-80e0fafb-3e34-4aa0-9832-227783663fb5.png)
Since changing the dual specialisation didn't reevaluate the benefits of Glyph of Seal of Vengeance, I believe the same behavior will happen with Glyph of Molten Armor and this might be a Blizzlike bug and thus might not be fixed.

**Comment by UltraNix** [comment]
As @Synful-Syn said. Plus this one: https://github.com/azerothcore/azerothcore-wotlk/issues/10264
I believe it's Blizzlike.
