### ISSUE TITLE
Feature: Missing Despawn in "fix(DB/Creature): Civilian Recruit Valiance Keep (#4071)"

### ISSUE THREAD

**Issue by genion18** [azerothcore/azerothcore-wotlk#4278]
Missing Despawn in "fix(DB/Creature): Civilian Recruit Valiance Keep (#4071)" for WP 15 and WP 27

This fix this

```
 -- From Toxic/ICC
DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `id` in (15,16) and `entryorguid` = 25220);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(25220, 0, 15, 0, 40, 0, 100, 0, 15, 2522000, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Civilian Recruit - On Reached WP15 - Despawn'),
(25220, 0, 16, 0, 40, 0, 100, 0, 27, 2522001, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Civilian Recruit - On Reached WP27 - Despawn');
```

**Comment by FrancescoBorzi** [comment]
thanks @genion18 for your report and provided fix, can you please [open a PR](https://www.azerothcore.org/wiki/How-to-create-a-PR) with it?

**Comment by Kitzunu** [comment]
@wizzymore

**Comment by wizzymore** [comment]
Hi,

The SAI is automatically despawning them as they reach the final waypoint, what exactly is the problem here?

Thanks,
Ouizzy

**Comment by wizzymore** [comment]
The proof that it works correctly:

![image](https://user-images.githubusercontent.com/25827787/104639830-888b5e80-56b0-11eb-8460-b73620b2068f.png)
![image](https://user-images.githubusercontent.com/25827787/104639840-8b864f00-56b0-11eb-9406-1f741deffe2d.png)
![image](https://user-images.githubusercontent.com/25827787/104639862-90e39980-56b0-11eb-8764-105714c18df6.png)

The reason why i don't need to set a despawn on the last waypoint is because of this being preset on both WP_START actions for both waypoints:
![image](https://user-images.githubusercontent.com/25827787/104639948-a658c380-56b0-11eb-9dd6-1c70e12676e6.png)

**Comment by Kitzunu** [comment]
Thank you @wizzymore
