### ISSUE TITLE
Darkshore cemetaries not available for horde players

### ISSUE THREAD

**Issue by Gizmoh** [azerothcore/azerothcore-wotlk#4304]
##### CURRENT BEHAVIOUR:
If as a horde player you die in Darkshore, currently tested at auberdine harbor, your spirit appears at ashenvale, and not even the nearer cementery in ashenvale.
![imagen](https://user-images.githubusercontent.com/4155081/104849971-6faac500-58cb-11eb-91d1-ba63a0f0d5a8.png)
![imagen](https://user-images.githubusercontent.com/4155081/104849985-7b968700-58cb-11eb-9a95-3f45a0eff821.png)
![imagen](https://user-images.githubusercontent.com/4155081/104850002-7fc2a480-58cb-11eb-8a01-34435d5d6b41.png)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
You should appear in a cemetery in Darkshore instead of Ashenvale

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Be Horde
2.  Die at Auberdine
3.  ???
4. Profit

##### AC HASH/COMMIT:
df600f9946c

##### OPERATING SYSTEM:

Ubuntu 20.04
##### MODULES:

    mod-cfbg
    mod-duel-reset

##### OTHER CUSTOMIZATIONS:

None.
##### SERVER:

ChromieCraft

**Comment by nicoaravena** [comment]
This is not the only spirit healer with that problem, in Tirisfal Glades if you die near the scarlet monastery, you will be spawned as ghost in the Brill spirit healer, and there is a near one there.
Also it appears that the correct behaviour is to find the nearest respawn in the map you are located, except for the main cities for the opposite faction (as you can find here https://www.wowhead.com/npc=6491/spirit-healer#comments:id=621748)

**Comment by Zoidwaffle** [comment]
@nicoaravena : maybe you should open an issue regarding this?

I tried to look into it, but I don't know how to solve it.

The issue is, as I see it, that everything outside of the monastery is zone 85. Once you enter the building, you are in zone 796.

This was tested as Alliance.

Die in zone 796 and you end up in the GY marked with blue on the map... but die in zone 85, and you end up near Brill instead.

There are also "Area" code changes besides the zone ones, but the graveyard_zone table in the database doesn't use that so I don't know if this can be even fixed unless some core code is rewritten to handle this (and I have no idea if this is Blizz-like or not).

**Comment by Helias** [comment]
Are we sure that this is not blizzlike?

The SpiritHealer locations are blizzlike, they are all extracted from the client, the faction of them not, but I have no way to verify if the faction should be for both faction or only for alliance.

**Comment by Zoidwaffle** [comment]
I have no idea if it's Blizz or not as mentioned - I just tried to see if it could be moved. And with my limited understanding of how things work, the answer is "no".

So unless someone/anyone can show that the current behavior is wrong (logically it seems wrong, but that's not saying it is), then I guess it works as intended already.

**Comment by FrancescoBorzi** [comment]
please test: https://github.com/azerothcore/azerothcore-wotlk/pull/4322
