### ISSUE TITLE
NPC:soridormi (19935) Wrong gossip option

### ISSUE THREAD

**Issue by mpfans** [azerothcore/azerothcore-wotlk#4316]
##### CURRENT BEHAVIOUR:
When The Scale of the Sands reputation revered,talk soridormi (id 19935),Select any ring quest,next quest... next...
At the last step,then talk to NPC,Select 'I've lost my Band of the Eternal Defender',NPC have give you a Band of the Eternal Defender(id 29297),this ring only The Scale of the Sands reputation Exalted can get it

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Band of the Eternal Defender(id 29297),this ring only The Scale of the Sands reputation Exalted can get it

'I've lost my Band of the Eternal Defender'  gossip option only  The Scale of the Sands reputation Exalted  can see it

##### STEPS TO REPRODUCE THE PROBLEM:
1. .go c 23453
2. .gm off and .gm visible on
3. set The Scale of the Sands reputation revered
4. get 'Defender's Pledge'(id 10460)
5. get 'Defender's Pledge'(id 10467)
6. get 'Defender's Pledge'(id 10471)
7. click 'I've lost my Band of the Eternal Defender'  gossip option

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/43d1a03e9bb5c6856fe931aef29a9d8426ca9c0e

##### OPERATING SYSTEM:
ubuntu 18.04

##### MODULES:
mod-anticheat

**Comment by avarishd** [comment]
https://github.com/chromiecraft/chromiecraft/issues/7102

We seem to have them, but with empty broadcastID. (And I cannot backtrace it)
![image](https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/12c65fe8-93e4-43b2-85a4-2f75fa4abb26)

**Comment by amed80** [comment]
maybe similar to this https://github.com/azerothcore/azerothcore-wotlk/pull/17385 ? ConditionTypeOrReference should be set to 8 instead of 9 ?

also while at it , change Restorer's Vow requirement rep to be 3000 instead of 9000 as the quest is showing atm when you reach honored instead of friendly.
And all the swapping quests at the end should be repeatable so you can change the ring again as it's only possible to change it just one time atm.

probably something like this ?

UPDATE `conditions` SET `ConditionTypeOrReference` = 8 WHERE `SourceGroup` = 8234 AND `ConditionTypeOrReference` = 9;
UPDATE `quest_template_addon` SET `RequiredMinRepValue` = 3000 WHERE (`ID` = 10465);
UPDATE `quest_template_addon` SET `SpecialFlags` = `SpecialFlags`|1 WHERE `id` IN (11103, 11104, 11105, 11106);

**Comment by avarishd** [comment]
Thing is we don't know if even such options exist, as due to empty broadcast, hence the need sniff label

**Comment by heyitsbench** [comment]
Broadcast text ID 21813, confirmed on build 55056 on Cata Classic.

**Comment by avarishd** [comment]
So it is 21813 "I seem to have misplaced my ring." for all rings, as it seems.
