### ISSUE TITLE
Distance to open a gameobject

### ISSUE THREAD

**Issue by Helias** [azerothcore/azerothcore-wotlk#4400]
##### CURRENT BEHAVIOUR:
I think that the current distance to open a gameobject is too much.
https://github.com/chromiecraft/chromiecraft/issues/28

##### EXPECTED BLIZZLIKE BEHAVIOUR:
in some youtube videos, the distance is the half or less than this screen

![image](https://user-images.githubusercontent.com/519778/106400213-61a58a00-641d-11eb-8a32-e7f6a93a93d1.png)

##### STEPS TO REPRODUCE THE PROBLEM:
check the distance to open a gameobject

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)

**Comment by Stifler82** [comment]
**Video "Fix" and Test:** **[Gameobject](https://youtu.be/v4VDOW92ys0)**

So, I have **"Fixed"** the problem **locally**, the problem is that this is not: **neither a CORE Fix**, **nor a DB Fix**.
Unfortunately **it is a Client Bug** that affects this game mechanic.

(I didn't show it in the video), but I also tried to import the Spell **[Opening](https://wotlk.evowow.com/?spell=3365)** into the **"spell_dbc"** table and also to import the **spell.dbc file (modified)** into the **"dbc" folder** of the emulator **"AzerothCore"**, but **it doesn't work**.
This means that **"The Game Client" FULLY IGNORES the indications of the CORE and DB**

**Comment by Helias** [comment]
If the problem is in the game client, I think that we can close this.

**Comment by Stifler82** [comment]
> If the problem is in the game client, I think that we can close this.

I, think so..
