### ISSUE TITLE
Cannot fish in orgrimmar [$10]

### ISSUE THREAD

**Issue by skxawng-cu** [azerothcore/azerothcore-wotlk#4510]
Cannot fish in orgrimmar

##### CURRENT BEHAVIOUR:

Frishing in orgrimmar is bugged.
Console log.
Fishable areaId 4374 are not properly defined in `skill_fishing_base_level`.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Fish in Orgrimmar and look at DBErrors.log file.
2. 
3. 

##### AC HASH/COMMIT:

71b40ed8bc75

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

Anticheat
DuelReset
Transmog

**Comment by JamesGent** [comment]
I've been able to fish in Orgrimmar without issue in Valley of Spirits and Valley of Honour. Do you have any screenshots/video of what this issue looks like?

**Comment by Kitzunu** [comment]
Same

**Comment by skxawng-cu** [comment]
I test it again after updated an work. Thanks.

**Comment by skxawng-cu** [comment]
I re open the issue because I confirm that female troll can not fish in Orgrimmar. Greets

**Comment by axzn** [comment]
I can confirm the issue happening for a female troll currently on ChromieCraft, here is the [video](https://streamable.com/29gchc).

**Comment by axzn** [comment]
I'm trying to debug this issue, looking through code, the culprit seems to be how the nearest point to player is calculated when casting **Fishing** spell, file `src/server/game/Spells/Spell.cpp`, line `1334`:
```c++
m_caster->GetNearPoint(m_caster, x, y, z, DEFAULT_WORLD_OBJECT_SIZE, dis, m_caster->GetOrientation() + angle);
```
The m_caster position in this case is dependent on Player height, and since female trolls have a slightly bigger height value, this potential fishing bobber location falls into `if (liquidLevel <= ground)` clause, making the fishing attempt fail. **I wonder what would be the best way to fix this, ideally without introducing a special case for female trolls...**

In case anyone cares, here is how to confirm the issue quickly:
```
$ .go creature gurky
Gurky is at the Orgrimmar Valley of Honor, at the fishing pier where the issue manifests.
$ /target player
$ .levelup 60
$ .modify money 999999
Buy fishing pole, learn apprentice fishing.
$ .setskill 356 300 300
Try fishing while standing on a pier. If the player character is for ex. a male troll, the fishing will be successful. If the player character is a female troll, the fishing will constantly fail. 
```

**Comment by Buggyswires** [comment]
Same issue for Human Male. No fishing possible in either Valley of Spirits or Valley of Honor

**Comment by UltraNix** [comment]
The problem is with calculations in `WorldObject::GetMinHeightInWater()`

**Comment by UltraNix** [comment]
```
if (canSwim && unit->GetMap()->IsInWater(x, y, max_z - Z_OFFSET_FIND_HEIGHT))
{
        // do not allow creatures to walk on
        // water level while swimming
        max_z = max_z - GetMinHeightInWater();
}
```
`IsInWater` means also shallow water, so `max_z-GetMinHeightInWater()` might be under the ground.
