### ISSUE TITLE
[EVENT] Gurubashi Arena chest does not work

### ISSUE THREAD

**Issue by Sworken** [azerothcore/azerothcore-wotlk#455]
The gurubashi event does not work
**Description**:

**Current behaviour**: Tell us what happens
The event is announced from world chat, 
**Expected behaviour**: Tell us what should happen instead
The event is announced from the world chat,but  Gurubashi Arena chest isn't spawning.

https://github.com/azerothcore/azerothcore-wotlk/commit/496536baadfa3950ab3be61fc94269c4ddf83f15

**Comment by Viste** [comment]
spawning normal for me on last master

**Comment by starrheld** [comment]
I had a player get it a week or so ago :)

**Comment by Yehonal** [comment]
I ve fixed it, are you using 1.x or latest master? You didn t follow our
rules for reporting.

Il 06/Apr/2017 13:55, "starrheld" <notifications@github.com> ha scritto:

I had a player get it a week or so ago :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/azerothcore/azerothcore-wotlk/issues/455#issuecomment-292151070>,
or mute the thread

**Comment by talamortis** [comment]
can confirm its working. but the only issue with this is that it requires a player to be in stv or it wont spawn the chess, but i believe this is something to do with the core with disabling features when a player is not within zone or distance.

**Comment by falzard** [comment]
I feel like it's more logical to make it spawn only if there is a player in stv, so it's all good
