### ISSUE TITLE
Core/Script: Implement instance script validation

### ISSUE THREAD

**Issue by LightDestory** [azerothcore/azerothcore-wotlk#4556]
##### CURRENT BEHAVIOUR:
When attempting to summon the litch king the server starts to dead-loop on segmentation fault

##### EXPECTED BLIZZLIKE BEHAVIOUR:
No SegFault

##### STEPS TO REPRODUCE THE PROBLEM:
1. Execute  .npc add 38153

##### EXTRA NOTES:
None

##### AC HASH/COMMIT:
c5400b301259

##### OPERATING SYSTEM:
Debian 10 under WSL2

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by FrancescoBorzi** [comment]
it could be related to the fact that you're trying to spawn in the world a boss that is supposed to be inside a dungeon, however I agree that the server should be robust enough to not crash

**Comment by Kitzunu** [comment]
First of all 38153 is just a trigger so you wouldn't get anything out of spawning it (Not even a model).

Second of all, it crashes due to _instance being nullptr
https://github.com/azerothcore/azerothcore-wotlk/blob/5cd011bee0f0cddb76d28abd787ffc2361a0a1a9/src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp#L645

So you could prevent the crash by adding 
```cpp
if (_instance && _instance->GetBossState(DATA_VALITHRIA_DREAMWALKER) != IN_PROGRESS) 
```

But the most proper fix would be to rework the scripts to always have validation for if the NPC is inside the instance. TrinityCore already have such checks :)
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/CreatureAIImpl.h
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Instances/InstanceScript.cpp#L810-L816

This means that if a creature is spawned outside the instance it will not initialize the script

**Comment by FrancescoBorzi** [comment]
@Kitzunu nice, can you please provide a PR?

**Comment by Kitzunu** [comment]
Too much work, too little time. Perhaps within the next 2-3 weeks

**Comment by Kitzunu** [comment]
PR ready to go
