### ISSUE TITLE
Molten Core Boss adds don't respawn

### ISSUE THREAD

**Issue by T1ti** [azerothcore/azerothcore-wotlk#4569]
##### CURRENT BEHAVIOUR:
When killed, [Garr's adds](https://classic.wowhead.com/npc=12099/firesworn) won't respawn after the encounter is reseted
![image](https://user-images.githubusercontent.com/40864460/107867514-dc3dc300-6e7b-11eb-89b8-373b64823104.png)
 been waiting 15 mins
-same issue for other bosses adds : Lucifron, Gehennas, Majordomo, Golemagg

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Garr's adds should respawn when the encounter resets (raid wipes)
https://youtu.be/8FZKW0APoDw?t=1707 

##### STEPS TO REPRODUCE THE PROBLEM:
 - .tele moltencore
 - kill garr's adds and reset the fight (die or enter gm mode)

##### AC HASH/COMMIT:
03e77ce66f2ccf55a4958faa4f36991ac4e95e2d

**Comment by r0m1ntik** [comment]
@T1ti respawn is 2 hours not 15 mins.

**Comment by T1ti** [comment]
> @T1ti respawn is 2 hours not 15 mins.

The issue si that they should respawn whenever the raid wipes and the encoutner resets.

**Comment by valens14** [comment]
I've been working with all of the vanilla raid content on my server and this issue was not unique to Garr, but affected every boss in Molten Core that had adds.  For example, if you engage Majordomo and kill 3 of the adds before wiping, you will be able to engage him again but he will only have 5 adds remaining.  This issue also affected Bug Trio in AQ40.  If you killed any of the three bugs then wiped the dead bug bosses would not respawn and you could engage them again with only 1 or 2 left.  I used a work around in MC because I was almost brand new but I did correctly fix the issue on Bug Trio.

**Comment by FrancescoBorzi** [comment]
> I've been working with all of the vanilla raid content on my server and this issue was not unique to Garr, but affected every boss in Molten Core that had adds. For example, if you engage Majordomo and kill 3 of the adds before wiping, you will be able to engage him again but he will only have 5 adds remaining. This issue also affected Bug Trio in AQ40. If you killed any of the three bugs then wiped the dead bug bosses would not respawn and you could engage them again with only 1 or 2 left. I used a work around in MC because I was almost brand new but I did correctly fix the issue on Bug Trio. I'm not sure how to share fixes via Github though. Working on my server is the only experience I've had with programming.

hello @valens14 and welcome to AzerothCore. This is how you can share your fixes:

https://www.azerothcore.org/wiki/How-to-create-a-PR

if you have any questions or need some assistance, please ping us on https://discordapp.com/invite/gkt4y2x
