### ISSUE TITLE
Phasing bug | Hodir's quest chain | Several ending quests involved

### ISSUE THREAD

**Issue by sucofog** [azerothcore/azerothcore-wotlk#458]
**Description**: Several quests involved in this, when you are going to do a quest, the quests does not turn you in into the correct phase required to see the NPCs or the Gameobjects involved in this quests.

**Current behaviour**:

This problem happens on this quests:

- http://www.wowhead.com/quest=13011/jormuttar-is-soo-fat --> NPC's and gameobjects involved in this quest are in phase 4, and player is in phase 1 (not turn-in)
![image](https://cloud.githubusercontent.com/assets/734950/24805214/442c5bce-1bb1-11e7-8a4b-236d6531f003.png)

- http://www.wowhead.com/quest=12975/in-memoriam --> gameobjects involved in this quest are in phase 4, and player is in phase 1 (not turn-in)
![image](https://cloud.githubusercontent.com/assets/734950/24805041/aedbaec6-1bb0-11e7-9f0e-293fe9bed38f.png)

- http://www.wowhead.com/quest=12966/you-cant-miss-him --> NPC involved is in phase 4, player is in phase 1 (not turn-in)
- http://www.wowhead.com/quest=12976/a-monument-to-the-fallen --> NPC involved is in phase 4, player is in phase 1 (not turn-in)

![image](https://cloud.githubusercontent.com/assets/734950/24805397/e5f7d1e0-1bb1-11e7-89c1-489966e7acd4.png)

**Expected behaviour**: Phasing should turn to the correct one to be able to complete quests.

**Steps to reproduce the problem**:

1. Take quests
2. Go to the involved locations and try to look for NPC's and Gameobjects to complete this quests
3. Wait till your beard grow

**Branch(es)**: master

**AC hash/commit**:  

**Operating system**:  Linux

**Modules**:  Transmog, Duel Reset, Mod-Anticheat

**Other Customizations**: PvP Titles ranks

**Comment by Thurin93** [comment]
It mainly happens with Njormeld,  but if you do all this correctly and following them properly you have no problems. Personally I completed them all including daily etc .. and had no problems. While many ppl have problems because they skip quests. The first example reported from your issue can be solved by controlling which quest has been done. A player has had the same problem yesterday, completed the quest "A spark of hope" and the phase has been set properly.
Just try following the order shown in this link [http://wowwiki.wikia.com/wiki/The_Sons_of_Hodir_quest_chain](url)

**Comment by sucofog** [comment]
Did all the quests until "A spark of hope".

I completed the quest, and Thorim was suposed to give me the quest [80] Forging an Alliance

No quest shown by npc Thorim:

![image](https://cloud.githubusercontent.com/assets/734950/24810553/ef54b5f8-1bc2-11e7-83ba-3cd65cb87b75.png)

**Comment by sucofog** [comment]
This issue can be closed, i tested all the quests, working as intended, my bad.

**Comment by starrheld** [comment]
Closing as requested in the previous comment.
