### ISSUE TITLE
DB/Creature: Vyrin Swiftwind

### ISSUE THREAD

**Issue by Valoriaz** [azerothcore/azerothcore-wotlk#4706]
Vyrin Swiftwind - translation error

##### CURRENT BEHAVIOUR:

with enGB client the npc called "Vyrin Swiftwind" without a subname. with deDE npc called "Vyrin flinkwind" with the subname "Gastwirtin" (Innkeeper)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

With a German client, the "Subname" should not be available 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Start wow with deDE (and login as alliance)
2.  .go -5666 -4255 407 and you see the subname "Gastwirtin"

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/28f1dc5c0cc0d3ce26bb64bfc4475329fb5166c2

##### OPERATING SYSTEM:

Windows Server 2019
and Windows 10 64 bit

**Comment by Helias** [comment]
is this a server issue or it depends only on the client?

cc @Stifler82

**Comment by Stifler82** [comment]
@Helias @Valoriaz 

Actually the problem is not in the deDE version, the problem is in the enUS / enGB version because the Title / Subname is missing.
We need to update the Subname in the creature_template table and insert **"Innkeeper"**

<details>
<summary>ScreenShots</summary>

![image](https://user-images.githubusercontent.com/1884642/110015141-76768580-7d1b-11eb-9c18-6376fab39f81.png)
![image](https://user-images.githubusercontent.com/1884642/110015270-960dae00-7d1b-11eb-953c-6a9d5d403391.png)
![image](https://user-images.githubusercontent.com/1884642/110015529-db31e000-7d1b-11eb-9d65-1a8010467818.png)

</details>

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/110050843-0d136880-7d55-11eb-814f-f34440120e4c.png)
https://wow.gamepedia.com/Vyrin_Swiftwind
![image](https://user-images.githubusercontent.com/24550914/110050947-3207db80-7d55-11eb-898c-d02ad4e7ef49.png)

Shouldn't be an innkeeper in this version

**Comment by Stifler82** [comment]
> ![image](https://user-images.githubusercontent.com/24550914/110050843-0d136880-7d55-11eb-814f-f34440120e4c.png)
> https://wow.gamepedia.com/Vyrin_Swiftwind
> ![image](https://user-images.githubusercontent.com/24550914/110050947-3207db80-7d55-11eb-898c-d02ad4e7ef49.png)
> 
> Shouldn't be an innkeeper in this version

So if it's as written in the article, the **creature_template_locale** table is wrong, where was the data contained in this table taken from? by Cataclysm?

**Comment by Kitzunu** [comment]
Probably yea
