### ISSUE TITLE
Crossfaction

### ISSUE THREAD

**Issue by HamedMohsenavi** [azerothcore/azerothcore-wotlk#472]
**Description**:
Hi All I

I have fixed crossfaction for azerothcore but there's a problem anyone who joins battleground goes to horde side
Can anyone help

My CrossFaction https://pastebin.com/9uxdrtDF

Crossfaction TDB 63 https://pastebin.com/8BVdbzZA

**Comment by falzard** [comment]
Just a small note: this CFBG may be randomly crashing when players leave a battleground (or go afk), you should test it in depth.

**Comment by ShinDarth** [comment]
@HamedMohsenavi  Hi, I guess it would be much easier for people who are going to check/test your crossfaction if you push it on a github repository, so people can just clone it.

What you can do is the following:

- create a fork of the azerothcore repo
- clone your fork locally
- inside the directory of your clone, create a new branch, e.g. ``git checkout -b crossfaction``
- apply your changes
- commit and push

so you will get something like https://github.com/HamedMohsenavi/azerothcore-wotlk/tree/crossfaction

ready to be tested.

However, this is not the right place to discuss about it since it's not an issue of the official AzerothCore (it does not belong to this issue tracker).

For this reason I'm closing this issue here but feel free to discuss it on our [discord](https://discordapp.com/invite/gkt4y2x) chat

**Comment by Devalenok** [comment]
@HamedMohsenavi, "My CrossFaction https://pastebin.com/9uxdrtDF"
Will not work, there are no such variables in AC! 
if (!Alliance || !Horde) This patch from Trinity 60

And do not lie that this is your patch.
