### ISSUE TITLE
[ZONE][WOTLK] Dalaran

### ISSUE THREAD

**Issue by TW1NKLET** [azerothcore/azerothcore-wotlk#473]
**Description**: Trespasser spell makes it impossible to interact with vendors as Horde

**Current behaviour**: You can't interact with the NPC(S) due to [SPELL] Trespasser, you get teleported away

**Expected behaviour**: You shouldn't be teleported when you interact with the vendors

**Steps to reproduce the problem**:

1. Walk
2. Close
3. To the NPC in the photos as Horde

![IMG](http://i.imgur.com/OcbtNhG.jpg)
![NAV](http://i.imgur.com/LGfPhVE.jpg)
**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  Windows 10

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by starrheld** [comment]
I think this is due to your "fix"
https://github.com/azerothcore/azerothcore-wotlk/commit/7408b67629386759fe36b05b6d2d43899f5a278d

At line:
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/scripts/Northrend/zone_dalaran.cpp#L449

I would suggest to swap it to:
```
if (!me->IsWithinDist(who, 65.0f, false))
```

Like here:
https://github.com/TrinityCore/TrinityCore/blob/master/src/server/scripts/Northrend/zone_dalaran.cpp#L80
