### ISSUE TITLE
[Rare Mob] Lady Moongazer doesn't have any Waypoints

### ISSUE THREAD

**Issue by Hacki95** [azerothcore/azerothcore-wotlk#4774]
##### CURRENT BEHAVIOUR:
- She doesn't move around.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
- She should move around (https://youtu.be/f-fose1oE-w?t=4116)

##### STEPS TO REPRODUCE THE PROBLEM:
1. .go c 37730
2. .die
3. Try to loot

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/60d684282b602addfcb666cc970f01f700732b37

##### OPERATING SYSTEM:
Ubuntu 18

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

**Comment by Helias** [comment]
Cannot reproduce, the missing loot.

I confirm the missing waypoints

![image](https://user-images.githubusercontent.com/519778/110542667-a3ff6c80-8129-11eb-8c0f-5d7fcb33c88b.png)

**Comment by Hacki95** [comment]
> 
> 
> Cannot reproduce, the missing loot.
> 
> I confirm the missing waypoints
> 
> ![image](https://user-images.githubusercontent.com/519778/110542667-a3ff6c80-8129-11eb-8c0f-5d7fcb33c88b.png)


> 
> 
> Cannot reproduce, the missing loot.
> 
> I confirm the missing waypoints
> 
> ![image](https://user-images.githubusercontent.com/519778/110542667-a3ff6c80-8129-11eb-8c0f-5d7fcb33c88b.png)


Huh. So I killed her again and this time dropped something, but for example not the guaranteed green item but only Linen Cloth and Wool Cloth.

Did you kill her severall times? Maybe the chances are just way off?

**Comment by Hacki95** [comment]
Normally rare mobs have one guaranteed green drop, this most likely isn't possible to do just with the normal loot tables right?

**Comment by Zoidwaffle** [comment]
I recall some of the lower level rares having no greens/blues in the Blizz version as well (and for sure that's true in Classic). Later in the game, true, I don't recall a rare ever not dropping some sort of magic item that was usually unique for that mob as well.

She has 0 interesting loot in the database - and in Classic her loot table seems to reflect AC: https://classic.wowhead.com/npc=2184/lady-moongazer

As @Helias said, she's guaranteed to drop a whopping 20 copper up to an astonishing 31 copper! So I think the current loot is OK? :smile: 

She has no pathing in TC either, so that part is missing indeed... Do we have some more information about her pathing? Then I might be able to make a PR.

**Comment by Hacki95** [comment]
In the video I linked it looks like she has no specific waypoints but just uses the wandering AI. Maybe I can find another video later to confirm this.

**Comment by Zoidwaffle** [comment]
@Hacki95 : Perhaps you can find a better source for her movements or have some feedback - but your comment about the "wandering AI" made me create a simple PR to improve her :+1:
