### ISSUE TITLE
Sap breaks on (Warlock or Hunter) Master NPC when the Rogue attacks the pet

### ISSUE THREAD

**Issue by necropola** [azerothcore/azerothcore-wotlk#4790]
Original report: https://github.com/chromiecraft/chromiecraft/issues/191 by @necropola
I've checked my local AC and TC server:
* Bug exists in current AC, too
* Bug **does not exist** in current TC

It looks like it only affects NPC (Sap) targets, i. e. probably an AI issue.

##### ISSUE: FACTION SIDE:
![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
When a Rogue applies [Sap](https://wotlkdb.com/?spell=6770) to a Hunter or Warlock **NPC** and then attacks (tries to kill) the pet, the master wakes up. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Only damage to the sapped target itself (and not its pet) should wake up the target.

##### CURRENT BEHAVIOUR:
See **Short Description**

##### STEPS TO REPRODUCE THE PROBLEM:
* Sap a Hunter or Warlock
* Attack its pet

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/b6bcb0b2b01d9788cc19a0a726ea9019b4673a1b

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stifler82** [comment]
Ok, after careful consideration, I have reached the conclusion that this is not a Bug.

The reason is: The Warlock does not make a Summon through SAI, that is, that summons the Demon's ID, but summons the Demon through Spell, this means that the NPC (Summoner) shares their "Properties" with the Demon exactly as it happens between Warlock Character and Demon, so they share Stats like "Armor" etc..
So when the Demon takes damage, the Warlock is also affected by this damage, but! he takes no damage..
