### ISSUE TITLE
Priest pet Shadowfiend should have more HP

### ISSUE THREAD

**Issue by laasker** [azerothcore/azerothcore-wotlk#4792]
##### CURRENT BEHAVIOUR:
Priest pet Shadowfiend https://wowgaming.altervista.org/aowow/?spell=34433 should have double the HP it currently have

A priest with ~28k HP, the pet has ~9k HP
https://www.youtube.com/watch?v=XrxKEJwiYVE

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The pet should have 16k~18k+ depending on your stamina/hp
Proof: 
https://www.youtube.com/watch?v=XcQdFJjL4SQ&ab_channel=ZybakTV 
at 2:40 you can see enemy priest has 28,3k HP and seconds later druid targets his pet and it has 18,3k HP

https://www.youtube.com/watch?v=buLNkD4uw0o&ab_channel=itsXMO 
if you pause at 9:13 you can see shadowfiend have 16,7k HP and in the right corner you can see priest on focus with 25400 HP

##### STEPS TO REPRODUCE THE PROBLEM:
1.  Create a Priest, equip with some gear till it have 25k+ hp
2.  Cast Shadowfiend on some mob or dummy
3.  Target Shadowfiend and check his HP

##### EXTRA NOTES:
This is the spell that give priest mana and has 5m cd, so the pet should not have low hp, making it die faster in PvP

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/51342ef9b500

##### OPERATING SYSTEM:
Windows 10

**Comment by claudiodfc** [comment]
![image](https://user-images.githubusercontent.com/54484196/110996434-d7353c00-8373-11eb-832e-29415883a488.png)

If you divide 28300 by 18300 that means that every 1.54hp of the priest equals 1 of the fiend.
Right now if you divide 28000 by 9000 the fiend will get 1 hp per 3.11hp of the priest which is indeed not right.

Acording to [wowwiki](https://wowwiki-archive.fandom.com/wiki/Base_health) a priest at lvl 80 should have 6960 base hp. You can calculate this by doing this formula:
`Base Health = Max Health - Health From Stamina`

So if a priest has 6960 (Base Health) = 28000 (Max health) - X (Hp Stamina)
X = -(6960-28000)
X = 21040
X/10 = 2104 Stamina


Since we don't really know how much of stamina did Fiends benefit I would suggest a simple rule of 3 base of the Priest's Max HP. The fiend should have the priests max hp / 1.5

**Comment by laasker** [comment]
i was able to fix this by increasing the HP of creature_entry 19668 (level 80) to 12230 on db/world/pet_levelstats, not sure if its the right place to change values, but this fixed the problem.

Not sure if the scalling is correct, but a priest with ~14k HP, the pet has 14k hp, and a priest with 28160 HP, the pet has 18640 HP. So, it looks alright to me.
 I dont know how to make a PR, seems a little bit complicated to me, otherwise i would have done one.
