### ISSUE TITLE
Warrior charge bug (it is actually a Vmaps related issue)

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#4808]
Originally reported https://github.com/chromiecraft/chromiecraft/issues/171

##### ISSUE: FACTION SIDE:
 ![Alliance](https://user-images.githubusercontent.com/1884642/108204869-3a88d100-711c-11eb-8179-e1b9b73ed450.png)
![Horde](https://user-images.githubusercontent.com/1884642/108204991-63a96180-711c-11eb-9ed9-138c233070a6.png)

##### CONTENT PHASE:
any phase i guess

##### SMALL DESCRIPTION:

Spell: [Charge](https://wowgaming.altervista.org/aowow/?spell=100)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When i charge in movement i must move into target

##### CURRENT BEHAVIOUR:
When i charge in movement i just get rage and not even start combat
[video](https://www.youtube.com/watch?v=BSRXd6kf3a4)

##### STEPS TO REPRODUCE THE PROBLEM:
1. Target any mob
2. Move and use charge at the same time

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6a7155eb7e82309ac34a38eec65eb7663b0605a0

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by FrancescoBorzi** [comment]
@Yehonal please have a look at this new bug movement-related

**Comment by Stifler82** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5022
https://github.com/chromiecraft/chromiecraft/issues/303

**Comment by FrancescoBorzi** [comment]
this is specific enough to keep it open, also it's quite important

@Stifler82 I agree to group similar issues together, but for that we need to use projects. Not merging all issues into one

**Comment by Stifler82** [comment]
@FrancescoBorzi @Yehonal @Helias 
In my opinion Charge works well and does not need any Fix, as you can see from my video..
**Video Test:** [Charge](https://youtu.be/GAqi6ebgUfo)

**Comment by FrancescoBorzi** [comment]
thanks @Stifler82 for testing this

**Comment by merdlin** [comment]
Hello, I am currently [master](https://github.com/azerothcore/azerothcore-wotlk/commit/0bb4ab3e3ebe98381dedc4cb78fa2bfde8df48ad) in and I have the same bug in Warrior's Charge, whenever I am in combat the skill does not work. when exiting combat the skill returns to work. I believe that the problem is related to the Bank 'acore_characters'. I don't know very well, but I have the same problem. I've tried everything and I can't solve it.

**Comment by merdlin** [comment]
why is it being closed? if there are two people reporting a problem, it is because there is a problem. The aim of the AzerothCore project is to fix bugs and not to keep bugs.

**Comment by merdlin** [comment]
I have videos proving bug and players also reporting this problem.

**Comment by Helias** [comment]
Hello, thanks for the detail, if you think that the bug is different from this issue open a new one, or just put the video here when you can and let's discuss it before reopen :+1:

**Comment by Yehonal** [comment]
@merdlin the problem with this report is the following....the test description says: Target any mob, Move and use charge at the same time. 

Doing so we cannot reproduce the bug since it works for us, as @Stifler82 showed in that video (I also just tested it with a warrior in Westfall). So probably you should provide better info to reproduce it, thus we can reopen this issue

**Comment by Yehonal** [comment]
> Hello, I am currently [master](https://github.com/azerothcore/azerothcore-wotlk/commit/0bb4ab3e3ebe98381dedc4cb78fa2bfde8df48ad) in and I have the same bug in Warrior's Charge, whenever I am in combat the skill does not work. when exiting combat the skill returns to work. I believe that the problem is related to the Bank 'acore_characters'. I don't know very well, but I have the same problem. I've tried everything and I can't solve it.

Also, about the "in combat" report. This spell is NOT intended to work when you are in combat. In fact, in my case, it is greyed out and you can't even use it. 

From the video you linked however I can see that the character is not in combat but there's a "red error" on the screen. The thing is that I cannot read that error because of the super-low quality and probably it's not even English.

There is no enough information here to reproduce it and the combat issue you reported is not an issue.
