### ISSUE TITLE
Lunaclaw spawn [Alliance]

### ISSUE THREAD

**Issue by markvetx** [azerothcore/azerothcore-wotlk#4829]
##### CURRENT BEHAVIOUR:
When player uses a [Cenarion Moondust](https://wotlkdb.com/?item=15208), Lunaclaw just spawning near the player.
In addition, after using a dust, [Moonkin Stone](https://wotlkdb.com/?object=177525) must have a blue glow around it but there isn't.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When player uses a [Cenarion Moondust](https://wotlkdb.com/?item=15208), Lunaclaw must run into the cave and start attacking player, plus [Moonkin Stone](https://wotlkdb.com/?object=177525) must have a blue glow around it.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .q add 6001
2. .go xyz 6354 138 24 1 4
3. Enter the cave and use moondust near the stone

##### EXTRA NOTES:

[#1. Video from 2008](https://youtu.be/Et7zuYWvS-s?t=172)
[#2. WoW Classic Behaviour](https://youtu.be/lVHaegvdrKc?t=113)

##### AC HASH/COMMIT:

b24ee3fc1043

##### OPERATING SYSTEM:

Arch Linux 5.11.5

##### MODULES:

[mod_autobalance](https://github.com/azerothcore/mod-autobalance)
[mod_ahbot](https://github.com/azerothcore/mod-ah-bot)
[mod_transmog](https://github.com/azerothcore/mod-transmog)

**Comment by markvetx** [comment]
[Found something interesting maybe?](https://github.com/TrinityCore/TrinityCore/commit/958665ab2ee0797c81c93a47162a38b2cbd33b36)

**Comment by Zoidwaffle** [comment]
Indeed, creature Lunaclaw Spirit (12144) is not using SmartAI but references npc_lunaclaw_spirit.

@illfated is mentioned as author of that commit - so summoning him now! [Performs some sort of ritual and accidentally ends up in Darnassus, the worst place in all of Azeroth].

[Returns from Darnassus] So as I was saying, I think @illfated should have a look, but otherwise it seems like it should be easy enough to migrate the fix over.

**Comment by illfated** [comment]
As much as I like being mentioned, I have to point out that the commit you refer to does not appear in the source referenced by the commit used in the main ticket report above.

https://github.com/azerothcore/azerothcore-wotlk/blame/b24ee3fc1043df1fc7021f79c2959cb76a4ea76e/src/server/scripts/World/npcs_special.cpp#L634-L673

https://github.com/azerothcore/azerothcore-wotlk/blob/b24ee3fc1043df1fc7021f79c2959cb76a4ea76e/src/server/scripts/World/npcs_special.cpp#L634-L673

I am fairly certain that the commit you refer to mostly has something to do with moving hardcoded text from C++ scripts to DB.

Regarding the reported issue, I think the spell itself needs adjusting, to make the Lunaclaw Spirit spawn outside of the cave. Not entirely sure if the event script needs adjusting too, to make the spawned creature target the player and run into the cave, but that would be fairly obvious to someone who can adjust the spell script.
- https://wotlkdb.com/?spell=18974/summon-lunaclaw

I can only vaguely remember that when I tested the script, I used Horde characters to test it in the Barrens area, near the entrance to Mulgore. At the time, it did not appear obvious to me that the Lunaclaw Spirit should appear some distance away from the player, so that issue never got addressed back then, when I was testing the Horde version.

You may also want to consider converting the script to SAI, perhaps making it easier to control the spawn point coordinates.

**Comment by Zoidwaffle** [comment]
Check, thanks for the info.

**Comment by Zoidwaffle** [comment]
I checked out the old commit and ported it to AC. It seems to work just as the old script did... Only it's now ported to SAI.

So technically it's an improvement, but seen from the player it makes no difference.

I will make a PR with it since it's an upgrade after all and should make a "true" fix easier to make by someone better at SmartAI than me.
