### ISSUE TITLE
‘BLACK WING LAIR’   No.1 BOSS BUG

### ISSUE THREAD

**Issue by Mycadi** [azerothcore/azerothcore-wotlk#486]
BLACK WING LAIR   No.1  BOSS  BUG

Open egg ..... Egg does not disappear.....

My English is poor.....HAHAHAHA!!!

**Comment by sucofog** [comment]
Lol?

**Comment by ShinDarth** [comment]
please read [How to open an issue](https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-open-an-issue)

thanks.

**Comment by mygithome002** [comment]
I tested ,this bug is existing too:
core:X64 (Without-Maps) 3.3.5a (With-Modules) (64-bit) MySQL 5.6 - No-Maps.rar
http://www.ac-web.org/forums/showthread.php?224282-(3-3-5a)-AzerothCore-Repack-32x-64x-(With-Transmog)

**Comment by mygithome002** [comment]
I tested ,this bug is existing too:
core:X64 (Without-Maps) 3.3.5a (With-Modules) (64-bit) MySQL 5.6 - No-Maps.rar[April-27-2017 [NEW] Release:]
http://www.ac-web.org/forums/showthread.php?224282-(3-3-5a)-AzerothCore-Repack-32x-64x-(With-Transmog)

1. cast no.3 spell:destory egg:
http://i2.muimg.com/577587/65e3dfd576fe3392.jpg

2. after spell action,egg still exist:
http://i2.muimg.com/577587/cb2229a3ee5e3d29.jpg
