### ISSUE TITLE
[quest] The Rescue

### ISSUE THREAD

**Issue by bensmrs** [azerothcore/azerothcore-wotlk#494]
**Description**:
Quest details: http://wotlk.evowow.com/?quest=498

**Current behaviour**: Drull can be rescued without any key.

**Expected behaviour**: Drull's chains should be unlocked with Dull Iron Key (http://wotlk.evowow.com/?item=3467)

**Steps to reproduce the problem**:

1. Accept the quest
2. Go to Drull's location
3. Click on the chain to unlock it

**Branch(es)**: master

**AC hash/commit**: cfd2d7e

**Operating system**:  Debian

**Modules**:  anticheat

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Gargarensis** [comment]
I could not find problems in the database, so I checked the DBC file:
https://imgur.com/a/mkgPS
Can someone tell what that highlighted cell does? I changed it to a 0 (like the other object of the quest) and it **almost** works since it requires the key but, instead of saying "Required Dull Key" when trying to open it without the key, it says "Invalid Target".

I noticed that clicking on the object without the key starts a "Disarm" action, maybe that cell in the dbc causes it.
