### ISSUE TITLE
Warsong Gulch Interior/Exterior Boundary is Incorrect (Doesn't Allow Mounting) [$10]

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#5086]
Warsong Gulch Interior/Exterior Boundary is Incorrect (Doesn't Allow Mounting)

## CURRENT BEHAVIOUR:

You must be 5+ yards outside of the building to mount up, causing people to awkwardly stand and click and try to find a spot outside they are allowed to mount at.

As you can see I'm quite far outside but I can't mount due to being indoors. "Can only use outside" is the error presented.

![WoWScrnShot_033121_211327](https://user-images.githubusercontent.com/61194190/113205250-faae2100-9265-11eb-91c2-c92829e28b7b.jpg)

## EXPECTED BLIZZLIKE BEHAVIOUR:

Should be able to mount when outdoors.

## SOURCE:

https://youtu.be/UyFATw5m7uE?t=86

Observe how the entire team gets an inch out of the door and begins mounting at 1 min 25 secs ish. Video is timestamped.

## STEPS TO REPRODUCE THE PROBLEM:

1. Enter WSG
2. Run out as the game begins and try to mount
3. Run in/ou/in/out and observe mount behaviour.

## AC HASH/COMMIT:

AzerothCore rev. 8bacb39d5334 2021-03-20 

## MODULES:

CFBG

## CUSTOMIZATIONS:

I do use some texture patches but texture patches shouldn't affect the size/shape of the map right?

**Comment by JamesGent** [comment]
Florencio — Today at 16:48
I could find like  4 spots where that happens on my local server

Tested & confirmed by discord Chromie user.

**Comment by LautaroJMolina** [comment]
Tried a couple spots.
I did find something odd, this seems to happen when going from the interior to the outside. 
In the spot in the above screenshot it's extremely noticeable. When exiting the interior you can't mount for quite a distance, but if you come from the exterior towards the entrance, it's much more accurate.

Another location I found:
![42 77, 64 47](https://user-images.githubusercontent.com/64675765/113335362-35ae6400-92fb-11eb-93f7-73bc5a51ee2e.png)
Coordinates: 42.77 64.47

And some others:
47.78, 21.48
49.41, 84.85
50.67, 66.87
50.69, 34.08
57.10, 39.91
60.71, 66.96

**Comment by UltraNix** [comment]
This bug (and many similar) comes from how the whole movement update is handled on SunwellCore (and AC). It's updated every few yards, due to performance. But this approach completely brakes smooth movement for players and creatures and it needs a major rewrite.
As the performance reasons - there is some solution on TC emu, that calculates all needed info (zone, area.outdoors, liquid) on every move (`GetFullTerrainStatusForPosition` - which is reduced vmaps calls) and all commits related to it should be ported to AC with removing that odd and useless code.
