### ISSUE TITLE
Chests don't despawn after being opened and emptied in parties (linked to rolling?)

### ISSUE THREAD

**Issue by JamesGent** [azerothcore/azerothcore-wotlk#5128]
## CURRENT BEHAVIOUR:

Chests don't despawn after being opened and emptied in parties (linked to rolling?)

![WoWScrnShot_040421_131548](https://user-images.githubusercontent.com/61194190/113516600-043fcd80-9573-11eb-8330-b27714080e92.jpg)

## EXPECTED BLIZZLIKE BEHAVIOUR:

Chests disappear once emptied.

## STEPS TO REPRODUCE THE PROBLEM:

1. Party up
2. Open a chest
3. Watch as you must open it 3-4 times for it to despawn.

## AC HASH/COMMIT:

AzerothCore rev. 9d4eebc61fec 2021-04-01 16:04:47 +0000 (master branch) (Unix, RelWithDebInfo)
Co

**Comment by pklloveyou** [comment]
#4413 It's about here

**Comment by pklloveyou** [comment]
The error disappears after PR is restored

**Comment by Stifler82** [comment]
##### CURRENT BEHAVIOUR:


**Any Player who is "Farming" the Chests spawned around the world, is potentially able to leave them empty.**



##### EXPECTED BLIZZLIKE BEHAVIOUR:


I suppose this is a Bug that also exists in Blizzard Retail, so we could call it a "BlizzLike-Bug".
The problem is that this Bug can ruin the game dynamics because a **"Player who doesn't do Fair Play"** could exploit this Bug to ruin the farming of others.



##### STEPS TO REPRODUCE THE PROBLEM:


**In this video I show you the steps to reproduce the problem.**

https://user-images.githubusercontent.com/1884642/115263649-814f7300-a12d-11eb-9b2b-7705e01133bd.mp4




##### EXTRA NOTES:


**This is the GameObject in question, but I am pretty convinced that this trick works with every Chest in the Game**
**[GameObject]:** [Solid Chest](https://wowgaming.altervista.org/aowow/?object=4149)

**Comment by Stifler82** [comment]
@JamesGent
