### ISSUE TITLE
Z position of monsters in water

### ISSUE THREAD

**Issue by nethw** [azerothcore/azerothcore-wotlk#5235]
## CURRENT BEHAVIOUR:
I know it has been recently patched (in january if I remember).
The monsters are indeed walking on the ground inside the water now. But if you pull them, they walk on the water. (we can see the monster walking in the water, but it must walk on the ground)

## EXPECTED BLIZZLIKE BEHAVIOUR:
Monster must keep walking on the ground

## STEPS TO REPRODUCE THE PROBLEM:

1.  Go to Southbreak Shore
2.  Pull a Coast Strider inside water
3.  Watch him walking on the water

## AC HASH/COMMIT:
master commit of 10/04/2021 (today)

## OPERATING SYSTEM:
ubuntu docker

## MODULES:
no

## CUSTOMIZATIONS:
no

**Comment by FrancescoBorzi** [comment]
cc @Yehonal @Footman

**Comment by Yehonal** [comment]
I think this issue "generalize" a lot. Monsters that can walk in water are "crabs-like" creatures, those creatures when under water and attacked they switch from walk to swim. When they evade they should go back walking on the depth. There are still some minor bugs to solve since some time crabs do not switch to the swimming animation when they are on the sea shore and you move them into the water (so probably this is also related to the Coast Strider  giant)...however, I've introduced a check inside the core where I take care of the height of the creature and the level of the water, and using a simplified version of the archimede's formula we I activate the swimming animation when there's enough water available (which could also related to the Coast Strider 
 giant case). 

I'll take a look at that specific creature

**Comment by Yehonal** [comment]
I just tested them, looks quite normal to me apart few minor bugs switching from swim to walk sometime. But 90% of cases it works. I'm gonna test it on retail in the meanwhile, can you upload a video to show me what do you mean? even with different kind of creatures if possible

**Comment by Yehonal** [comment]
In retail they do not swim anymore, they moved these giants far away from the deep sea so they evade before reaching higher levels :( 

Cannot test on classic though, I don't have a level 50+ char there

**Comment by Yehonal** [comment]
I asked @ReynoldsCahoon to record a video on official wow classic and here is what happens there:  https://www.youtube.com/watch?v=1DU3JJSrkog 

It looks more buggy than ours...Maybe that's why they moved those creatures on retail

**Comment by Mitradis** [comment]
why close?

**Comment by Yehonal** [comment]
Look at the video I sent. The creature you reported acts as on the official server. So we cannot consider it a bug
