### ISSUE TITLE
Event SAI 74

### ISSUE THREAD

**Issue by Stifler82** [azerothcore/azerothcore-wotlk#5270]
## CURRENT BEHAVIOUR:

The event SAI 74 **"FRIENDLY_HEALTH_PCT"**
Do not trigger with action 80 **"CALL_TIMED_ACTIONLIST"**
In addition it would be useful to add in **"Parameter 5"** the possibility to add the "Creature Entry" (the friendly target)
I also add that it would be useful for the event to be activated with any action **(or at least, with all those actions that have a logical sense for the activation of this event)**

In many SAIs that I have done, I have noticed that this event is not "recognized" by the NPCs, in the sense that it is as if the event did not activate.
**(Probably buggy)**
An example is what you see in the image below.
This is an example of a broken SAI.

![image](https://user-images.githubusercontent.com/1884642/114535629-26f37580-9c48-11eb-8d70-5496651dc322.png)

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers can anyone reproduce this?

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers can anyone check this?

**Comment by Raelorasz** [comment]
Currently SMART_EVENT_FRIENDLY_HEALTH_PCT only works with target types shown below (in SmartScript::ProcessEvent). To me it makes sense, the target should be the unit whose health percentage you're checking, be it a creature or a player. 

https://github.com/azerothcore/azerothcore-wotlk/blob/cb1aaec4af13341816b65fea5ccbb4b44ef7a585/src/server/game/AI/SmartScripts/SmartScript.cpp#L4327-L4347

The thing is that the target of whatever action you choose is also going to be the same unit whose health you're checking.
If you want a different target for the action (say Self for example) there's no way to do it in one SAI line, since you would need to specify two separate target types; one way in which you could get around that is with SET_DATA/DATA_SET trickery.
