### ISSUE TITLE
Trash spawn infinite (The Shattered Halls)

### ISSUE THREAD

**Issue by Siid974** [azerothcore/azerothcore-wotlk#529]
**Description**: The Shattered Halls (Trash spawn infini)

**Current behaviour**: After first boss in the long corridor trash no spawn in wave but spawn when you get to the end of the corridor

**Expected behaviour**: Normally the trash spawn by wave arrived at the beginning of the corridor after killing the non-elite trash that spawn we must kill the trash elite of the bottom

**Steps to reproduce the problem**:

1. Killed the first boss
2. Go to the bottom of the corridor
3. And Find the bug 

**Branch(es)**: Master

**Modules**:  Anticheat / Transmog

**Video**: https://youtu.be/hXWud6JoJwo

**Comment by sucofog** [comment]
Confirmed

**Comment by Yehonal** [comment]
@Siid974 i didn't understand if the issue is about a "cosmetic" since spawns are not at correct position and do not follow a path....or the bug is related to the fact that they spawn unlimited mobs and it shouldn't happen.

please be more clear about it otherwise we don't know what we've to fix exactly.

**Comment by Yehonal** [comment]
Moreover please give us links to creatures from here: https://wowgaming.altervista.org/aowow

**Comment by Yehonal** [comment]
We've fixed following this video: https://youtu.be/Tgok9bDH9N4?t=282

PR incoming ;)
