### ISSUE TITLE
Feature: config to allow low-levels arenas [$100]

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#5315]
It would be nice to be able to enable arenas for low-levels and be able to determine whether the players should get rating/points or not.

**EDIT**: here's the list of requirements for a new **module** implementing the following:

- brackets every 5 levels, so 10-14, 15-19, 20-24, 25-29, etc...
- you just need to be in a party group of 1, 2, 3, 4 or 5 to join
- when you join, there should be a global announcement like "A team queued for 3v3 arena [15-19]"
- there should be a spam filter mechanism to prevent the same team to spam the message too often (the same we currently have with BGs)
- people should be able to queue from everywhere using a command such as `.arena queue skirmish`

**In order for the bounty to be claimed, AS USUAL, it should be properly tested and ready for production.**

**Comment by 55Honey** [comment]
> ...able to determine whether the players should get rating/points or not.
Inidividually with a config flag each i guess.

**Comment by JamesGent** [comment]
For anyone interested you'd want to take inspiration from how wow separates 70 arenas from 80 arenas.

If you had 2700 rating and 5000 arena points at level 70, but became level 71, this would be wiped. You'd need to replicate this wipe at each bracket automatically.

"On November 19th, Blizzard Entertainment Wryxian (of the official EU forums) announced that arena points for players will be reset at level 71 and they will be removed from level 70 arena teams, "Players who level past 70 will have their Arena points reset to 0 and be removed from all Arena teams in the level-70 bracket"

You'd need a rating system exclusive to each bracket. So I think a 19 rating, a 29 rating, a 39, a 49, 59, 60, 70, 80 would be the total brackets needed. Currently there is a 70 bracket and a 80 bracket.

That's 8 brackets and rank setups compared to the current 2.

You'd need to be able to sign up to create teams at the arena NPCs, and manage teams at level 19 (or whatever the chosen lowest bracket would be).

You'd need settings in world.conf to manage each bracket, for example you'd need to be able to enable/disable 19 arenas without disabling 60 arenas.

You might want to make the config level brackets for the arenas optional. One server might prefer 10/20/30/40 brackets, Chromie prefers 19/29/39, I might prefer 25/35/45 etc.

Something like;

ArenaBracketOneEnabled = 0
ArenaBracketOneLevel = 19

etc

ArenaBracketSevenEnabled = 1
ArenaBracketSevenLevel = 70


https://wowwiki-archive.fandom.com/wiki/Arena_point

https://wowpedia.fandom.com/wiki/Arena

What I wrote won't be 100% accurate, for example I'm not sure if the current system has level 60-70 as "70 arenas" or if it's 70 only. Likewise 71-80 for 80 or "just 80".

**Comment by Cromisaid** [comment]
Hi all, Chromiecraft player here

If we implement Arenas we've to make the choice between:
1) if they'll be like Blizzlike system wants
2) if we can make a custom one


How the blizzlike arena system works in 3.3.5 (source: https://wowwiki-archive.fandom.com/wiki/Arena_PvP_system)

Only level 80 can make arena teams and join them as Skirmish or Rated Arena, the second one in order to get Rating and Arena Points as well.
players <80 are only able to join Skirmish (so random matchmaking)
The brackets will be like 15-19 / 25-29 / 35-39/ and so on...

Those system already exsist on Chromiecraft or every AC server, you probably just need to start the Arena Season to make arenas joinable by players.


But talking about Chromicraft, do we really need that?
my personal answer is Yes...but
but we could love a custom system that allow us to join Rated arenas already at bracket 30-39, in order to make PvP with a player the we chose before.
Why this?
Because we don't have the possibility to do pre-made PvP now, not in Battleground or Arenas.


What ChromieCraft Staff should take into consideration if they make a custom system:
1st) We'll need a Ranking List, and reward them too
2nd) Which reward arenas could give? (Already Arena Points? More Honor Points? Golds? be sure to make the right choice)
3rd) Probably a dev. should spend his time to make that system instead of making something else, since ours don't have it, you probably have to invest in bounty reward.


That's probably everything
If you need something, let me know :)

**Comment by FrancescoBorzi** [comment]
I'm considering starting with a simple requirement to have at least an initial feature to allow skirmish arenas this way:

- brackets like BGs so 10-19, 20-29, etc...
- you just need to be in a party group of 1, 2, 3, 4 or 5 to join
- when you join, there should be a global announcement like "A team queued for 3v3 arena [10-19]"
- there should be a spam filter mechanism to prevent the same team to spam the message too often (the same we currently have with BGs)
- people should be able to queue from everywhere using a command such as `.arena queue skirmish`

**Comment by Cromisaid** [comment]
> I'm considering starting with a simple requirement to have at least an initial feature to allow skirmish arenas this way:
> 
> * brackets like BGs so 10-19, 20-29, etc...

Bracket should be as Blizzard established, so from 15 to 19 / 20 to 25 / 25 to 29/ etc...

Because as level 10 against a 19 u miss spells for sure, but the percentage of missed spells as 15 against a 19 is moderate lower

**Comment by FrancescoBorzi** [comment]
thanks @Cromisaid , I've added that and placed a bounty of 100$ on the implementation of this feature.

**Comment by Winfidonarleyan** [comment]
- Module https://github.com/azerothcore/mod-low-level-arena
- PR #6114

**Comment by Sedatyf** [comment]
I tested the low level arena module more in depth and everything work as Shin describe.
But @Winfidonarleyan, can you please edit your ``README.md`` to give people which command to use to tag in arena? Because we had to scrap your code to find the commands (you know ``.lla queue solo XvX`` or ``.lla queue group XvX``)

**Comment by Sedatyf** [comment]
And I think it will be important to have maybe periodic announcement to tell people they can queue in arena with those commands. Because low level characters won't tag in Gadgetzan for sure (which is working if this happened though)

**Comment by Winfidonarleyan** [comment]
> I tested the low level arena module more in depth and everything work as Shin described.
> But @Winfidonarleyan, can you please edit your `README.md` to give people which command to use to tag in arena? Because we had to scrap your code to find the commands (you know `.lla queue solo XvX` or `.lla queue group XvX`)

Okay, I'll do it.

**Comment by Winfidonarleyan** [comment]
@Sedatyf Done. https://github.com/azerothcore/mod-low-level-arena/commit/a0f31bd486c1de1a7503b03d45bfcc941e6f6c7a

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan where is the SQL part to add the new commands to the `command` table?

**Comment by Winfidonarleyan** [comment]
> @Winfidonarleyan where is the SQL part to add the new commands to the `command` table?

Added

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan there are several issues.

### Problem 1

Ally and horde cannot queue together, they should be allowed to.

### Problem 2

The current implementation is different from the requirements specified here: you just need to be in a party group of 1, 2, 3, 4 or 5 to join

> You just need to be in a party group of 1, 2, 3, 4 or 5 to join

So you just type `.lla queue` (no need for `solo`, group or `2v2`m`3v3` etc...)
- if you are without group, it will join 1v1
- if you are in a group, it will join your group according to the group size (2v2 if a group of 2, 3v3 if a group of 3, etc...)

### Problem 3

It is not working, we tried with 4 characters queued and the arena didn't start

https://cdn.discordapp.com/attachments/534503351803445291/855863127299850250/unknown.png

**Comment by FrancescoBorzi** [comment]
update:

- Problem 3 was fixed
- Problem 2 partially addressed (no 1v1 and 4v4 yet but everything else works)

Still need to fix Problem 1 (crossfaction) to be accepted

**Comment by FrancescoBorzi** [comment]
update:

### Problem 4 - the queue has some bugs

apparently there is something wrong with the queue. I don't know the exact reproduction steps at the moment, but several players queued one by one in solo. At some point, there were 6 players queued (3 ally and 3 horde), all level 39, but the Arena did not start. To start it, they left the queue and joined again in groups, then it worked.

### Problem 5 - possible crash

According to players it crashed twice in a row after they joined arena, crash dump here and I'm investigating it: https://github.com/azerothcore/azerothcore-wotlk/issues/6452

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/mod-low-level-arena
