### ISSUE TITLE
[Docker] DB service unhealthy when overriding the default MySQL password

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/azerothcore-wotlk#5431]
## STEPS TO REPRODUCE THE PROBLEM:

1. `DOCKER_DB_ROOT_PASSWORD=root docker compose up -d ac-database ` 
2. `docker-compose run --rm ac-dev-server`

You'll get the following error:

```
ERROR: for ac-dev-server  Container "075802a76c8b" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

## EXTRA NOTES:

- If you don't override anything, it works fine
- Overriding the MySQL port using `DOCKER_DB_EXTERNAL_PORT` works fine.
- Overriding the MySQL user password using `DOCKER_DB_ROOT_PASSWORD` causes the issue.

## AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/26a477dd126c68a46f265b97dd439d9982bba1d1

## OPERATING SYSTEM:

macOS

## MODULES:

None

## CUSTOMIZATIONS:

None

**Comment by Yehonal** [comment]
This is by design...you cannot change the MySQL root password in that way since probably your container was already initialized with another password.

You have to remove your container (and the volumes, thus dropping the database as well) with the following command: `docker-compose down -v`

It will remove all the containers and the related volumes. Then you can run those command you listed and they should work this time
