### ISSUE TITLE
Auction House mails don't have any gold/name info on them

### ISSUE THREAD

**Issue by locus313** [azerothcore/azerothcore-wotlk#5718]
Orginally reported at https://github.com/chromiecraft/chromiecraft/issues/558

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Auction house mails don't list any gold stats or name sof the buyers/seller.
![auction1](https://user-images.githubusercontent.com/80769357/117404538-668d4480-af0a-11eb-84b3-4ee30ae8ff18.jpg)
![auction2](https://user-images.githubusercontent.com/80769357/117404540-6725db00-af0a-11eb-93c1-14189a36af46.jpg)
![auction3](https://user-images.githubusercontent.com/80769357/117404541-67be7180-af0a-11eb-99c3-d50e28ca8b97.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Auction house mails should include the gold information and the name of the buyer/seller.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Sell or Buy any item on AH
2. See the attached mail

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by locus313** [comment]
@UltraNix could you take a look at this?

**Comment by locus313** [comment]
might need to do something similar to this:
https://github.com/TrinityCore/TrinityCore/commit/3ebcf3f1a94b6455979d6dd9091f220247950023#diff-f4f8437f4c37733502345d304c41c008bdcf9a91cc66ef269ece3a5e29b4ba44

**Comment by necropola** [comment]
The issue is caused by the ObjectGuid commit https://github.com/azerothcore/azerothcore-wotlk/commit/f4c226423dc0811efccf8135b46bc7ff46aab940

Here are the steps I took to prove it:
(0) Change worldserv.conf, authserver.conf and config.sh to use the following databases
 - acore_auth_test
 - acore_world_test
 - acore_characters_test 

(1) Create "test" branch based on last commit before the ObjectGuid patch
 - `git branch test 91081f4ad8fed98d7bdc9c0ae13d05c86032df9f`
 - `git checkout test`
 
(2) Build, install and run db_assembler with option 5. Then create a test account with a "MySeller" character and a test account  with a "MyBuyer" character

(3) Test in game
 - Put up auctions on character "MySeller"
 - Buy auctions on character "MyBuyer"
 - Check mail on "MyBuyer" -> all good
 - Check mail on "MySeller -> all good
![image](https://user-images.githubusercontent.com/7461137/117544470-e0fcb800-b021-11eb-820e-2dabc75c5550.png)
![image](https://user-images.githubusercontent.com/7461137/117544495-07baee80-b022-11eb-95aa-61bad982bd9e.png)
![image](https://user-images.githubusercontent.com/7461137/117544498-0ee1fc80-b022-11eb-9533-45363316cd5c.png)

(4) Merge ObjectGuid commit into the "test" branch
 - `git merge f4c226423dc0811efccf8135b46bc7ff46aab940`

(5) Build, install and run db_assembler with option 5

(6) Test in game
 - Put up auctions on character "MySeller"
 - Buy auctions on character "MyBuyer"
 - Check mail on "MyBuyer" -> bugged
 - Check mail on "MySeller" -> bugged
![image](https://user-images.githubusercontent.com/7461137/117544503-16a1a100-b022-11eb-9b27-72d012f017d2.png)
![image](https://user-images.githubusercontent.com/7461137/117544506-1dc8af00-b022-11eb-8145-fe70e6e1b297.png)
![image](https://user-images.githubusercontent.com/7461137/117544516-2d47f800-b022-11eb-86c8-f98cb355cb96.png)

**Comment by FrancescoBorzi** [comment]
thanks @necropola for your investigation. @UltraNix please have a look at this

**Comment by UltraNix** [comment]
@locus313 @necropola 
https://gist.github.com/UltraNix/199e77daa649228e4f949a83e36cdeba
Check this one and let me know if it got better.

**Comment by locus313** [comment]
does look like that worked:
![image](https://user-images.githubusercontent.com/4015312/117551917-628e1f00-affd-11eb-89d2-2c4fc42336de.png)
![image](https://user-images.githubusercontent.com/4015312/117551920-67eb6980-affd-11eb-93bc-e98e58466fdc.png)

**Comment by necropola** [comment]
@UltraNix Looks good. I've applied your patch to my ` test` branch (instead of current `master`). Mail bodies appear to be fixed and the extra delay when checking for mail from the AH is gone, too.

(7) Apply patch to `test` branch
- `curl https://gist.githubusercontent.com/UltraNix/199e77daa649228e4f949a83e36cdeba/raw/d5a44a80eeb5907890aac71b84f915fc1ed71cbe/gistfile1.txt | git apply -v --index`

(8) Update Test system
- Build and install binaries
- Set `MailDeliveryDelay = 180`  in `worldserver.conf` to  receive "Auction successful" mails after 3 minutes (instead of an hour) 
- Start `authserver` and `worldserver`

(9) Test in game
 - Put up auctions on character "MySeller"
 - Buy auctions on character "MyBuyer"
 - Check mail on "MyBuyer" -> fixed
 - Check mail on "MySeller" -> fixed

![image](https://user-images.githubusercontent.com/7461137/117555248-e7a92080-b05d-11eb-8257-44727fb7d011.png)
![image](https://user-images.githubusercontent.com/7461137/117555256-f8599680-b05d-11eb-8432-b6344d9938ce.png)
![image](https://user-images.githubusercontent.com/7461137/117555264-10311a80-b05e-11eb-9fb5-df0cd2490450.png)
![image](https://user-images.githubusercontent.com/7461137/117555269-17f0bf00-b05e-11eb-9648-f79ba257d64f.png)

**Comment by UltraNix** [comment]
@FrancescoBorzi Can you commit the changes? I'm working on other branch, so I don't wanna mess up with changes.

**Comment by necropola** [comment]
We need a PR anyway, right? If it is just this one change, I'm happy to create it.

**Comment by locus313** [comment]
> @FrancescoBorzi Can you commit the changes? I'm working on other branch, so I don't wanna mess up with changes.

pr has been created. Thanks, @UltraNix for the quick fix.
