### ISSUE TITLE
Core/ItemScript: Goblin Gumbo Kettle cause AuraScript error

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#576]
**Description**: This error is reported by worldserver.exe when using the Goblin Gumbo Kettle item (ID: 33219).

>TSCR: Script: `spell_item_goblin_gumbo_kettle` Spell: `42760` AuraScript::PreventDefaultAction called in a hook in which the call won't have effect!

**Expected behavior:** 
No errors!

**Steps to reproduce the problem:**
Use the item and click on it.

**Reference**
http://www.wowhead.com/item=33219/goblin-gumbo-kettle

**Branch:**
Master

**Commit Hash:** 
 f353f9b5bb08cde4d75b13c1c1c33ae35da971b4

**Comment by d3tr0l** [comment]
This thing is not working properly too... https://www.wowhead.com/item=33219/goblin-gumbo-kettle#comments The buff should cause you to burp randomly, which works. But the burp should cause you to lose any "well fed" buff you have active and it does not work here. The well fed bug should be removed when burping, it does not work. I have this item on retail, funny, but garbage :D because you pay for something that just removes your well fed buff.

**Comment by d3tr0l** [comment]
I would like to work on a fix for this, since this item should be used by players in some "recreational" way and not inside raids etc. But idk where to look for the effects and mechanics, in which file. I will take a look around in the whole core code, but if anyone has some hint for this i would greatly appreciate that.

**Comment by BarbzYHOOL** [comment]
If they use inside raids what happens? they don't gain anything, they just lose something

Better focus on fixing the console error or another bug :P

**Comment by d3tr0l** [comment]
yes but the console output error for this gets fixed if the remove well fed gets proper checks and conditions and it would be working, then the console output should be gone. aura error, propably some conditions checks are screwed here for this.

**Comment by Si1ker** [comment]
No errors on the console. Closing as invalid.

![image](https://user-images.githubusercontent.com/61223313/113659681-cff60b00-965f-11eb-88eb-0f6c7cc24daf.png)

**Comment by TheDiscordian** [comment]
I'm currently experiencing this bug:

```
Script: `spell_item_goblin_gumbo_kettle` Spell: `42760` AuraScript::PreventDefaultAction called in a hook in which the call won't have effect!
```

I'm not sure why the error doesn't appear for @Si1ker, does the well fed buff remove too?

**Comment by wefgame** [comment]
++ Script: `spell_item_goblin_gumbo_kettle` Spell: `42760` AuraScript::PreventDefaultAction called in a hook in which the call won't have effect!

**Comment by wefgame** [comment]
class spell_item_goblin_gumbo_kettle : public AuraScript
{
    PrepareAuraScript(spell_item_goblin_gumbo_kettle);

    void CalcPeriodic(AuraEffect const* /*effect*/, bool& isPeriodic, int32& amplitude)
    {
        isPeriodic = true;
        amplitude = urand(10 * IN_MILLISECONDS, 40 * IN_MILLISECONDS);
    }

    void Update(AuraEffect* effect)
    {
        effect->SetPeriodicTimer(urand(10 * IN_MILLISECONDS, 40 * IN_MILLISECONDS));
        if (Unit* owner = GetUnitOwner())
            owner->CastSpell(owner, 42755 /*Goblin Gumbo Trigger*/, true);
    }

    void Register() override
    {
        DoEffectCalcPeriodic += AuraEffectCalcPeriodicFn(spell_item_goblin_gumbo_kettle::CalcPeriodic, EFFECT_0, SPELL_AURA_PROC_TRIGGER_SPELL);
        OnEffectUpdatePeriodic += AuraEffectUpdatePeriodicFn(spell_item_goblin_gumbo_kettle::Update, EFFECT_0, SPELL_AURA_PROC_TRIGGER_SPELL);
    }
};
