### ISSUE TITLE
Chunks of meat in the pristine Stormwind Moonwell

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#5817]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

I have noticed that in the moonwell of Stormwind, there are some objects that should not be corrupting the pure waters of the place, I don't think the druids have either approved or thrown it there themselves ^^
##### EXPECTED BLIZZLIKE BEHAVIOUR:

No object should be at the bottom of the pool.
##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the Stormwind park.
2. Look at the moonwell bottom.
3. See if the described issue exist.

##### EXTRA NOTES:
![WoWScrnShot_051221_060445](https://user-images.githubusercontent.com/82579073/118088404-b0c16a80-b3cf-11eb-8f71-8564e4849449.jpg)

It is tagged as 'moonwell' when you point at it with the cursor.

**AC HASH/COMMIT:**
 
e4510ba01b61

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

Local AC setup

**Comment by Kitzunu** [comment]
Dont ignore adding your current hash number

**Comment by Eldarix** [comment]
Sorry, didnt intend to ignore anything :D where i found it ?

**Comment by FrancescoBorzi** [comment]
@Eldarix just check your `.server info`, it should match with a commit hash (found in the commit URL as well). For example:

https://github.com/azerothcore/azerothcore-wotlk/commit/f6c6123d85d467134ee24565c9d98efdfc3a0c41

**Comment by Eldarix** [comment]
![WoWScrnShot_051321_004141](https://user-images.githubusercontent.com/82579073/118136655-05370b00-b40d-11eb-9a2c-2c6400b468fc.jpg)

so i must enter the azeroth core rev. that appears there ? i just never needed to do anything in relation in all these last reports.

**Comment by Kitzunu** [comment]
![SmartSelect_20210513-160843_Chrome](https://user-images.githubusercontent.com/24550914/118137474-87233600-b405-11eb-97c5-c889e98adcb0.jpg)

**Comment by Eldarix** [comment]
Sorry i wasn't at my computer until now again, i can't find it, i suppose in the other issues it was automated because i take it from the original chromie reports or something ?

if you can explain to me more precisely how to get the hash/commit i put it, i'm useless and hopeless almost always if you don't explain in detail to me :D

**Comment by Branel** [comment]
In your chat after you type .server info it says AerothCore rev. `e4510ba01b61`
If you type out that number that comes after rev. it will look like this e4510ba01b61 (automatically converts to a shorter number, and makes a reference)

So everytime you are posting a issue and you are the original author you need to write .server info and write the revision that your server is on so that it is more easier to make sure that everybody is on the same page, i.e you could have a outdated server that has the issue already fixed.

**Comment by Eldarix** [comment]
Branel now i see :), okey i correct it now and it's good as well to know for the subsequent.
