### ISSUE TITLE
Bug Spell Drain Soul [Warlock]

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#5935]
## CURRENT BEHAVIOUR:
Warlock spell when we click on npc
Soul Shard does not

## EXPECTED BLIZZLIKE BEHAVIOUR:
Must be on all npc
What we do
give soul shard

## SOURCE:
![WoWScrnShot_051821_190942](https://user-images.githubusercontent.com/80007195/118673020-ec17cb00-b80d-11eb-9a4d-dae3924e7014.jpg)
![WoWScrnShot_051821_191103](https://user-images.githubusercontent.com/80007195/118673045-f0dc7f00-b80d-11eb-8522-2f9a0e30147a.jpg)
![WoWScrnShot_051821_190834](https://user-images.githubusercontent.com/80007195/118673083-f76af680-b80d-11eb-8e33-6ff3d526c0f3.jpg)

## EXTRA NOTES:
AC HASH/COMMIT:
rev. 7fa1cb1+ 2021-04-29 15:07:03 +0200

## OPERATING SYSTEM:
Windows Server 2019 Standard

## MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by arielcami** [comment]
Good day my friend, I think is not a bug.
You're trying to get a soul shard from a target that won't report any experience/honor to you.

## Screenshot
![drain soul](https://user-images.githubusercontent.com/71854140/118684680-09c24180-b7c8-11eb-9d7d-0f7aadc5bbe1.jpg)

So you won't be able to get a Soul shard from a target which level is displayed in Gray (10 levels lower than you.)
I understand your confusion, because I also remember the Drain soul ability
creating soul shards from any target. Well, that was the bug.

It's working properly in Azerothcore!  Good day.
