### ISSUE TITLE
Pet Warlock Attack Problem Name : Summon Felguard

### ISSUE THREAD

**Issue by poryagholami1374** [azerothcore/azerothcore-wotlk#6065]
### CURRENT BEHAVIOUR:
Pet Warlock Name : Summon Felguard
He hits the target only once and then does not attack again
Ctrl 1
I tested the other 4 and there was no problem
Only this one is broken

### SOURCE:

https://user-images.githubusercontent.com/80007195/119735447-9092b080-be91-11eb-84e6-141fed4d6804.mp4

### AC HASH/COMMIT:
rev. 579dbe1e5ffc+ 2021-05-31 17:05:09

### OPERATING SYSTEM:
Windows Server 2019 Standard

### MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

**Comment by Kitzunu** [comment]
Maybe I can take a look later

**Comment by poryagholami1374** [comment]
> Maybe I can take a look later

I have provided my reports, but no one is looking, even if my reports are accurate and include pictures and clips.
To make it easier to understand

**Comment by Sedatyf** [comment]
Everyone is working on their free time. As you can see, there is a lot of opened issues (698 at the time of writing), so indeed, no one is looking to your issues, not because of you, but because there is a lot of work in general. So be patient. If you want to speed up things, you can place a bounty on your issue: [BountySource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)

**Comment by FrancescoBorzi** [comment]
> I have provided my reports, but no one is looking

I have provided [my tutorials](https://www.azerothcore.org/wiki/How-to-test-a-PR) so if you want to help in speeding up the development, you can help by testing PRs.

Currently, 30 PRs are waiting to be tested and the devs are just waiting for users to test them :)

**Comment by poryagholami1374** [comment]
> > I have provided my reports, but no one is looking
> 
> I have provided [my tutorials](https://www.azerothcore.org/wiki/How-to-test-a-PR) so if you want to help in speeding up the development, you can help by testing PRs.
> 
> Currently, 30 PRs are waiting to be tested and the devs are just waiting for users to test them :)

explanations
it's hard for me
Posts have no photos or videos
I can not understand what it means
To test
If there is something that has an image and it is easy to understand, send it to me to test

**Comment by poryagholami1374** [comment]
I tried this again, sometimes it hits 3 to 4 npc and can no longer work
It may work well in ions. You should test on low level npcs

**Comment by FrancescoBorzi** [comment]
> If there is something that has an image and it is easy to understand, send it to me to test

@poryagholami1374  testing that a PR does not introduce new bugs is also valid testing.

**Comment by Kitzunu** [comment]
I have added this to My todo list

**Comment by poryagholami1374** [comment]
I thoroughly tested this
And all levels from 1 to 80 npc
It strikes once
It doesn't work anymore
The pet has a problem

**Comment by Azcobu** [comment]
Confirming that this is actually a problem in certain rare circumstances:

https://user-images.githubusercontent.com/81782124/121350489-ea06df00-c969-11eb-8ada-e9fcbf749f04.mp4

The problem seems to be the Felguard's Intercept ability. **If it one-shot kills the target**, as it is doing with these very low level mobs, the Felguard's attack seems to lock up and it gets stuck. From there on, the only thnig to do was relog or resummon the pet. Even swapping to passive or trying to use other FG abilities didn't help.

Normal fights, where it doesn't instantly kill the enemy NPC with Intercept, work fine. This is a rare case, because most NPCs will not die in one hit as these are.

I was suggest changing the title of this issue to something like "Felguard's Intercept Ability Prevents Other Actions On Instant Kill."

**Comment by Sedatyf** [comment]
Thank you @Azcobu 🚀
