### ISSUE TITLE
Thousand Needles - Various Doubled/Too Close Ore Veins Spawns

### ISSUE THREAD

**Issue by Azcobu** [azerothcore/azerothcore-wotlk#6092]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/717

There are many mining veins spawned within 10 yards where 2 veins can be mined from same spot.
Double Spawns:
 GUID 6524 & 17159
![double_6524_17159](https://user-images.githubusercontent.com/80769357/119983075-f715ec80-bfbf-11eb-985d-e182256513e9.jpg)

GUID 5467 & 6163
![5467_6163](https://user-images.githubusercontent.com/80769357/119983187-1b71c900-bfc0-11eb-8543-b06ef953ceb4.jpg)

Close Pairs:
GUID 5088 & 120789
![5088_120789](https://user-images.githubusercontent.com/80769357/119983240-2f1d2f80-bfc0-11eb-916a-a9cc039622f5.jpg)

GUID 5847 & 120627
![5847_120627](https://user-images.githubusercontent.com/80769357/119983331-4d832b00-bfc0-11eb-92fe-cc6e1d412d45.jpg)

GUID 6353 & 17169
![6353_17169](https://user-images.githubusercontent.com/80769357/119983380-5d9b0a80-bfc0-11eb-94fb-ad39e020cee6.jpg)

GUID 6051 & 6743
![6051_6743](https://user-images.githubusercontent.com/80769357/119983432-71467100-bfc0-11eb-8e86-7f1953e395f7.jpg)

same for these, just don't wanna spam too many screenshots:
GUID 4933 & 5146
GUID 5985 & 17091
GUID 6089 & 120812 & 5982
GUID 6152 & 6016
GUID 6318 & 17166
GUID 6631 & 6332
GUID 6685 & 17226
GUID 17161 & 5813
GUID 17195 & 6560
GUID 17227 & 6157 & 6625
GUID 120397 & 6299
GUID 120405 & 5972

Tester's notes: Visited all these, confirming that they probably should be pooled.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mining Nodes don't spawn in close pairs/clusters simultaneously.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Have mining and track minerals on and run around thousand needles
2. Or Teleport to provided Guids and see the dense spawns of node veins

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by Stump876** [comment]
I believe this is blizzlike, and more of a spawning issue on AC. On retail occasionally I would happen upon double veins (one on top of another) or veins close together like this. It wasn't frequent, but it did happen, and it was memorable because it always felt like hitting the jackpot. Look at the first comment [here](https://classic.wowhead.com/item=2770/copper-ore#comments). "camps with 2 or 3 veins" 

I also believe that on AC there are just too many veins spawned all at once. I believe the spawn points are correct, however it just seems like too many.  I mentioned this theory somewhere else but I can't seem to find it. I can find maps of nodes and data from gatherer addons, but I can't find anywhere that shows how mining is supposed to work. I'm not even sure how it was implemented into the current core and where those numbers came from. I have no proof of this concept, nor I'm not sure if this is even do-able. But my thought is this:
 
Just pulling random numbers for example. Say there are 100 possible spawn points for ore, some are close to each other. So AC spawns all 100 veins, because these are verified veins, they are in the DB. One is mined. X amount of time passes and it's respawned. Although this is correct behavior, it just seems like there are way too many veins and the ones close together are errors. Which is what we have now.

Now going back. If out of the 100 Possible spawn points, only 50% were to spawn or 66% (pick a number). As they are mined the respawn timer would tick as normal, but then respawn randomly out of those 100 spawn points back up to the 50% mark. This would explain gatherer data, and all the mining maps, the double veins, and ones close to each other, and it would not be as overwhelming seeing 100 nodes all at once.

I also believe the amount of silver/gold/truesilver veins are too many. These were typically rare. Again this going back to spawning. [Silver veins are a rare spawn of tin](https://wowpedia.fandom.com/wiki/Silver_Vein), [Gold veins appear uncommonly wherever iron deposits are found](https://wowpedia.fandom.com/wiki/Iron_Ore), [Truesilver Deposits rarely spawn in place of mithril or small thorium veins](https://wowpedia.fandom.com/wiki/Truesilver_Deposit). Not to say every node can spawn a rare ore spawn. There is data saying where these should typically spawn. But right now it's kind of hard wired that "this mining node spawns silver 100% of the time" and we will occasionally see the double spawn REF: [https://github.com/azerothcore/azerothcore-wotlk/issues/5513](https://github.com/azerothcore/azerothcore-wotlk/issues/5513) I believe this spot should be one of the spots for chance to spawn silver. If you factor that in into the above 50% respawn equation with a 10% chance to spawn a "rare spawn" at the assigned spawn point. (90% chance for tin, 10% chance for silver in this case for Silverpine) That would make those green ores more rare.

**Comment by Azcobu** [comment]
What you're talking about here is the node pooling system, which is still being worked on. The point of this issue and others like it is to document nodes that should be pooled (rather than deleted) so we don't see 100% of them all at once.

**Comment by Stump876** [comment]
OK I gotcha. I wasn't sure how they were being fixed, and I wanted to call attention to the bigger picture instead of dealing with them one at a time.
