### ISSUE TITLE
Core/Script: Upper Blackrock Spire Father Flame event does not start.

### ISSUE THREAD

**Issue by StygianTheBest** [azerothcore/azerothcore-wotlk#611]
**Description**:  Looting Father Flame from the obelisk does not start the event to fight  Solakar Flamewreath.

**Expected**:
> In order to start the event to summon Solakar Flamewreath you will need to loot the Father Flame on the western side of the room. After you loot the Father Flame it will start an event and waves of Dragonkin will come out at you. After you fight off all the waves Solaka Flamewreath will yell out then come running.

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

**Comment by gtao725** [comment]
The issue still exists as of commit hash 7eb703e. almost 2 years lol...

**Comment by Pondaveia** [comment]
@gtao725 It ain't forgotten, I'll give an update soon.

**Comment by Zoidwaffle** [comment]
Maybe some inspiration/info can be here: https://github.com/TrinityCore/TrinityCore/issues/19370 but it's not something that can, currently, be used directly.

**Comment by Shineslippers** [comment]
Some vids
https://youtu.be/usD4PsDX1N4?t=603
https://youtu.be/srDqhx5oGF0?t=923

Wowhead [comment](https://www.wowhead.com/npc=10264/solakar-flamewreath#comments:id=1091101)
>By Kasa24 on 2010/07/29 (Patch 3.3.5)
Walk in and head to the left - it doesn't matter whether you kill the two guards or not - and you will see a glowing crystal near the wall. Click it as to loot, and you can get Father Flame. By right clicking it you'll see a yell, and two dragonkin will come to attack you. There are 6 waves of two dragonkin each, with about 30 seconds of downtime between them (as I did this on my 80 pally not sure if its 30 seconds from the time you kill them or the time that they spawn, since I killed them almost instantly). After the 6th wave Solakar will yell at you and spawn.
