### ISSUE TITLE
use gm command does not work that about talent...

### ISSUE THREAD

**Issue by xengine-qyt** [azerothcore/azerothcore-wotlk#6235]
**CURRENT BEHAVIOUR:**

input gm command to game windows..
.learn all my pettalents
.learn all my talents
not work or not i want to want....

**EXPECTED BLIZZLIKE BEHAVIOUR:**

learn all talentpoints in talent template and not learn a part of half of each talent
.modify talentpoints is clear when i logout...that is not useful

I want to be like trinitycore 

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

**EXTRA NOTES:**

**AC HASH/COMMIT:**
Commits on Jun 4, 2021 
196f74f

**OPERATING SYSTEM:**
WIN10 x64..

**MODULES:**
is not 

**CUSTOMIZATIONS:**

**Comment by Tinywolf69** [comment]
Greetings,

I have verified that these issues are still present. Here are the steps I followed:

1. Created new character named Dummy (Warrior)
2. Used the GM command **.char level 80** to bring the character level to 80 (**Command is working as expected**)
3. Used the GM command **.learn all my spells** to ensure that any dependencies are met (**Command is working as expected**)
4. Used the GM command **.learn all my talents** in order to max all the character talents (**Command is not working as expected**)
5. I restated the **AuthServer**, **WorldServer**, and the **client**
6. Upon opening the talent window for character Dummy, I noticed that partial talent scores were implemented
7. I added additional talent points manually to max all talents, but upon restart of the client it reverted to the previous state

I have attached images showing the before the command was executed, the after the command was executed, and the WorldServer console print-out.

![Pre-command](https://user-images.githubusercontent.com/83475687/205989828-04f70bab-b82d-4a0d-a09d-f96f3aed94dc.JPG)

![Post-command](https://user-images.githubusercontent.com/83475687/205989863-bb1afeac-b25c-472d-b9a3-0920abb99a02.JPG)

![WorldServer-Output](https://user-images.githubusercontent.com/83475687/205989889-7887a595-60c2-4ee6-986b-ff751adf97d7.JPG)
