### ISSUE TITLE
Pathing for interact with target

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/azerothcore-wotlk#6292]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Automatic pathing towards an NPC while using the "Interact with target" feature is currently broken on slight slopes and in tight paths. While clicking the ground always works, approaching a unit does nothing.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It should always be possible to engage/approach a unit when pressing the Interact with target key. This worked flawless in Classic.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to a slight slope or tight path like in the examples below.
2. Target an NPC and use the button for "Iinteract with target" while "Click to move" is enabled

##### EXTRA NOTES:

In the example videos, every press on button f or 2 triggers the client side command "Interact with target" for the warrior and paladin. This usually makes them run towards the target.
Note how clicks on the ground work (Click-to-move) but not the "Interact with target"

Example for slope: https://www.twitch.tv/videos/1051005420?t=00h05m32s (also next packs)
Example for tight path 1: https://www.twitch.tv/videos/1051005420?t=00h02m05s
Example for tight path 2: https://www.twitch.tv/videos/1051005420?t=00h08m23s
Example for tight path 3: https://www.twitch.tv/videos/1051005420?t=00h26m28s

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by tkn963** [comment]
I have only encountered this in certain instances, like Zul'Farrak in the videos. As a multiboxer myself, these kinds of issues always trigger me. I'm not sure this is due to the terrain itself but something in the maps/mmaps that isn't quite matching up. Sunken Temple also has this issue from time to time. Never had it happen so far in the open world

**Comment by tkn963** [comment]
My point is if it were to be related to slopes etc it would occur in more places and not just specific instances. I could scan through my uploaded videos and see if I remember other instances having this issue

**Comment by 55Honey** [comment]
> My point is if it were to be related to slopes etc it would occur in more places and not just specific instances. I could scan through my uploaded videos and see if I remember other instances having this issue

Please do! i remember this happening it Gnomerregan on the ramps where the trash dwarfs place bombs as well.

> By the way @55Honey how are you not banned on Twitch? Their rules supposedly say you can't stream private servers, which is why I haven't been streaming it :P

I assume twitch does not care about 0 follower channels.

**Comment by tkn963** [comment]
I'll list the ones I remember right now. I'm going to start gearing up my setup soon so I'll be testing the wrath dungeons thoroughly

I can't say exactly where the issues occur in the instances because I have no reliable way of doing so. I can link the video I have of it having these issues if it's requested. This is merely my discovery of these issues.

Zul'Farrak has the most amount of issues of all instance I've run through so far. It's everywhere (ps: multibox melee characters in this one if you want to hate yourself)
Razorfen Kraul has issues
Razorfen Downs has issues
Sunken Temple has many issues, also randomly all over the dungeon
Scarlet Monastery has a few issues, not much but occurs from time to time
Utgarde Keep has a few issues, some occur on flat terrain but are rare enough that it's not a priority
Uldaman has a few issues, most noticably in the areas where the scorpions are

**Comment by UltraNix** [comment]
I don't get it at all.
What is `"Interact with target" feature` and `"Click to move" is enabled`???

**Comment by 55Honey** [comment]
![image](https://user-images.githubusercontent.com/71938210/127227969-c7254e7f-35c5-42b3-872b-31ad35eeb0fc.png)
`Interact with Target` is a client function. When used the character interacts with the target, e.g. open a chatbox.

![image](https://user-images.githubusercontent.com/71938210/127228164-837dd6a0-fc11-4e39-b9f8-589494cd67da.png)
`Click-to-Move` is also a client feature, which allows to click the ground with the mouse and make the character move to that position.

**Comment by UltraNix** [comment]
Both options are clientside and client decides where to go. There is nothing I can do with it. 
This is completely independent from serverside code.

**Comment by 55Honey** [comment]
It works on other cores as Well as retail. I suspect it's either our maps, or the cores logic.

But this problem is very low priority in my opinion.

**Comment by UltraNix** [comment]
As I said - there is no core logic as it's a client packet send to server with movement position.

**Comment by 55Honey** [comment]
Unfortunately i never got to know what core these servers were using. They were private servers i played like 2 years ago for a very short period of time. Since you say there is no relation to server-side maps/scripting, i must have been wrong and it seemingly just never happened.

If you say it's not possible to do something about it, let's close it.
