### ISSUE TITLE
hashbringer

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#635]
**Description**: in last even of DK

**Current behaviour**: Tell us what happens
Thirion get the ashbringer, but the wrong version.

**Expected behaviour**: Tell us what should happen instead
The animation would have to transform in light version

![wowscrnshot_091417_142936](https://user-images.githubusercontent.com/31663279/30450088-1ceb5f70-9991-11e7-99b2-9ba3ec3e2724.jpg)

**Steps to reproduce the problem**:

1. do quest 
2. 
3. 

**Branch(es):** Master

**AC hash/commit**: 9d2395e

**Operating system:** Ubuntu server 16.04.03 LTS

**Modules:** Are you using modules? if yes, list them

**Other Customizations:** Are you using any core/db patches or other customizations? If yes please specify them here.

**Comment by talamortis** [comment]
please can you provide the following information

QuestID:
CreatureID:

Please do these ingame as they might be differrent ID's for each event.

**Comment by Maurowin** [comment]
@talamortis QuestID : 12801 (The Light of Dawn)
https://www.youtube.com/watch?v=YP8nbf9TBso

CreatureID: i don't know.

**Comment by talamortis** [comment]
thank you I'll see what I can find 👍

**Comment by Gargarensis** [comment]
I've found that in the table creature_equip_template the item assigned to Tirion is the Corrupted Ashbringer instead of the Ashbringer.

I don't know if it should be like this (maybe the "purification" would come from a spell), but if no one knows how to fix this issue in the correct way, we can change the item to 13262 should be the right one) or 50442 (i think this one is used in Icecrown Citadel, so it might be the wrong entry).

I've seen some videos and the Corrupted Ashbringer is never shown on Tirion so this fix might be safe.
I will PR as soon as I can.
