### ISSUE TITLE
Feature: use std::chrono

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/azerothcore-wotlk#6490]
![image](https://user-images.githubusercontent.com/24550914/137370596-d28934bc-8833-40eb-b314-960bb0c0d9d3.png)

We should start replacing events where we use time like "x * IN_MILLISECONDS" to std::chrono instead

Example: https://github.com/azerothcore/azerothcore-wotlk/pull/6489

**Comment by Winfidonarleyan** [comment]
yes

**Comment by Eronox** [comment]
> > so I dont have to swap them when I see them in code?
> 
> I don't know what you mean?

The origin intent is to change the current way of defining times to use the chrono system instead, like so: 
https://github.com/azerothcore/azerothcore-wotlk/pull/8498/files

Your PR seems to be making this unneccessary, that instead todays way will be just changed to chrono, instead of manually changing each code part one stumbles upon to chrono.

At least this is what I think he meant 😄

**Comment by Winfidonarleyan** [comment]
About this, i think if we convert everything to std::chrono, the arguments that some functions require will become clearer and there will be fewer mistakes from developers

**Comment by Nyeriah** [comment]
Yeah, it's much more readable and way more pratical to use. Looking forward to this.

**Comment by Kitzunu** [comment]
I think this issue serves no purpose anymore.

It is well known that std::chrono is preferred at this point
