### ISSUE TITLE
(DB) World database update error

### ISSUE THREAD

**Issue by claudiodfc** [azerothcore/azerothcore-wotlk#6509]
**CURRENT BEHAVIOUR:**

When creating a new world database and importing world update sql file I get this error:

![image](https://user-images.githubusercontent.com/54484196/122957968-57f3d300-d37a-11eb-91b3-8f6e3ec08d4b.png)

**EXPECTED BLIZZLIKE BEHAVIOUR:**

No error

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Drop world db
2. Create world db
3. Import files for base and update
4. Error

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
AzerothCore rev. 5787d00d545a
**OPERATING SYSTEM:**

Windows 10
**MODULES:**

No
**CUSTOMIZATIONS:**

Models

**Comment by arielcami** [comment]
I strongly recommend you to use the the db_assembler.sh
in YourSourceCode/apps/db_assembler
![assebler](https://user-images.githubusercontent.com/71854140/122968531-40542480-d351-11eb-9554-28664c9402ca.png)

option 5: Creates, Fills up and Updates all databases.

Your error happens because you are missing one update
that modifies that particular column.

**Comment by claudiodfc** [comment]
I don't like using the import because it said something about no permission to do so. Nonetheless I did assemble all update files and if you do this from scratch you will get this error.

**Comment by Kitzunu** [comment]
Can you give me the contents of the line it errors on is?

**Comment by Kitzunu** [comment]
havent heard antyhign bout this, so gonna close
