### ISSUE TITLE
Missing gossip for NPC Eralan (saleswoman in Tranquillien)

### ISSUE THREAD

**Issue by ghost** [azerothcore/azerothcore-wotlk#6614]
**CURRENT BEHAVIOUR:**

![WoWScrnShot_062721_173429](https://user-images.githubusercontent.com/82579073/123548646-51949b00-d76e-11eb-95f4-1ec4cfc365d6.jpg)

Directly opens the sales interface when you interact, but in the original has something to say.

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Transcription of the original:

-Eralan appears to be chewing on some deathweed.-

If you're looking to make a love potion, you've got the wrong place. Blinding, crippling, and killing is my business and hopefully yours.

**SOURCE:**

![WoWScrnShot_062721_172730](https://user-images.githubusercontent.com/82579073/123548563-e8ad2300-d76d-11eb-9634-1aae017e93ff.jpg)

**STEPS TO REPRODUCE THE PROBLEM:**

1. Go to Tranquillien (Npc data on the screenshot)
2. See if she says something.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 

2a2e54d8c586

**OPERATING SYSTEM:**

Windows 10 21H1 

**MODULES:**

No.

**CUSTOMIZATIONS:**

None.

**Comment by MathematicalWTF** [comment]
The texts and IDs are inside the database. What I don't understand is why they don't work. I tried different methods and none of them worked.

**Comment by Eldarix** [comment]
This is how claudio fixed a similar one:

https://github.com/azerothcore/azerothcore-wotlk/pull/6381

**Comment by MathematicalWTF** [comment]
It was exactly what I did. What's more, I even tried a number of different things that didn't work either.

**Comment by Eldarix** [comment]
In that case no idea mate :D

**Comment by Efymer** [comment]
Hey boys I couldn't resist to take a look into this issue and I found something really curious.

If you filter creature_template with this query:

`SELECT entry, npcflag, gossip_menu_id FROM creature_template WHERE npcflag = 385`

You get a list of NPCs that should have this attributes: GOSSIP, VENDOR and VENDOR_AMMO.

However, if you visit them one by one ingame, you will notice that none of them shows the gossip, but instead it just sells stuff directly.

Now, if you filter by: 
`SELECT entry, npcflag, gossip_menu_id FROM creature_template WHERE npcflag = 387`

You get a list of NPCs that should have this attributes: GOSSIP, VENDOR, VENDOR_AMMO AND **they are also QUEST_GIVERS**

And what's my surprise? SOME of them will show the gossip ONLY if they have a quest to offer.

Example:

**Quartermaster Lewis** - NPC ID 491 with npcflag = 387

![WoWScrnShot_062821_215535](https://user-images.githubusercontent.com/79163132/123696069-9fd39800-d85b-11eb-94a3-25e6b10dde43.jpg)


**Quartermaster Lymel** - NPC ID: 16187 with npcflag = 387 WITHOUT a quest (quest not showing because of requirements and she should show a gossip accordingly https://wowpedia.fandom.com/wiki/Quartermaster_Lymel)

![WoWScrnShot_062821_215717](https://user-images.githubusercontent.com/79163132/123696759-63546c00-d85c-11eb-9660-d741dc722309.jpg)



So its weird, npcs will only show their gossip if they have a quest to offer as well......

**Comment by Eldarix** [comment]
Well done Efymer :) and nice finding, sure it will help to resolve it in the grand scale.

**Comment by Eldarix** [comment]
And i suppose now that i look it in detail, that in relation to that is the 'has gossip (1)' in the npc info

**Comment by claudiodfc** [comment]
Thank-you all for the feedback. Taking a serious look into this. 👍🏼

**Comment by malcrom** [comment]
Core should be using Type Flags: 134217728 (ForceGossip) to display gossip. Values in database are correct.

**Comment by yuzifc** [comment]
probably fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/9962
