### ISSUE TITLE
Sergent Bly in Zul Farrak has double chat options

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#6700]
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/1069

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

After rescuing Sergeant Bly from and clearing the mobs, when talking to Sergeant Bly to start his encounter he has two options.
![SeargeantBly](https://user-images.githubusercontent.com/80769357/124366146-c9226880-dc4d-11eb-909d-43195f5ea2b7.jpg)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should only be 1 option when talking to him

##### SOURCE:

https://blizzardwatch.com/gallery/zulfarrak?slide_pos=9

##### STEPS TO REPRODUCE THE PROBLEM:

1. GO to Zul Farrak and do the dungeons up to the point where you have to fight Sergeant Bly
2. Talk to him and notice he has two conversation options

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

**Comment by buddiman** [comment]
There are two entries for the corresponding MenuID in `gossip_menu_option`.
![grafik](https://user-images.githubusercontent.com/10009755/124385172-f6fec000-dcd4-11eb-8d0f-a66d04103c7b.png)

The only difference is that the second entry has a linked broadcast text.  (And one more whitespace which doesn't seem to be visible ingame) I think there should be only the second option. 

But I can't test it right now because the whole fight doesn't work as it's supposed to. While testing https://github.com/azerothcore/azerothcore-wotlk/issues/6696 occured several times. Sergeant Bly has the Gossip option already while he is in the cage, I think this shouldn't be the case. I'm gonna look into this later.
