### ISSUE TITLE
[Spell] Autocast for The Imp's Fire Shield Spell Doesn't Work

### ISSUE THREAD

**Issue by Eldarix** [azerothcore/azerothcore-wotlk#6858]
Original report: https://github.com/chromiecraft/chromiecraft/issues/1141

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Autocast for Fire Shield (https://wowgaming.altervista.org/aowow/?spell=2947) doesn't autocast the spell on the owner of the imp nor other party members within range.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When autocast is on for Fire Shield (https://wowgaming.altervista.org/aowow/?spell=2947) it should autocast the spell on the owner of the imp and all party members within range. 

##### SOURCE:

It has always worked like this. When you turn on autocast on Fire Shield, it should "autocast" Fire Shield on the owner and other party members within range. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Be a warlock.
2. Summon an imp.
3. Turn on autocast for Fire Shield.

##### EXTRA NOTES:

https://user-images.githubusercontent.com/25198252/125089387-ed27f300-e100-11eb-9729-cb2c16f895e9.mp4

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: dc76e6b) :

![WoWScrnShot_071021_085052](https://user-images.githubusercontent.com/82579073/125153430-496c3080-e15c-11eb-84f2-778b73ca1a74.jpg)

**Comment by Azcobu** [comment]
I think you need a better source for this issue than the player saying "It has always worked like this." That's not evidence or a source, it is a bare assertion with no proof to back it up. As triagers we are supposed to be checking and verifying bug reports, not just accepting whatever they say.

The Wowwiki entry for Fire Shield says "When set to auto-cast, the Imp will cast this on any party members within 30 yds **if they receive a melee attack**." - https://wowwiki-archive.fandom.com/wiki/Fire_Shield?oldid=2394971 and Wowpedia says the same thing. A post on Blizz forums also says "The imp only autocasts fire shield if a party member is taking damage within range... It won’t passively buff people up, only reactively." (https://us.forums.blizzard.com/en/wow/t/imp-pet-not-casting-fire-shield-automatically-with-autocast/305443) These all suggest to me that we're seeing expected behaviour here.

That's from one Google search, I'm sure you can find more. But please try to to take the time to look for actual sources and check the player's claims in future. I'll leave the ticket open in case you want to do further testing on Fire Shield and verify exactly how it behaves.
