### ISSUE TITLE
[QUEST] button doesn't work for this quest

### ISSUE THREAD

**Issue by Maurowin** [azerothcore/azerothcore-wotlk#726]
**Description**:

**Current behaviour**: Tell us what happens

When i clic on complete the windows don't propose next quest. If we need close the widow we must press ESC.

![wowscrnshot_120617_082916](https://user-images.githubusercontent.com/31663279/33650361-f4f4599c-da61-11e7-8668-8879a4703bbd.jpg)
![wowscrnshot_120617_083523](https://user-images.githubusercontent.com/31663279/33650362-f508d28c-da61-11e7-97a6-7ce82b350ac3.jpg)

**Expected behaviour**: Tell us what should happen instead

When i clic on "complete quest" the windows must propose next quest.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: 2979fd6c1f7d+ Master

**AC hash/commit**:  

**Operating system**:  Windows10

**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Zvertk69** [comment]
I have confirmed that this problem does exist on the core, I used Talamortis's test server and came up with the same problem. The quest is still do able just that the quest window stays open after hitting complete. In order to close the window you need to hit ESC (key) or just simply hit the X in the corner of the quest window. The two quests them selves is not broken in the sense that it is not able to be complete.

Quest names 
- Find the Lost Guards - ID: 37
-  Discover Rolf's Fate - ID: 45
This is what I found as the ID's ofc since I help GM for him and test quests out.

**Comment by Trystanosaurus** [comment]
Just to bump this issue, it's still happening (I'm on 825a62b)

It also seems to be for all quests where you hand in to a game object and get the follow up from the same game object. Instead of being able to click complete and the next quest shows up you have to close the quest pane and then re-use the game object to pick up the follow up quest.

**Comment by Maurowin** [comment]
Atm it's still happening.
