### ISSUE TITLE
Unmount\Mount when traveling by ship or zeppelin

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#7335]
### Current Behaviour

Unmount\Mount when traveling by ship or zeppelin. When you traveling by ship or zeppelin you can hear or even see how you character unmount and mount again after loading screen. Sometimes **mounting doesn't happen** and after loading screen you unmount. And **Pet sometimes is gone** after traveling.

on screen i was mounted. After traveling dismounted.
![WoWScrnShot_081521_090657](https://user-images.githubusercontent.com/21084600/129468932-bb55dbc7-3b37-409d-b966-1cd92b27ba9a.jpg)

I think it's a some hack for someting, i dont know.

### Expected Blizzlike Behaviour

No unmount\mount when traveling by ship or zeppelin. No sound. No visible effects. The same on warname.

### Steps to reproduce the problem

traveling by ship or zeppelin

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/6ff9b21b736c5bbf506a1ffa439caadb42c5dbdf

### Operating system

Windows 10 x64

**Comment by lineagedr** [comment]
Pretty sure it's blizzlike

**Comment by Mitradis** [comment]
"Sometimes mounting doesn't happen and after loading screen you unmount. And Pet sometimes is gone after traveling."

**Comment by Azcobu** [comment]
@VFaleiro comments in https://github.com/chromiecraft/chromiecraft/issues/1615:

When running around (while mounted) ships/zeppelins, or even standing by (as soon as the ship/zeppelin begin to move), you can get randomly dismounted as if just walking through a door, but still outdoors. You can mount right after it without any problems.

Zeppelins that got me dismounted:

Tirisfal-Durotar
Tirisfal-Stranglethorn Vale
Durotar-Stranglethorn Vale
Ships that got me dismounted

Ratchet-Booty Bay
Did not test the zeppelin Durotar-Mulgore.

I was playing horde, but for Alliance it probably behaves the same way since most Alliance ships (E.G. Darkshore-Stormwind or Wetlands-Dustwallow) use the exact same model as the Ratchet-Booty Bay ship.

Have no clue about the behaviour of Alliance ships that have no indoors (E.G. Teldrassil-Darkshore or Azuremyst-Darkshore), and evidently Northrend ships/zeppelins cannot be tested (but they also have no indoors).

@Shineslippers adds:

https://user-images.githubusercontent.com/85256266/131997007-92e9346c-eeb7-4ee8-bbfa-7f27da111f9d.mp4

Places for dismount the same. Found atleas 3 on BB ship. Only one condition - transport have to moving. Probably most of them above/near doors.
