### ISSUE TITLE
LBRS rare spawn Spirestone Lord Magus doesn't cast some spells

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#7361]
### Current Behaviour

He appears to only cast `Arcane Bolt` and `Bloodlust` but only on himself once his HP reaches 30%

### Expected Blizzlike Behaviour

He should also cast Enlarge, and Polymorph. He should have the ability to cast bloodlust onto any adds involved in the battle as well. 

### Source

https://www.wowhead.com/npc=9217/spirestone-lord-magus#abilities;mode:normal
https://wowpedia.fandom.com/wiki/Spirestone_Lord_Magus
https://wowwiki-archive.fandom.com/wiki/Spirestone_Lord_Magus
Classic WOW LBRS walkthrough: https://youtu.be/3bKwDcQqINM?t=610

### Steps to reproduce the problem

 `.go c 43521`
If he's not spawned, target his corpse and `.respawn`
Enter into combat and see what he attacks with
Get his health to 30% and watch him self cast Bloodlust
See if he will cast it onto any adds in combat with him

### AC rev. hash/commit

 faef417d9231

### Operating system

Windows 10

**Comment by Asthalor** [comment]
Checking the SmartAi he have this:

![image](https://user-images.githubusercontent.com/87535580/131526934-4868d864-604d-4554-ae3b-35b0a1188a96.png)

Polymorph is set to HOSTILE_RANDOM_NOT_TOP, so that means that he will skip the person with lowest threat. In my testing he dont cast it, so i guess that by being alone he thinks you are the lowest.
When we were 2 he casted it.

![image](https://user-images.githubusercontent.com/87535580/131528743-afac24d1-1fbd-4b04-96be-1d9c6c92a953.png)

Both the enlarge and Bloodlust are with target self, so he wont be able to buff allies. That need fixing.
