### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by DarkmoonRabbit** [azerothcore/azerothcore-wotlk#768]
Is the project dead?

**Comment by Maurowin** [comment]
no!

**Comment by sucofog** [comment]
WTF?

**Comment by Yehonal** [comment]
No, it's not, but would be nice to have more contributors since i've worked
for 2 years and we still don't have any usual contributors.

So now i'm working on improving documentation and installation process.
Also creating a "training platform" because people must learn and help, not
only wait for free fixes.



2018-01-28 8:56 GMT+01:00 DarkmoonRabbit <notifications@github.com>:

**Comment by ShinDarth** [comment]
LoL the project is not dead! Feel free to contribute!
