### ISSUE TITLE
Core/Script: Razorgore the Untamed

### ISSUE THREAD

**Issue by Trystanosaurus** [azerothcore/azerothcore-wotlk#785]
**Description**: Currently there are a number of bugs with the Razorgore encounter, some are minor but others prevent the encounter from being winnable.

**Current behaviour**: 

- [ ] There should be a beam between the orb of domination and Razorgore all the times (at the moment it only shows when the orb is used).
- [ ] Grethok the Controller should be doing a channeling animation before he's engaged.
- [x] The eggs should not be clickable (at the moment they show as clickable but don't do anything).
- [x] Grethok the controller should shout "Intruders have breached the hatchery.." when engaged, not killed.
- [ ] When Grethok is engaged Razegore should start attacking the party.
- [ ] Engaging Grethok should close the entrance gate (at the moment you can click it to close but it doesn't close automatically).
- [ ] At the moment there are two exit gates. There should only be one and it should open when the encounter is over. One is usable by players (called Portcullis) the other is only usable by GM's (Doodad_BOSSGATE01). At the moment both are open before the fight start and close when Grethok is engaged.
- [ ] When you use the orb to control Razorgore you should get the Mind Exhaustion debuff. This actually looks to be a bug on the blizzard WotLK server, in vanilla the debuff is added when the channel ends, so you can't control him twice in a row.
- [ ] Using the orb should also be a channeled ability, it currently has no time limit, from the video it looks to be 90 seconds.
- [ ] Currently using the orb gives a QAE Charm buff (cog icon), the icon should probably be hidden, I think it's just used to set the player's animation?
- [ ] The destroy egg spell on Razorgore should destroy the closest egg in range. Currently it does nothing.
- [ ] Razorgore doesn't seem to take damage normally, he's also immune to .die. He heals to full each time you use the orb I think.
- [ ] The encounter doesn't reset if all party members leave the room/die.

Because I couldn't kill him I couldn't tell if he kills all engaged players if he dies during the egg phase and because the eggs couldn't be destroyed I couldn't test that he moves into phase 2 when they're all gone (a standard tank and spank).

Some id's and things in case it helps..
Creatures:
Grethok the Controller - 12557
Razegore the Untamed - 12435
Objects:
Orb of Domination - 177808
Black Dragon Egg - 177807
Spells:
Destroy Egg - 19873
Mind Exhaustion - 23958
QAE Charm - 42013 (I think)

**Expected behaviour**:
Here's a video I found of him being killed in WotLK - https://www.youtube.com/watch?v=vxSICGXkcjU

**Steps to reproduce the problem**:

1. Go to Black wing lair and fight Razegore.
2. 
3. 

**Branch(es)**: master 

**AC hash/commit**:  7bc6b57

**Operating system**: Windows 10

**Modules**:  None

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by Inifield** [comment]
Hello, i'll try to work on this a bit here's my progress so far (I will edit this post when I fixed something else)
```
-- The eggs should not be clickable
UPDATE `gameobject_template` SET `faction`='14' WHERE  `entry`=177807;
```

**Comment by Middel** [comment]
First of all Nice issue report. 👍 

Second: you are right about everything.
however i think he should not reheal. (not sure about that) but the reason i think that is because all enemies as they enter the room they go for razorgore and the tanks have to make sure that none of the enemies attack razorgore while someone using the orb is destroying the eggs. as soon however when razorgore does hit 1 HP he should do a spell that wipes the entire raid the spell hits the entire room. so that nobody can hide someone and survive. it just kills everyone and reset the fight completely.

atleast thats how it works on retail from what i remember from the fight. i'm not sure about razorgore healing. but i think its not happening. but it could be otherwise. but the rest of my text is for sure true, about the wiping of the raid at 1 HP.

**Comment by Trystanosaurus** [comment]
Ah yeah, I was unclear on that point. It should work as you say, that razorgore takes damage normally and wipes the raid if he dies before all the eggs are destroyed.

At the moment however he doesn't seem to be taking damage normally and I think he heals when he's dismissed from control, which should be fixed.

**Comment by Deltharis** [comment]
While it's not fixed, is there a workaround we could use? This encounter being broken blocks access to the rest of Blackwing Lair without help from GM.

I would be fine with him just being killable.

**Comment by milestorme** [comment]
i don't know how to report it properly because i don't know how the encounter should go, i just know you cant break any eggs , they aren't clickable unless with gm on but even then nothing happens, you cant kill the boss apparently without breaking them, you can use the orb and take over the other guy but the egg smash doesn't smash em, you actually cant get past the first boss in BWL this raid is currently broken because of this.

**Comment by Pondaveia** [comment]
As far as I have been told, people can open the gate and get past. This has been tested by Discord people. Are you sure about this?

**Comment by milestorme** [comment]
if you have a game master with you and .die the boss you can get through the door will open but without a game master the boss cannot be killed and you cannot enter the next area

**Comment by gtao725** [comment]
guys, you are not supposed to click on the eggs to break them, you are supposed to mind control the boss, and then use one of his spells to kill all the eggs in the room. This is an old school vanilla encounter, which is why I guess a lotta people are not familiar with rofl. I can make a video of it from vmangos later.

**Comment by milestorme** [comment]
Yeah your supposed to mind control the boss using the orb  then use the spell egg smash to smash em , did you try to complete it first cause my players tryed everything and the eggs won’t break by the mind controlled boss so razergor won’t die

**Comment by milestorme** [comment]
This is why I didn’t report it because I don’t know how to explain it’s broken , try do the encounter and you will see

**Comment by gtao725** [comment]
yes you are right, I just tested, the eggs cannot be destroyed, and razorgore cannot be killed, its hp drops to 1 and then unkillable. Only GM can get past, either .die boss or gm mode on. Even the 2nd boss isn't scripted correctly, no scene between Vaelstraz and Victor Nefarius (Nefarian). This entire raid may need a rewrite, as with many other vanilla and tbc raids...

**Comment by Pondaveia** [comment]
Thanks for confirmation @milestorme and @comix1988 . Since this is critical I'll try to address it as soon as I can!

**Comment by Endeffect-AT** [comment]
Already a little older issue but I confirm the previous posts & issues.

**Comment by gamedebug** [comment]
"The eggs should not be clickable (at the moment they show as clickable but don't do anything)."
Is this bug fixed?

**Comment by Axaxxax** [comment]
Does anyone have any ideas or a working version?

**Comment by BarbzYHOOL** [comment]
yes, ideas are to port code from cmangos/vmangos

now need some people to actually code it

**Comment by Artanisx** [comment]
Just to confirm the issue with Razorgore's DESTROY EGG spell failing to destroy the eggs still exists.
