### ISSUE TITLE
[Ashenvale] Terrowulf Packlord (rare) moving too fast & wrong spawn timer

### ISSUE THREAD

**Issue by gurveleg** [azerothcore/azerothcore-wotlk#7850]
### Current Behaviour

Terrowulf Packlord GUID 51870 (https://wowgaming.altervista.org/aowow/?npc=3792) is currently on 2h45min spawn timer and has a walking speed set to 1.56

https://user-images.githubusercontent.com/80769357/133116255-a8a6c001-a5c0-49ed-955f-4438323c2e41.mp4

### Expected Blizzlike Behaviour

Terrowulf Packlord should be on a 21-32h spawn time according to wow atlas and wowkiki, wowhead comments confrim this.
His walking speed should be set to normal - what that would be exactly I don't know. Was not able to find a retail WoW video, only from other private servers in which he walked slower.

### Source

https://tbc.wowhead.com/npc=3792/terrowulf-packlord#comments;mode:normal

https://wowwiki-archive.fandom.com/wiki/Terrowulf_Packlord
https://vanillawowdb.com/?npc=3792#comments

![terrowulf](https://user-images.githubusercontent.com/80769357/133115862-625a2d47-972f-473a-9cd5-5cdc77a5dcdd.jpg)

### Steps to reproduce the problem

1. Teleport to GUID 51870 and observe
2. Check DB for entry 3792 and see spawn time and movement speed

### AC rev. hash/commit

AzerothCore rev. 26aee27

### Operating system

Windows 7 x64

**Comment by RealLushen** [comment]
`-- Terrowulf Packlord Fix
-- Lushen#4800 @ Discord

-- This is deleting the Old Entry and adds the new one with the corrected Walking Speed.
DELETE FROM `creature_template` WHERE `entry`=3792;
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `detection_range`, `scale`, `rank`, `dmgschool`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES (3792, 0, 0, 0, 0, 0, 522, 0, 0, 0, 'Terrowulf Packlord', NULL, NULL, 0, 31, 32, 0, 16, 0, 1, 1.14286, 20, 1, 4, 0, 1, 2000, 2000, 1, 1, 1, 0, 2048, 0, 0, 0, 0, 0, 0, 7, 0, 3792, 0, 3792, 0, 0, 49, 69, 'SmartAI', 0, 3, 1, 1.1, 1, 1, 1, 0, 0, 1, 0, 0, 0, '', 12340);

-- This is deleting the Old Entry in the creature Table and adds the new one with a 21h Spawntimer, since thats what the most people
-- expierienced him to spawn at. (approx)
DELETE FROM `creature` WHERE `guid`=3792;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (3792, 5996, 0, 0, 0, 1, 1, 6721, 1, -10610.2, -3506.41, 0.812838, 3.28122, 75600, 0, 0, 2488, 0, 0, 0, 0, 0, '', 0);
`

This should fix the Terrowulf Packlord, did not tested it but there is literally no reason why it should not work :)

Best Regards,
Lushen

**Comment by FrancescoBorzi** [comment]
@syssneck let's not forget to add the Project as well :)
