### ISSUE TITLE
[Minor Quest Bug] Black Shield Incorrect Location

### ISSUE THREAD

**Issue by scott-grimes** [azerothcore/azerothcore-wotlk#7946]
### Current Behaviour

The "Black Shield" (20992) in Dustwallow marsh which starts the quests "Black Shield" (1251/1253 for horde/alliance) is incorrectly positioned at the moment. Only a corner of the shield sticks out of the fireplace. See attached

### Expected Blizzlike Behaviour

Shield should be mounted flat against the wall and easily click-able ala screenshot https://classic.wowhead.com/object=20992/black-shield

### Source

![brokenshield](https://user-images.githubusercontent.com/6396416/133865560-fd4fec8e-afd5-4026-9978-a67167563e16.jpeg)

https://classic.wowhead.com/object=20992/black-shield

### Steps to reproduce the problem

1) .go gobject 20992
2) Observe corner sticking out of wall

### Extra Notes

Resolving this should be fairly easy except I'm not sure how object rotation is calculated. Per documentation at https://www.azerothcore.org/wiki/gameobject

Orientation has values (North = 0, South = 3.14159)

But I'm not sure what 
rotation0
rotation1
rotation2
rotation3
stand in for. 

There's no way to rotate the object in-game, the gm command `gobject turn` at https://github.com/azerothcore/azerothcore-wotlk/blob/2f449326e0ca1795457848721405f35519598829/src/server/scripts/Commands/cs_gobject.cpp#L366 only sets orientation.

I ran some manual sql changes to modify the values but only succeeded in getting the shield stuck further inside the fireplace. Each query requires the worldserver be restarted to take effect (logging out/in did nothing). If someone can let me know how the rotation is calculated (radians, degrees etc) and what the relative positions are I'll calculate how to get it fixed and submit a PR

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

**Comment by patou01** [comment]
Based on gameobject.h, the 4 rotations are a quaternion.
![image](https://user-images.githubusercontent.com/2592673/133879591-c1897d30-59fb-4d89-b4b1-e64cc69cb22a.png)

I'm not sure how to go from there, when I just take some guesses at the values based on an online quaternion calculator, nothing seems to happen.
This is how it's used in the code:
![image](https://user-images.githubusercontent.com/2592673/133879872-a4096011-b069-44a0-8e47-5ac62b588f92.png)

Might need to add a hack on top of a hack on top of a hack there, to add eg at the top. 
` case 20992:

If this is the way it's done, I'd assume other objects that "hang from walls" might have wrong orientations more often, so this might be bad searching on my side. If you know of other objects that are similar, maybe have a look at them to see if they have the same issue?

**Comment by patou01** [comment]
Played some more minutes with it.
If I add the following to the code in gameobject.cpp line 280:
![image](https://user-images.githubusercontent.com/2592673/133887235-39cc29ad-26f0-4b1d-b9d0-7824e0718e22.png)

and change the DB to this:
![image](https://user-images.githubusercontent.com/2592673/133887265-11d6085e-6181-424a-a1cc-bba8a3d7a442.png)

I get the following, while there's some rotation missing, it's "close enough":
https://drive.google.com/file/d/1KNY6g0Zp8R4h8M6eBJ8PyCAntwpct-dA/view?usp=sharing

My understanding is that it's supposed to look like it's about to drop, based on https://www.youtube.com/watch?v=FWCIcjSBdlI .
But if anyone wants to go have a look on current servers, that would tell us exactly what it should be.


If this is "the way" to fix it, then there's not much of a reason to add a function in-game since exceptions need to be handled manually, but maybe just for the sake of not restarting the worldserver 100 times to get it in place it could be useful.

Of course, I might be completely wrong in the way of doing it, but I don't see another entry in the db that one should use, and the rotations don't really seem used to me without adding that exception in the switch(). 

Additionally, here's how I got the quaternions, with a guess and some trials on what would be x/y/z of the object. Make sure you use the right units.
https://www.andre-gaschler.com/rotationconverter/
![image](https://user-images.githubusercontent.com/2592673/133887397-9bf8ef0f-820b-410c-a584-c48015bbb6f2.png)
