### ISSUE TITLE
Brewfest- Only one horde barker seems to be tossing replacement mugs

### ISSUE THREAD

**Issue by Stump876** [azerothcore/azerothcore-wotlk#8027]
### Current Behaviour

For horde, only the `Drohn's Distillery Barker` (GUID 88944) seems to toss new mugs for the event. Even if you are standing right next to another barker. I thought I had another one toss me one once, but I couldn't duplicate it.

https://user-images.githubusercontent.com/68164076/133375981-5071d426-2547-4e6a-8ff9-7ac127280e87.mp4

While all the Alliance barkers will all throw mugs, It's not always the closest one. Technically not broken, but not working as intended either.

### Expected Blizzlike Behaviour

The closest barker should toss you a new mug.  

### Source

I couldn't find a horde source, but in this video the player walks between 2 barkers and the closest one is always tossing her a new mug.
https://youtu.be/4neherfsaEE

### Steps to reproduce the problem

1. Be horde
2. .event start 24 (unless you're doing this between Sep 20- Oct 6)
3. .go c 88944
4. Grab a complimentary mug off the table
5. Run around the area periodically drinking and tossing the mug
6. Pay attention to who is throwing you a new mug.

### AC rev. hash/commit

bd956b5a5750

### Operating system

Windows 10

**Comment by Shineslippers** [comment]
Have to re-open because [T'chali's Voodoo Brewery Barker GUID88942](https://wowgaming.altervista.org/aowow/?npc=24493) doesn't also doesn't throw it instead it's doing [Gordok Brew Barker GUID88955](https://wowgaming.altervista.org/aowow/?npc=23685). Allince side seems ok.

https://user-images.githubusercontent.com/85256266/142621906-e11323c7-f5c6-4f66-b532-e16aac65b281.mp4

2bcd78041eef081c1a60b929af88b3f3d94665c5
