### ISSUE TITLE
[Spell]Warlock's Glyph of Quick Decay not work with Everlasting Affliction

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#8191]
### Current Behaviour

After pr #7559 It happens

### Expected Blizzlike Behaviour

Glyph of Quick Decay should work all the time

### Steps to reproduce the problem

1.learn 47813(Corruption) and 47205(Everlasting Affliction)
2.learn 70948(Glyph of Quick Decay)
3.equip some haste equipment
4.get combat and use spell  47813(Corruption)
5,you can see buff time is correct and Glyph worked
6.now use 47205(Everlasting Affliction)
7.you can see buff time is 18s and Glyph did not work

### AC rev. hash/commit

52aa0e996640dafe2b66d2e68d98ec68f9d9aa5e

### Operating system

Windows 10 x64

**Comment by Algorak** [comment]
yap same Problem

**Comment by bgcfb** [comment]
The snap system is worked but the dot time is not correct

**Comment by Algorak** [comment]
Ok, because we noticed the caster on the server quite often not hit critically even though the end equipment is on. That usually looks like this: 6100+ Sp 80% crit and complete raid support spells like fireball, soul fire and other spells often hit with the smallest hits ... What could be the reason?

**Comment by laasker** [comment]
> 

it should only keep the crit chance and bonus damage auras, i just tested and its not working, gonna open a bug report
