### ISSUE TITLE
[NPC] Wandering skeleton incorrect behavior 

### ISSUE THREAD

**Issue by IntelligentQuantum** [azerothcore/azerothcore-wotlk#8341]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original Post: https://github.com/chromiecraft/chromiecraft/issues/2009

1. [Wandering Skeleton](https://wowgaming.altervista.org/aowow/?npc=10816) could be spawned by using [Mrs. Dalson's Diary](https://wowgaming.altervista.org/aowow/?object=175926) innumerous times 
![WoWScrnShot_100721_155259](https://user-images.githubusercontent.com/85256266/136388289-90f14ad9-095b-46b4-8ae7-a79cc00c87f8.jpg)
2. [Dalson Outhouse Key](https://wowgaming.altervista.org/aowow/?item=12738) available to players without pre-quest [Mrs. Dalson's Diary](https://wowgaming.altervista.org/aowow/?quest=5058) complete
![WoWScrnShot_100721_155355](https://user-images.githubusercontent.com/85256266/136388318-82d62000-1f4e-406c-a225-d04d0d0f0db5.jpg)

### Expected Blizzlike Behaviour

1. There is should exist spawn timer
2. Key shouldn't be obtainable bofore pre-quest

### Source

Wowwiki [Mrs. Dalson's Diary](https://wowwiki-archive.fandom.com/wiki/Mrs._Dalson%27s_Diary)
> Objective of
Needs to be read before you can get the item [Dalson Outhouse Key] from the Wandering Skeleton.

Wowhead [Mrs. Dalson's Diary](https://www.wowhead.com/quest=5058/mrs-dalsons-diary#comments:id=732694)
> By 380570 on 2009/05/31 (Patch 3.1.2)
I noticed in earlier an post, someone had a issue when killing the Wandering Skeleton before reading the diary.
This is exactly what I did. I had killed the Wandering Skeleton, no key.
Went in the barn (which when by the outhouse facing the field, is the building on your left side),
read Mrs. Dalson's Diary, came out and **waited for him to respawn**.
Killed him again and he dropped the key.

### Steps to reproduce the problem

Kill Wandering Skeleton before item used and after use Diary several times.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

**Comment by Shineslippers** [comment]
### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2398

Mrs. Dalson's Diary (the object) prompts the text for the quest. (Quest itself also has the same correct text)
![Screenshot from 2021-11-22 15-53-14](https://user-images.githubusercontent.com/84640316/143443561-71a7374a-696c-45b6-8907-c5d6e0e04203.png)

Tester:

The issue is confirmed. on interact [Mrs. Dalson's Diary](https://wowgaming.altervista.org/aowow/?object=175926) shows same text as quest.
![image](https://user-images.githubusercontent.com/85256266/143452617-1824cf34-f630-426b-a126-c8cc647954bc.png)


### Expected Blizzlike Behaviour

1. Object simply Greets with <name>
2. Add autoaccept to this quest and it will skip object text. Maybe it's not blizzlike wrath, but classic

### Source

Wowhead [Mrs. Dalson's Diary](https://classic.wowhead.com/quest=5058/mrs-dalsons-diary)
> By Alteritus on 2020/01/04 (Classic)
1) Run in the barn and right click the book, you get the option to complete the quest even though you are not doing a quest for it. **_The pickup is instant_**.

> By Highone on 2019/11/02 (Classic)
1) Click on Mrs. Dalson's Diary in the barn. **_Will write completed_**. No exp or next quest.


https://www.youtube.com/watch?v=x1GhK2K-pQA
