### ISSUE TITLE
Cooldown of spell Ravage(53562) can be reset

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#8425]
### Current Behaviour

Hunter`s pet spell Ravage(53562) cooldown can be reset by call pet back

### Expected Blizzlike Behaviour

Cooldown should not reset

### Steps to reproduce the problem

1.use a hunter and get a ravager pet
2.cast pet spell ravage(53562) to attack a target,you can see spell cooldown
3.call pet back and cast ravage again and again
4.you can see cooldown is not worked

### Extra Notes

Someone says crab's spell pin(53548) is also have this problem
It's a big bug in PVP

### AC rev. hash/commit

a6a85c0

### Operating system

Windows 10 x64

**Comment by Shineslippers** [comment]
### Current Behaviour

The issue is confirmed. if you use cast [Ravage](https://wowgaming.altervista.org/aowow/?spell=53562) and after `/petfollow` while pet is not near you able to use Ravage ability again. You can repeat it at least several times. [Pin](https://wowgaming.altervista.org/aowow/?spell=53548) is confirmed also.

https://user-images.githubusercontent.com/85256266/144167642-bfc96a51-f837-49a2-8426-0de434b64008.mp4

### Steps to reproduce the problem

.go c 58836
.pet create
/cast ravage on some NPC
/petfolllow after ability proc
