### ISSUE TITLE
[Hunter] T9 2 piece Serpent Sting Crit dmg wrong scaling

### ISSUE THREAD

**Issue by bgcfb** [azerothcore/azerothcore-wotlk#8859]
### Current Behaviour

https://github.com/dalaranwow/dalaran-wow/issues/3017

### Expected Blizzlike Behaviour

none

### Steps to reproduce the problem

see https://github.com/dalaranwow/dalaran-wow/issues/3017

### AC rev. hash/commit

a25eae3

### Operating system

Windows 10 x64

**Comment by Shineslippers** [comment]
The issue is confirmed. [Mortal Shots](https://wowgaming.altervista.org/aowow/?spell=19485) doesn't apply bonus damage to  [Serpent Sting](https://wowgaming.altervista.org/aowow/?spell=1978).
![WoWScrnShot_110221_235126](https://user-images.githubusercontent.com/85256266/139950669-9bca69cd-ad97-40b2-8e08-956591017c41.jpg)
![WoWScrnShot_110221_235153](https://user-images.githubusercontent.com/85256266/139950674-44893074-d8d2-4055-ba00-252e1e2d5138.jpg)

**Comment by Algorak** [comment]
Can you also watch Resounding Shots, please? The stack behavior is wrong in my opinion and should not be as limited as here. 30% buff in Icc it should tick up to 11.5k Dmg and in 15% buff up to 8.5k.

With you on the Core it is at 15% at 4.8k and at 30% just at 8k there is a massive lack of dmg.

**Comment by Shineslippers** [comment]
@Algorak add links please. I'm not familiar with hunters. Can't find what is Resounding Shots.

**Comment by Algorak** [comment]
> @Algorak füge bitte Links hinzu. Mit Jägern kenne ich mich nicht aus. Kann nicht finden, was Resounding Shots ist.

Sry /spell=53234 this ist a Talent The stack behavior should always take the value of Crit for each Crit and then stack. But here it is so that from a certain value the magic / spell = 53234 gets a reset and starts again at 0. But if I hit critically in the long term, the stack should not be set again but should remain active until it no longer hits critical. That makes the hunter strong.

**Comment by Shineslippers** [comment]
@Algorak i would say it's working as intended. If issue exist it's somewhere else.
- Aimed Shot `21*8/568=29.6%`
- Steady Shot `13*8/348=29.9%`
- Chimera shot `7*8/200=28%`
![WoWScrnShot_112321_205524](https://user-images.githubusercontent.com/85256266/143078678-8aa92f5d-410a-4dba-9fd2-021bb752cac3.jpg)
![WoWScrnShot_112321_205835](https://user-images.githubusercontent.com/85256266/143079052-29269620-b09f-4a73-9aea-89e6ca304a9f.jpg)
![WoWScrnShot_112321_210015](https://user-images.githubusercontent.com/85256266/143079226-67af3a7c-b981-4d47-8107-acc87445b2ac.jpg)

**Comment by Algorak** [comment]
> @Algorak Ich würde sagen, es funktioniert wie beabsichtigt. Wenn ein Problem besteht, liegt es woanders. Nicht mit Talent.
> 
> * Gezielter Schuss `21*8/568=29.6%`
> * Ruhiger Schuss `13*8/348=29.9%`
> * Chimäre geschossen `7*8/200=28%`
>   ![WoWScrnShot_112321_205524](https://user-images.githubusercontent.com/85256266/143078678-8aa92f5d-410a-4dba-9fd2-021bb752cac3.jpg)
>   ![WoWScrnShot_112321_205835](https://user-images.githubusercontent.com/85256266/143079052-29269620-b09f-4a73-9aea-89e6ca304a9f.jpg)
>   ![WoWScrnShot_112321_210015](https://user-images.githubusercontent.com/85256266/143079226-67af3a7c-b981-4d47-8107-acc87445b2ac.jpg)

Hey, it's not about the spells themselves, it's about the stacking behavior. If I hit critical with all spells in a row, the stack should always add the old value to the new value so that the damage stacks properly.


Here it often happens that, for example, after the first stack has expired, the value is recalculated from zero, although the 2 old stacks were still stacked.

So it happens that the magic is recalculated through the new meeting, although in fact 2603 dmg were still active on the target. The new critical hit simply ignores the 2 stacks of the 2 previous spells and starts over with the 30% damage. I noticed that very often. And when I compare other cores it seems to be doing great. Unfortunately, there are hardly any hunters who do not do dmg with this stack and we are actually all quite good players.

**Comment by Shineslippers** [comment]
@Algorak Nothing there.
![image](https://user-images.githubusercontent.com/85256266/143437671-68db53f6-3343-48e1-9e9f-28b4e54d90a6.png)
![image](https://user-images.githubusercontent.com/85256266/143437977-afb7c891-7d2f-4390-8551-762963620706.png)
![image](https://user-images.githubusercontent.com/85256266/143438215-2bdd80ad-5316-4c60-87c6-888f047d8880.png)

**Comment by Algorak** [comment]
> @Algorak Nichts da. ![Bild](https://user-images.githubusercontent.com/85256266/143437671-68db53f6-3343-48e1-9e9f-28b4e54d90a6.png) ![Bild](https://user-images.githubusercontent.com/85256266/143437977-afb7c891-7d2f-4390-8551-762963620706.png) ![Bild](https://user-images.githubusercontent.com/85256266/143438215-2bdd80ad-5316-4c60-87c6-888f047d8880.png)


Test one on Trinity 
Aimed Shot crit 1520   || Dot-damage: 1520*0.3=456 → 456/8=57
Piercing Shots Tick 57  
Piercing Shots Tick 57
Piercing Shots Tick 57 || Residual damage on the DoT: 456-(3*57)=285
Aimed Shot crit 1423   || DoT- damage 1423*0,3=426,9 → Adding the DoTs: 426+285=711 → 711/8=88,875
Piercing Shots Tick 88 || Anm.: WoW always rounds off
Piercing Shots Tick 88
Piercing Shots Tick 88
Piercing Shots Tick 88
Piercing Shots Tick 88
Piercing Shots Tick 88
Piercing Shots Tick 88
Piercing Shots Tick 88



test Two 
Aimed Shot Crit 0 (1173 absor) || 1173*0,3=351,9 → 351/8=43,875 → 43
Piering Shots Tick 43
Chimaera Shot Crit 2145 ||  2145*0,3=643,5 → trunc(643/8)+trunc(7*43/8) → 80+37=117  
Piercing Shot Tick 117

As I said, the remaining dmg from the first point should always be assessed on the new value.
I don't know if it is comparable to ours, but unfortunately I can no longer find the comparisons from World of Logs. It was just perfect there.

If you say it's ok then I trust you there but the Hunter doesn't feel good to me

**Comment by Shineslippers** [comment]
>As I said, the remaining dmg from the first point should always be assessed on the new value.
@Algorak I'm not saying anything. It's math doing it instead of me. Look to my screenshots. There is exactly same situation that you said about. Same as on Trinity also. When i'm applying new crit `Piercing Shots` getting more and more damage. You have to try do math by yourself with my screenshots:
1. Calculate all `Piercing Shots` damage
2. Calculate all `Abilities damage`
3. Divide `Piercing Shots` by `Abilities damage`

I will do it for your trinity logs as example
1. 57*3 + 88*8 = 875
2. 1520 + 1423 = 2943
3. 875 / 2943 = 0.2973 ~ 30%

1. 43 + 117*8 = 979
2. 1173 + 2145 = 3318
3. 979 / 3318 = 0.295 ~30%
