### ISSUE TITLE
Spell casting suspend swing's timer of Auto Attack

### ISSUE THREAD

**Issue by Mitradis** [azerothcore/azerothcore-wotlk#8899]
### Current Behaviour

I noticed this a long time ago. If you attack target with spells, you fisrt weapon hit must wait weapon cooldown before weapon will commit first hit. This pause (between the time the target is available to hit and hit) very annoying.

https://user-images.githubusercontent.com/21084600/139868575-823e15b8-c4d0-4287-8d8d-715e55f2b129.mp4

### Expected Blizzlike Behaviour

If target available for melee attack weapon does not wait pause for first hit.

### Steps to reproduce the problem

dont stop attack target with range spells
when the target is close enough to hit with the weapon, stop casting and wait hit...

### AC rev. hash/commit

2d38f36555e59e00131c5813da7b300a0a85179a

### Operating system

windows 10

**Comment by Shineslippers** [comment]
I'm not sure, but for example on TBC looks like this is exist.
https://youtu.be/TXYBPPEMmbU?t=957

**Comment by Mitradis** [comment]
I proceeded from the fact If i cast spell after weapon hit this not cause start GCD for weapon. GCD and spell cast not bind.

**Comment by Algorak** [comment]
Automatic attacks should always be used when a buffer is in place. That said, I always trigger car hits, even when I use a spell, it should come right away when the time is right. There are classes like Ele-Shaman that have a hybrid skill with the spell /? Spell = 16284 games.
The attacks between spells are very important.

That actually means spell, attack then spell, attack then spell, attack The spell should not be interrupted by this, but it still spells and carries out the attack with the weapon.

Even with healers like the Holy Paladin, who gains mana through his seal because he carries out automatic attacks.

**Comment by Shineslippers** [comment]
`.go c 202727` `.cast 585`

https://user-images.githubusercontent.com/85256266/143081688-89b9c242-2b5f-408f-b4f5-da144226a946.mp4

**Comment by T1ti** [comment]
Afaik spell casting shouldn't entirely reset the swing timer, it should only reset the 2nd attack anim phase(2nd half)

**Comment by laasker** [comment]
I have noticed this bug alot, but i always thought it was because i swapped targets.

This is a pain in the ass for feral druids, sometimes you cast Cyclone on one target and go to Cat Form to attack another target, but you need to wait a few seconds for the auto attack to start, because the first delayed auto attack is based on the Weapon Speed and not on the Cat Form Attack Speed (1.0)

Doing a little bit of testing, i noticed that Innervate and Hurricane doesnt delay your next auto attack

https://user-images.githubusercontent.com/79991768/143192677-85d7940e-f470-4507-a38a-15cc05b7ce3c.mp4

**Comment by Algorak** [comment]
I wouldn't be surprised if hunters have the same problem when casting a spell.

**Comment by Mitradis** [comment]
> This is a pain in the ass
same)) because of this, I did not play on the server. I don't want to watch silly expectations. I don't remember such problems on the official servers.

**Comment by UltraNix** [comment]
Just tested on retails and it works the same. I see no bug here.

**Comment by T1ti** [comment]
> 

though the message about feral is probably right, deesn't seem normal that shapeshifting to feral with 1.0s speed still has you wait 3seconds for your first auto https://github.com/azerothcore/azerothcore-wotlk/issues/8899#issuecomment-977598956

**Comment by T1ti** [comment]
@UltraNix

**Comment by UltraNix** [comment]
@T1ti Shapeshifts are spells, so it works as other spells - on cast the swing timer is reset. The question is - should the shapeshifting reset or not swing timer?
