### ISSUE TITLE
Various Dungeons - Visible Triggers

### ISSUE THREAD

**Issue by Trystanosaurus** [azerothcore/azerothcore-wotlk#897]
**Description**:
There are quite a few encounters where triggers (usually look like infernals or imps) are visible.
I've made this issue to try and collect some of them so they can be fixed. If you'd prefer separate issues/pull requests I can do that instead.

**Current behaviour**: 
On some fights you can see infernals that should be invisible, usually for boss abilities that target an area.

**Expected behaviour**: 
The triggers should be invisible, which can be done by adding 128 to flags_extra in the triggers creature template.

**Steps to reproduce the problem**:

1. Engage a boss with this bug.
2. Keep an eye out for infernals

** Bosses found so far and ID's to fix **

- [ ] Zul'Aman - Jan'alai (Dragonhawk boss): Visible infernals for his Firebomb, they're creature_template 23920 - Firebomb (Zul'Aman)
- [x] Auchenai Crypts - Shirrak the Dead Watcher: Visible infernal when he focuses. Creature template 18374 - Focus Fire. There's also 20308 - Focus Fire (1) which I guess might be supposed to be used for Heroic but it's currently not used.
- [ ] Mount Hyjal - Archimonde: Doomfire trails have a little infernal at the head of them. 18095 - Doomfire and 18104 - Doomfire Spirit.

**Branch(es)**: master

**AC hash/commit**:  825a62b

**Operating system**:  Windows 10

**Modules**:  VAS Autobalance

**Other Customizations**: Are you using any core/db patches or other customizations? If yes please specify them here.

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

**Comment by BarbzYHOOL** [comment]
Do they have something in common to "uniquely" identify them?

For example a modelid, a special flag, a name or subname?

If so we could just select them all with one query and update them

**Comment by pondaveia** [comment]
The Creature_template.entry is unique for alot of triggers. Since triggers should be invisible there's no issue if you simply make them all invisible.
Something like:
``` SQL
REPLACE INTO creature_template(flags_extra) VALUES (128) WHERE entry = 23920 or entry = 18374 or entry = 20308 or entry = 18095 or entry = 18104;
```

**Comment by Deku** [comment]
Agree with @BarbzYHOOL , we should look for a generic solution instead of finding them one by one. A priori I'm thinking on modelId, flags, movementtype, hp/mana

**Comment by pondaveia** [comment]
It's not like every trigger in Azerorthcore is visible, It's such a simple solution i don't understand why is it so hard to fix them as bugs get reported. It's literally impossible to put every trigger invisible because there is no common flags among them except flags_extra which, guess what? It's 0 because they are visible. Everything else is just volatile information which, if you query it, you will break alot of stuff.
Just fix entry by entry...

**Comment by BarbzYHOOL** [comment]
Hmm, I compared all triggers in the db... and it's pure bullshit, really

They often have different damage, different HP, different modelids, different faction, different name and subname (some have "triggers" some don't...), different level (instead of all being lvl1), even different unit_class, different movementtype (some move, some don't) etc...

And for the models, some are invisibles, some are infernals, some are a flying staff. Some are named "Eranikus" and they are in gnomeregan...................................................... this is awful

This is really horrible work, I don't know how they've been done, maybe with sniffs?

**Comment by Trystanosaurus** [comment]
A generic solution would be great but I think by the time one's found you'll have spent longer than just looking normally. It might be a nice way to get new people into helping with the core though, write a guide on how to find/report/pr visible triggers. There are a few doors that shouldn't mouse-over for players that currently do as well, so they could be done similarly.

For just infernals, I did a search in the database (below) that gave me 62 hits, most of which can be made invisible. As a start it won't take too long to go through those hits and decide which ones obviously need to be fixed.

```SELECT * FROM `world`.`creature_template` WHERE (`modelid1` = '1126' or `modelid1` = '1126' or `modelid2` = '11686') and `flags_extra` = '0'```

**Comment by Deku** [comment]
Well, seems like it the old way here. We should seize this opportunity to standardize triggers (at least in the sub name?).

And please, use `WHERE entry IN (111, 222, 333, ...)` 🤣

**Comment by BarbzYHOOL** [comment]
I took some of the common modelID and made a query to show which triggers are visibles

```
SELECT * FROM creature_template
WHERE (modelid1 IN (11686,16946,169,1126,7804,16480)
OR modelid2 IN (11686,16946,169,1126,7804,16480)
OR modelid3 IN (11686,16946,169,1126,7804,16480))
AND lootid = 0
AND maxgold = 0
AND flags_extra != flags_extra | 128
```

This is a small list because there are many more modelid and some are probably unknown.
Then we could update them all but I tried to spawn 4 of them from that list and they are all not spawned ingame, so I don't know if they are used for an event or if they are just unused... All of this would require more researches

**Comment by Deku** [comment]
Don't forget to check in the `creature` table for extra attributes using a SQL Join !

**Comment by BarbzYHOOL** [comment]
Try this and compare (first table = creature)

```
SELECT *
FROM creature
JOIN `creature_template`
ON ID = entry
WHERE `entry` IN (23920,18374,18104,20308,18095)
OR flags_extra = flags_extra | 128
LIMIT 200
```
