### ISSUE TITLE
Warrior not showing second weapon

### ISSUE THREAD

**Issue by pe93** [azerothcore/azerothcore-wotlk#9108]
### Current Behaviour

So i have a lvl 80 warrior with 2x 2handed weapon (fury). When i engage a battle the offhand becomes invisible. It hits and is still equipped but doesnt sho up on the screen.

### Expected Blizzlike Behaviour

you should see both weapons

### Steps to reproduce the problem

Get a LVL 80 warrior with the fury talent Titans Grip and equip 2 2handed weapons and engage a battle

### AC rev. hash/commit

b2f0893

### Operating system

Win 10 running with docker

**Comment by Cinnamohn** [comment]
Is it when Deathbringer's Will procs and transforms you?

**Comment by pe93** [comment]
tested and confirmed. it is when Deathbringer's Will procs.

**Comment by Algorak** [comment]
Is offilike and cannot be customized;)

**Comment by Shineslippers** [comment]
### Current Behaviour

The issue is confirmed. If you hande something in `ranged` slot after [Deathbringer's Will](https://wowgaming.altervista.org/aowow/?item=50362) proc you turn into model with one weapon. If you doesn't have `ranged` slot equipped everything is ok.

https://user-images.githubusercontent.com/85256266/144075220-603eb3b5-73ab-467e-95dd-9e87956a6de2.mp4

### Expected Behaviour

Player should have same weapon layout after transform

**Comment by avarishd** [comment]
Blizzard bug, client side only ("unfixable") - https://www.wowhead.com/item=50362/deathbringers-will#comments:id=1022691;80
TC has that "issue" closed from 2011 (# 3927)
