### ISSUE TITLE
DeathKnight tier9 incorrect damage

### ISSUE THREAD

**Issue by xojld0** [azerothcore/azerothcore-wotlk#915]
Description: If you put on dk full tier 9 set and pumped two specs 71 0 0 (blood) and 0 71 0 (ice) and change the specs, the damage from dk will drop: x115, x111, x106, x102, x98 ...
![image](https://user-images.githubusercontent.com/34447743/41190274-d2b64488-6bdb-11e8-91d7-bbfc40c9ac00.png)
![image](https://user-images.githubusercontent.com/34447743/41190261-97c6f142-6bdb-11e8-9fa3-3fd343cb108a.png)

Current behaviour: In this case, the damage of dk will decrease with each change of spec.

Expected behaviour: When changing the spec to the shooting range of 9 sets, the damage should almost not change: x115, x120, x115, x120 ...

Steps to reproduce the problem:

1. Create dk
2. Complete the quest chain
3. Get Level 80
4. To study the double specialization
5. Download the first speck blood on 71 (71 0 0) and the second frost spec on 71 (0 71 0)
6. Dress full Tier 9 set
7. Change the spec from the blood to frost, from frost to blood and look at the damage in the information about the character.

Branch(es): master

AC hash/commit:  7256dc30a9e9

Operating system:  Linux, ubuntu 16.04

Modules: mod-transmog, mod-premium, mod-anticheat.

Other Customizations: no

**Comment by talamortis** [comment]
Im sure this is just  a visual issue. most servers have this error

**Comment by xojld0** [comment]
Unfortunately, this is not a visual problem. If you try to beat a mannequin, then the damage will be appropriate.
x120(blood) = ~322
![image](https://user-images.githubusercontent.com/34447743/41191282-679982ca-6bed-11e8-8745-8e7eca99d4f0.png)
x102(blood) = ~303
![image](https://user-images.githubusercontent.com/34447743/41191338-3b448872-6bee-11e8-91f4-5770cc754745.png)

**Comment by BarbzYHOOL** [comment]
Thank you ayase, this is some serious issue imo

**Comment by Nefertumm** [comment]
I can't reproduce it on 334a0f3e2c5c43be448be8dbcfc9d6dffeb64266.

**Comment by BarbzYHOOL** [comment]
hmmm but ayase could, need someone else to test then

**Comment by Knindzagxg** [comment]
This is super simple folks, and damage will be different no matter which Tier you put on.
Blood spec is supposed to be tanking one, and have extra Attack Power, not only via Buff, but also via Armor.

Those will be missed in Frost spec, since you wanted to test 71 talent in single one.
Bladed Armor will increase Attack power by 5 for each 180 armor you have in Blood.
Abomination's Might, will increase Attack Power by 10% (Group wise) and extra 2% STR.
Both of these will give extra Damage to tanks in blood spec so they can keep agrro.

Frost is supposed to be dual wield spec, with much faster attacks and better resource recovery but lower Attack power.

Video bellow as well.

https://www.youtube.com/watch?v=WEpju1jy9_w&feature=youtu.be

**Comment by BarbzYHOOL** [comment]
So it's a valid issue or not? (I guess it's not)

**Comment by Knindzagxg** [comment]
I don't see any issue with this at all.

**Comment by BarbzYHOOL** [comment]
If someone confirms this issue again, we'll reopen it.
