### ISSUE TITLE
Characters not saved due to DB deadlocks (character_queststatus_daily)

### ISSUE THREAD

**Issue by temperrr** [azerothcore/azerothcore-wotlk#9630]
### Current Behaviour

Some characters are not getting saved.

### Expected Blizzlike Behaviour

Characters getting saved.

### Steps to reproduce the problem

Not sure how to reproduce. Is happening on CC.

### Extra Notes
```
2021-12-11_05:30:35 ERROR [sql.sql] [1213] Deadlock found when trying to get lock; try restarting transaction
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
2021-12-11_06:15:58 WARN [sql.sql] Transaction aborted. 41 queries not executed.
2021-12-11_06:00:03 ERROR [sql.sql] SQL(p): INSERT INTO character_queststatus_daily (guid, quest, time) VALUES (170807, 24883, 1639202403)
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
2021-12-11_06:00:03 WARN [sql.sql] Transaction aborted. 53 queries not executed.
```
### AC rev. hash/commit

0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

W11

### Custom changes or Modules

-

**Comment by Nyeriah** [comment]
2021-12-11_05:30:35 ERROR [sql.sql] [1213] Deadlock found when trying to get lock; try restarting transaction
[2:47 PM]
[2:48 PM]
[ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
2021-12-11_06:15:58 WARN  [sql.sql] Transaction aborted. 41 queries not executed.
[2:48 PM]
2021-12-11_06:00:03 ERROR [sql.sql] SQL(p): INSERT INTO character_queststatus_daily (guid, quest, time) VALUES (170807, 24883, 1639202403)
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
2021-12-11_06:00:03 WARN  [sql.sql] Transaction aborted. 53 queries not executed.

Turns out this is not related to the shutdowns but some players might not be saving properly due to a deadlock in the quest tables

@Winfidonarleyan @UltraNix do either of you have any info on this?

**Comment by Nyeriah** [comment]
Just to add: we started receiving reports about this in the past two weeks. My understanding is that if those deadlocks don't solve themselves between one save and another, this could lead to entire play sessions not being saved, so a pretty critical issue.

**Comment by UltraNix** [comment]
It's hard to fix this without replication. I don't know even if this is save from `Player::Update` or from logout.

**Comment by temperrr** [comment]
This happens on CC, PTR and local

**Comment by temperrr** [comment]
Log in, move somewhere else, stay there for half an hour, let the server crash, you are not saved.

**Comment by Nyeriah** [comment]
> It's hard to fix this without replication. I don't know even if this is save from `Player::Update` or from logout. @Nyeriah This happens on PTR?

This happens on the live server.

I noticed that AC has some code that fires a full save whenever quests are rewarded. Those quests causing the deadlock are the RDF quests from what I can see. I wonder if that could have anything to do with it?

**Comment by UltraNix** [comment]
You can disable that code for tests.

**Comment by Winfidonarleyan** [comment]
Maybe #9712 can fix this

**Comment by Winfidonarleyan** [comment]
I'll do it.

**Comment by temperrr** [comment]
@Winfidonarleyan 

Any update? It keeps rolling back individuals on ChromieCraft during server reboot.

**Comment by temperrr** [comment]
(this confirms my suspicions...)
![image](https://user-images.githubusercontent.com/20357406/146634992-6d51ec5d-82ed-4aec-96bb-cf0ef299c3d5.png)
They didnt logout and let themselves get kicked by the server.

**Comment by Winfidonarleyan** [comment]
> 

I'll start working on it tomorrow

**Comment by Winfidonarleyan** [comment]
> @Winfidonarleyan
> 
> Any update? It keeps rolling back individuals on ChromieCraft during server reboot.

I'll start working on it tomorrow
