### ISSUE TITLE
 Glyph of Aimed Shot is affecting Multi-Shot

### ISSUE THREAD

**Issue by Shineslippers** [azerothcore/azerothcore-wotlk#9707]
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2565

Reach lvl 20 with a marksman hunter, use Glyph of Aimed Shot in order to reduce Aimed Shot cd with 2 sec. After this action Multi-shot cd is 10 sec and Aimed Shot is 8 sec. 
If hunter attack with Multi-shot (Aimed shot not used yet), cd of both spells (Multi-shot and Aimed shot) will be 10 sec.
If hunter attack with Aimed Shot (Multi-shot not used yet),  cd of both spells (Multi-shot and Aimed shot) will be 8 sec.

Tester:

The issue is confirmed. [Glyph of Aimed Shot](https://wowgaming.altervista.org/aowow/?item=42897) is affecting [Multi-Shot](https://wowgaming.altervista.org/aowow/?spell=2643) if it's used after [Aimed Shot](https://wowgaming.altervista.org/aowow/?spell=19434). Also after using Multi CD for Aimed is 10s.

https://user-images.githubusercontent.com/85256266/146073689-721bbcfc-72b3-4d3a-9176-3f7affb97412.mp4

### Expected Blizzlike Behaviour

Glyph of Aimed Shot should not affect Multi-Shot since there is exist glyph for Multi-Shot

### Steps to reproduce the problem

create hunter
.go c 202727
.learn 2643
.learn 19434
.aura 56824

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

**Comment by bonfax4** [comment]
I'm not sure what's the policy here about reopening issues but this is in fact correct behaviour that can be seen on old hunter pvp videos like [this](https://youtu.be/a5_mTxNmYuk)  since aimed shot glyph is taken for pvp usually. @0:53 seconds aimed shot is casted and cool down ends @ 1:01 along with multi-shot. Spell used seems to indicate the CD both spells will take.

**Comment by bonfax4** [comment]
https://youtu.be/G_m9hwU75No
Even more obvious here since this guy uses omnicc

**Comment by bonfax4** [comment]
@Nyeriah  @UltraNix @Shineslippers  I'm not sure what's the policy here about reopening issues but [this](https://youtu.be/a5_mTxNmYuk) is in fact correct behaviour that can be seen on old hunter pvp videos like this since aimed shot glyph is taken for pvp usually. @0:53 seconds aimed shot is casted and cool down ends @ 1:01 along with multi-shot. Spell used seems to indicate the CD both spells will take.

https://youtu.be/G_m9hwU75No
Even more obvious here since this guy uses omnicc to show CD timers
