### ISSUE TITLE
 Creature has wrong spell 0 defined in auras field

### ISSUE THREAD

**Issue by catontheway** [azerothcore/azerothcore-wotlk#9763]
### Current Behaviour

run worldserver.exe 
Console print error
like this:

![error](https://user-images.githubusercontent.com/6520412/146650778-99641751-1286-4a6b-b32b-4b5971c56637.jpg)

### Expected Blizzlike Behaviour

no error

### Steps to reproduce the problem

run worldserver.exe

### AC rev. hash/commit

AzerothCore rev. e1f176f51b81 2021-12-18 14:20:16 +0100 (master branch) (Win64, Release, Static)
Using SSL version: OpenSSL 1.1.1h  22 Sep 2020 (library: OpenSSL 1.1.1h  22 Sep 2020)
Using Boost version: 1.72.0
Using MySQL version: 50731
Using CMake version: 3.18.4
Compiled on: Windows 10.0.19041
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in Data/maps. Total size: 252190595 bytes
vmaps directory located in Data/vmaps. Total size: 658130553 bytes
mmaps directory located in Data/mmaps. Total size: 2196364992 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.5-dev
Using World DB Revision: 2021_12_18_02
Using Character DB Revision: 2021_10_14_00
Using Auth DB Revision: 2021_10_14_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

### Operating system

windows 10 x64

**Comment by LondoBell0090** [comment]
Yes, I also made this mistake. I investigated it for a long time, but I didn't find it

**Comment by Kitzunu** [comment]
It's a weird thing. Ignore it.

**Comment by LondoBell0090** [comment]
> It's a weird thing. Ignore it.

I have changed to older source code to compile.             : (

**Comment by Kitzunu** [comment]
You can still compile. This is just a weird db error that doesnt affect anything

**Comment by adink1** [comment]
Can it be solved? The previous code did not have this error.

**Comment by catontheway** [comment]
thanks guys

**Comment by virgo77** [comment]
Hi there! it seems that an update has resolved the issue. I tried it this morning and it seems ok. So, thanks for the job! You roxx :D
I will check for the WorldServer and the MariaDB 10.5 / 10.6 compatibility error. Because actually I run on MySQL, but I got now a dedicated SQL Server at Home. So I will try to migrate to MariaDB soon.

And I will search for another posts:
- about WorldServer and some "WaypointMovementGenerator - creature does not have waypoint"
- for some "Gameobject not created: non-existing entry in `gameobject_template`"
- and, erm, I will abuse a little bit (sorry about that): about the NPC Smooth Movements that are really... not so smoothly as they would like to ^^

See you soon :)

V.
